/**
 * ENVIRONMENT REGISTRY
 * Maintains a registry of environments for video generation.
 * Plain JS module with ESM exports. No framework dependencies.
 */

export class EnvironmentRegistry {
  constructor() {
    this._registry = new Map();
    this._categoryIndex = new Map();
    this._typeIndex = new Map();
    this._initDefaults();
  }

  _initDefaults() {
    const environments = [
      { id: 'downtown_city', name: 'Downtown City', type: 'urban', category: 'Urban', location: 'city center', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'modern high-rise', condition: 'well-maintained', materials: ['glass', 'steel', 'concrete'] }, lighting: { natural: 'daylight', artificial: 'streetlights, office windows' }, color_palette: ['cool gray', 'blue', 'white', 'asphalt'], background_activity: ['pedestrians', 'traffic', 'street vendors'], continuity_reference: 'consistent street grid and building facades' },
      { id: 'financial_district', name: 'Financial District', type: 'urban', category: 'Urban', location: 'business district', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'light', fog: 'none' }, architecture: { style: 'tower blocks', condition: 'pristine', materials: ['glass', 'steel', 'marble'] }, lighting: { natural: 'bright daylight', artificial: 'facade lights, lobby glow' }, color_palette: ['navy', 'silver', 'glass blue', 'marble white'], background_activity: ['commuters', 'security', 'business pedestrians'], continuity_reference: 'consistent tower skyline' },
      { id: 'tech_campus', name: 'Tech Campus', type: 'urban', category: 'Urban', location: 'suburban campus', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'light', fog: 'none' }, architecture: { style: 'modern campus', condition: 'modern', materials: ['glass', 'steel', 'brick', 'green walls'] }, lighting: { natural: 'diffused daylight', artificial: 'LED strips, signage' }, color_palette: ['green', 'white', 'accent blue', 'wood'], background_activity: ['employees', 'bicycles', 'shuttle buses'], continuity_reference: 'consistent building wings and landscaping' },
      { id: 'warehouse_district', name: 'Warehouse District', type: 'urban', category: 'Urban', location: 'industrial waterfront', time: { timeOfDay: 'dusk', season: 'any', era: 'mixed' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'industrial', condition: 'weathered', materials: ['brick', 'corrugated metal', 'concrete'] }, lighting: { natural: 'golden hour', artificial: 'security lights, neon signs' }, color_palette: ['rust', 'gray', 'neon orange', 'shadow'], background_activity: ['workers', 'trucks', 'forklifts'], continuity_reference: 'consistent warehouse row and graffiti walls' },
      { id: 'subway_station', name: 'Subway Station', type: 'urban', category: 'Urban', location: 'underground transit', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'dry', intensity: 'none', wind: 'still', fog: 'none' }, architecture: { style: 'modern transit', condition: 'worn', materials: ['tile', 'steel', 'concrete'] }, lighting: { natural: 'none', artificial: 'fluorescent, platform lights' }, color_palette: ['white', 'gray', 'yellow', 'advertising red'], background_activity: ['commuters', 'musicians', 'rats'], continuity_reference: 'consistent tile patterns and platform edges' },
      { id: 'rooftop_bar', name: 'Rooftop Bar', type: 'urban', category: 'Urban', location: 'high-rise rooftop', time: { timeOfDay: 'night', season: 'summer', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'modern terrace', condition: 'stylish', materials: ['glass', 'wood', 'steel', 'rope'] }, lighting: { natural: 'city lights', artificial: 'string lights, bar lamps' }, color_palette: ['amber', 'navy', 'gold', 'deep red'], background_activity: ['guests', 'bartenders', 'city hum'], continuity_reference: 'consistent railing and skyline framing' },
      { id: 'alleyway', name: 'Alleyway', type: 'urban', category: 'Urban', location: 'between buildings', time: { timeOfDay: 'night', season: 'any', era: 'any' }, weather: { condition: 'rain', intensity: 'moderate', wind: 'light', fog: 'none' }, architecture: { style: 'narrow urban', condition: 'gritty', materials: ['brick', 'concrete', 'metal'] }, lighting: { natural: 'moonlight', artificial: 'flickering neon, dumpster light' }, color_palette: ['black', 'neon green', 'wet asphalt', 'shadow'], background_activity: ['rats', 'dripping water', 'distant traffic'], continuity_reference: 'consistent brick patterns and fire escapes' },
      { id: 'parking_garage', name: 'Parking Garage', type: 'urban', category: 'Urban', location: 'multi-level structure', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'dry', intensity: 'none', wind: 'still', fog: 'none' }, architecture: { style: 'concrete brutalist', condition: 'worn', materials: ['concrete', 'steel', 'paint'] }, lighting: { natural: 'none', artificial: 'sodium vapor, fluorescent' }, color_palette: ['gray', 'yellow', 'orange', 'shadow'], background_activity: ['echoing footsteps', 'distant car alarms'], continuity_reference: 'consistent ramp angles and painted arrows' },
      { id: 'construction_site', name: 'Construction Site', type: 'urban', category: 'Urban', location: 'development zone', time: { timeOfDay: 'day', season: 'spring', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'unfinished', condition: 'active', materials: ['steel', 'concrete', 'crane'] }, lighting: { natural: 'daylight', artificial: 'safety lights, beacons' }, color_palette: ['orange', 'yellow', 'steel gray', 'earth brown'], background_activity: ['workers', 'cranes', 'trucks'], continuity_reference: 'consistent crane position and scaffolding' },
      { id: 'shopping_mall', name: 'Shopping Mall', type: 'urban', category: 'Urban', location: 'indoor complex', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'modern mall', condition: 'clean', materials: ['glass', 'tile', 'steel'] }, lighting: { natural: 'skylight', artificial: 'overhead, store displays' }, color_palette: ['white', 'pastel', 'brand colors', 'chrome'], background_activity: ['shoppers', 'kids running', 'mall music'], continuity_reference: 'consistent food court and atrium layout' },
      { id: 'airport_terminal', name: 'Airport Terminal', type: 'urban', category: 'Urban', location: 'international airport', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'modern terminal', condition: 'busy', materials: ['glass', 'steel', 'terrazzo'] }, lighting: { natural: 'skylight', artificial: 'overhead, gate signs' }, color_palette: ['white', 'blue', 'gray', 'airline red'], background_activity: ['travelers', 'carts', 'announcements'], continuity_reference: 'consistent gate numbers and signage' },
      { id: 'hotel_lobby', name: 'Hotel Lobby', type: 'urban', category: 'Urban', location: 'luxury hotel', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'luxury', condition: 'pristine', materials: ['marble', 'brass', 'glass', 'wood'] }, lighting: { natural: 'crystal chandeliers', artificial: 'warm sconces' }, color_palette: ['gold', 'cream', 'marble white', 'deep red'], background_activity: ['guests', 'bellhops', 'piano music'], continuity_reference: 'consistent chandelier and front desk layout' },
      { id: 'startup_office', name: 'Startup Office', type: 'urban', category: 'Urban', location: 'open-plan office', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'open plan', condition: 'lived-in', materials: ['wood', 'glass', 'concrete'] }, lighting: { natural: 'large windows', artificial: 'desk lamps, neon signs' }, color_palette: ['white', 'teal', 'wood', 'brand accent'], background_activity: ['engineers', 'standup meetings', 'coffee'], continuity_reference: 'consistent desk clusters and whiteboard walls' },
      { id: 'corporate_hq', name: 'Corporate HQ', type: 'urban', category: 'Urban', location: 'tower headquarters', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'corporate', condition: 'pristine', materials: ['glass', 'steel', 'marble'] }, lighting: { natural: 'floor-to-ceiling windows', artificial: 'recessed, boardroom lights' }, color_palette: ['navy', 'gray', 'white', 'brand red'], background_activity: ['executives', 'assistants', 'security'], continuity_reference: 'consistent boardroom and reception areas' },
      { id: 'co_working_space', name: 'Co-Working Space', type: 'urban', category: 'Urban', location: 'shared office', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'flexible', condition: 'clean', materials: ['wood', 'glass', 'fabric'] }, lighting: { natural: 'large windows', artificial: 'task lights, pendant lights' }, color_palette: ['white', 'green', 'wood', 'accent yellow'], background_activity: ['freelancers', 'calls', 'coffee bar'], continuity_reference: 'consistent desk pods and lounge areas' },
      { id: 'rooftop_helipad', name: 'Rooftop Helipad', type: 'urban', category: 'Urban', location: 'skyscraper roof', time: { timeOfDay: 'dusk', season: 'any', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'industrial rooftop', condition: 'maintained', materials: ['concrete', 'steel', 'paint'] }, lighting: { natural: 'city twilight', artificial: 'helipad lights, red beacon' }, color_palette: ['dark gray', 'red', 'city gold', 'twilight blue'], background_activity: ['helicopter', 'crew', 'city hum'], continuity_reference: 'consistent helipad markings and skyline' },
      { id: 'industrial_kitchen', name: 'Industrial Kitchen', type: 'urban', category: 'Urban', location: 'restaurant kitchen', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'hot', intensity: 'moderate', wind: 'none', fog: 'none' }, architecture: { style: 'commercial', condition: 'busy', materials: ['stainless steel', 'tile', 'concrete'] }, lighting: { natural: 'none', artificial: 'heat lamps, oven lights' }, color_palette: ['silver', 'red', 'black', 'white'], background_activity: ['chefs', 'line cooks', 'order tickets'], continuity_reference: 'consistent station layout and stainless surfaces' },
      { id: 'nightclub', name: 'Nightclub', type: 'urban', category: 'Urban', location: 'underground venue', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'industrial chic', condition: 'stylized', materials: ['concrete', 'LED', 'leather'] }, lighting: { natural: 'none', artificial: 'lasers, strobes, neon' }, color_palette: ['neon purple', 'black', 'magenta', 'cyan'], background_activity: ['dancers', 'DJ', 'crowd'], continuity_reference: 'consistent bar and DJ booth placement' },
      { id: 'recording_studio', name: 'Recording Studio', type: 'urban', category: 'Urban', location: 'professional studio', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'acoustic', condition: 'pristine', materials: ['wood', 'foam', 'glass'] }, lighting: { natural: 'none', artificial: 'warm monitor lights' }, color_palette: ['wood brown', 'black', 'violet', 'amber'], background_activity: ['musicians', 'engineer', 'microphone hum'], continuity_reference: 'consistent console and vocal booth setup' },
      { id: 'art_gallery', name: 'Art Gallery', type: 'urban', category: 'Urban', location: 'white cube gallery', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'minimalist', condition: 'pristine', materials: ['white walls', 'concrete', 'glass'] }, lighting: { natural: 'skylights', artificial: 'track lights' }, color_palette: ['white', 'black', 'art colors', 'concrete gray'], background_activity: ['gallery-goers', 'docents', 'silence'], continuity_reference: 'consistent wall spacing and track lighting' },
      { id: 'museum', name: 'Museum', type: 'urban', category: 'Urban', location: 'public museum', time: { timeOfDay: 'day', season: 'any', era: 'any' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'classical or modern', condition: 'maintained', materials: ['stone', 'glass', 'wood'] }, lighting: { natural: 'atrium skylight', artificial: 'spotlights, ambient' }, color_palette: ['stone', 'gold', 'white', 'artifact earth tones'], background_activity: ['visitors', 'security', 'audio guides'], continuity_reference: 'consistent exhibit hall and artifact placement' },
      { id: 'library', name: 'Library', type: 'urban', category: 'Urban', location: 'public library', time: { timeOfDay: 'day', season: 'any', era: 'any' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'classical or modern', condition: 'maintained', materials: ['wood', 'stone', 'glass'] }, lighting: { natural: 'stained glass or skylight', artificial: 'warm lamps' }, color_palette: ['wood brown', 'cream', 'green', 'brass'], background_activity: ['readers', 'pages turning', 'quiet hum'], continuity_reference: 'consistent stacks and reading nooks' },
      { id: 'university_campus', name: 'University Campus', type: 'urban', category: 'Urban', location: 'college quad', time: { timeOfDay: 'day', season: 'fall', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'collegiate gothic', condition: 'maintained', materials: ['stone', 'brick', 'ivy'] }, lighting: { natural: 'golden daylight', artificial: 'lamp posts' }, color_palette: ['brick red', 'ivy green', 'gold', 'slate'], background_activity: ['students', 'bicycles', 'birds'], continuity_reference: 'consistent quad layout and bell tower' },
      { id: 'high_school_hallway', name: 'High School Hallway', type: 'urban', category: 'Urban', location: 'school interior', time: { timeOfDay: 'day', season: 'fall', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'institutional', condition: 'worn', materials: ['lockers', 'tile', 'paint'] }, lighting: { natural: 'high windows', artificial: 'fluorescent' }, color_palette: ['gray', 'locker green', 'poster colors', 'linoleum'], background_activity: ['students', 'locker slams', 'bells'], continuity_reference: 'consistent locker bank and classroom doors' },
      { id: 'hospital_wing', name: 'Hospital Wing', type: 'urban', category: 'Urban', location: 'medical center', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'clinical', condition: 'sterile', materials: ['tile', 'plastic', 'steel'] }, lighting: { natural: 'none', artificial: 'fluorescent, monitor glow' }, color_palette: ['white', 'pale blue', 'green', 'gray'], background_activity: ['nurses', 'monitors beeping', 'wheelchairs'], continuity_reference: 'consistent room numbers and hallway signage' },
      { id: 'courtroom', name: 'Courtroom', type: 'urban', category: 'Urban', location: 'courthouse', time: { timeOfDay: 'day', season: 'any', era: 'any' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'classical', condition: 'formal', materials: ['wood', 'marble', 'brass'] }, lighting: { natural: 'high windows', artificial: 'chandeliers' }, color_palette: ['wood brown', 'marble white', 'gold', 'navy'], background_activity: ['lawyers', 'jury', 'bailiff'], continuity_reference: 'consistent judge bench and jury box' },
      { id: 'police_station', name: 'Police Station', type: 'urban', category: 'Urban', location: 'precinct', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'institutional', condition: 'worn', materials: ['cinder block', 'linoleum', 'steel'] }, lighting: { natural: 'none', artificial: 'fluorescent, desk lamps' }, color_palette: ['gray', 'blue', 'white', 'orange'], background_activity: ['officers', 'dispatch', 'interrogations'], continuity_reference: 'consistent booking desk and holding cells' },
      { id: 'prison_cell', name: 'Prison Cell', type: 'urban', category: 'Urban', location: 'correctional facility', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'concrete cell', condition: 'worn', materials: ['concrete', 'steel', 'cinder block'] }, lighting: { natural: 'small window', artificial: 'bare bulb' }, color_palette: ['gray', 'green', 'orange', 'shadow'], background_activity: ['guards', 'clanging doors', 'distant intercom'], continuity_reference: 'consistent cell bars and concrete walls' },
      { id: 'dmv', name: 'DMV', type: 'urban', category: 'Urban', location: 'government office', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'bureaucratic', condition: 'worn', materials: ['tile', 'plastic', 'steel'] }, lighting: { natural: 'none', artificial: 'fluorescent' }, color_palette: ['gray', 'green', 'white', 'orange'], background_activity: ['waiting people', 'ticket machines', 'announcements'], continuity_reference: 'consistent ticket numbering and seating rows' },
      { id: 'laundromat', name: 'Laundromat', type: 'urban', category: 'Urban', location: 'corner storefront', time: { timeOfDay: 'night', season: 'any', era: 'retro' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'retro storefront', condition: 'worn', materials: ['tile', 'metal', 'glass'] }, lighting: { natural: 'street glow', artificial: 'fluorescent, dryer glow' }, color_palette: ['white', 'teal', 'red', 'gray'], background_activity: ['spinning machines', 'folding people', 'radio'], continuity_reference: 'consistent washer-dryer rows and tile pattern' },
      { id: 'barbershop', name: 'Barbershop', type: 'urban', category: 'Urban', location: 'neighborhood shop', time: { timeOfDay: 'day', season: 'any', era: 'retro' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'classic', condition: 'lived-in', materials: ['wood', 'mirror', 'tile'] }, lighting: { natural: 'window glow', artificial: 'warm overhead, vanity lights' }, color_palette: ['red', 'white', 'wood brown', 'chrome'], background_activity: ['barbers', 'clients', 'scissors', 'radio'], continuity_reference: 'consistent barber chairs and mirror wall' },
      { id: 'tattoo_parlor', name: 'Tattoo Parlor', type: 'urban', category: 'Urban', location: 'street shop', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'industrial', condition: 'stylish', materials: ['concrete', 'leather', 'neon'] }, lighting: { natural: 'none', artificial: 'neon, blacklight, desk lamp' }, color_palette: ['black', 'neon pink', 'leather brown', 'skin'], background_activity: ['artists', 'clients', 'buzzer'], continuity_reference: 'consistent station layout and flash art displays' },
      { id: 'boxing_gym', name: 'Boxing Gym', type: 'urban', category: 'Urban', location: 'basement gym', time: { timeOfDay: 'day', season: 'any', era: 'classic' }, weather: { condition: 'hot', intensity: 'high', wind: 'none', fog: 'none' }, architecture: { style: 'old school', condition: 'worn', materials: ['wood', 'canvas', 'rope'] }, lighting: { natural: 'high windows', artificial: 'bare bulbs' }, color_palette: ['red', 'wood', 'black', 'sweat'], background_activity: ['fighters', 'coaches', 'bag thuds'], continuity_reference: 'consistent ring ropes and speed bag' },
      { id: 'dance_studio', name: 'Dance Studio', type: 'urban', category: 'Urban', location: 'rehearsal space', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'mirror-walled', condition: 'maintained', materials: ['wood', 'mirror', 'barre'] }, lighting: { natural: 'large windows', artificial: 'warm overhead' }, color_palette: ['wood', 'mirror silver', 'leotard colors', 'white'], background_activity: ['dancers', 'music', 'barre exercises'], continuity_reference: 'consistent mirror wall and barre placement' },
      { id: 'climbing_gym', name: 'Climbing Gym', type: 'urban', category: 'Urban', location: 'indoor gym', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'industrial', condition: 'maintained', materials: ['foam', 'wood', 'steel'] }, lighting: { natural: 'skylights', artificial: 'overhead, LED' }, color_palette: ['foam blue', 'wood', 'chalk white', 'gray'], background_activity: ['climbers', 'belayers', 'chalk dust'], continuity_reference: 'consistent wall routes and bouldering layout' },
      { id: 'skate_park', name: 'Skate Park', type: 'urban', category: 'Urban', location: 'outdoor park', time: { timeOfDay: 'day', season: 'summer', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'concrete bowls', condition: 'weathered', materials: ['concrete', 'metal', 'wood'] }, lighting: { natural: 'sunlight', artificial: 'none' }, color_palette: ['concrete gray', 'sky blue', 'graffiti colors', 'wood'], background_activity: ['skateboarders', 'bikes', 'music'], continuity_reference: 'consistent bowl shape and graffiti walls' },
      { id: 'basketball_court', name: 'Basketball Court', type: 'urban', category: 'Urban', location: 'outdoor court', time: { timeOfDay: 'day', season: 'summer', era: 'any' }, weather: { condition: 'clear', intensity: 'light', wind: 'none', fog: 'none' }, architecture: { style: 'outdoor court', condition: 'worn', materials: ['asphalt', 'chain link', 'wood'] }, lighting: { natural: 'sunlight', artificial: 'none' }, color_palette: ['asphalt', 'orange', 'chain link', 'sky'], background_activity: ['players', 'ball bouncing', 'spectators'], continuity_reference: 'consistent court lines and chain-link fence' },
      { id: 'mountain_peak', name: 'Mountain Peak', type: 'nature', category: 'Nature', location: 'summit', time: { timeOfDay: 'dawn', season: 'winter', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'pristine', materials: ['rock', 'snow', 'ice'] }, lighting: { natural: 'alpenglow', artificial: 'none' }, color_palette: ['white', 'blue', 'rock gray', 'gold'], background_activity: ['wind', 'eagles', 'silence'], continuity_reference: 'consistent ridge and summit cairn' },
      { id: 'forest_trail', name: 'Forest Trail', type: 'nature', category: 'Nature', location: 'woodland path', time: { timeOfDay: 'day', season: 'fall', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'light', fog: 'none' }, architecture: { style: 'natural', condition: 'lush', materials: ['dirt', 'roots', 'leaves'] }, lighting: { natural: 'dappled sun', artificial: 'none' }, color_palette: ['green', 'brown', 'gold', 'earth'], background_activity: ['birds', 'squirrels', 'rustling leaves'], continuity_reference: 'consistent trail markers and tree species' },
      { id: 'desert_dunes', name: 'Desert Dunes', type: 'nature', category: 'Nature', location: 'sandy expanse', time: { timeOfDay: 'dusk', season: 'summer', era: 'timeless' }, weather: { condition: 'clear', intensity: 'moderate', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'arid', materials: ['sand', 'rock', 'scrub'] }, lighting: { natural: 'golden hour', artificial: 'none' }, color_palette: ['orange', 'gold', 'brown', 'sky blue'], background_activity: ['wind', 'rolling dunes', 'lizard'], continuity_reference: 'consistent dune crest and shadow direction' },
      { id: 'ocean_beach', name: 'Ocean Beach', type: 'nature', category: 'Nature', location: 'coastal shore', time: { timeOfDay: 'sunset', season: 'summer', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'natural', condition: 'pristine', materials: ['sand', 'water', 'driftwood'] }, lighting: { natural: 'sunset', artificial: 'none' }, color_palette: ['cyan', 'gold', 'sand', 'coral'], background_activity: ['waves', 'seagulls', 'beachgoers'], continuity_reference: 'consistent tide line and dune grass' },
      { id: 'waterfall', name: 'Waterfall', type: 'nature', category: 'Nature', location: 'canyon', time: { timeOfDay: 'day', season: 'spring', era: 'timeless' }, weather: { condition: 'misty', intensity: 'moderate', wind: 'moderate', fog: 'mist' }, architecture: { style: 'natural', condition: 'pristine', materials: ['water', 'rock', 'moss'] }, lighting: { natural: 'rainbow mist', artificial: 'none' }, color_palette: ['white', 'green', 'rock gray', 'cyan'], background_activity: ['rushing water', 'frogs', 'mist'], continuity_reference: 'consistent cascade and pool shape' },
      { id: 'glacier', name: 'Glacier', type: 'nature', category: 'Nature', location: 'polar region', time: { timeOfDay: 'day', season: 'winter', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'pristine', materials: ['ice', 'snow', 'rock'] }, lighting: { natural: 'cold daylight', artificial: 'none' }, color_palette: ['white', 'blue', 'ice gray', 'slate'], background_activity: ['creaking ice', 'wind', 'seals'], continuity_reference: 'consistent ice shelf and crevasses' },
      { id: 'cave_system', name: 'Cave System', type: 'nature', category: 'Nature', location: 'underground', time: { timeOfDay: 'night', season: 'any', era: 'timeless' }, weather: { condition: 'damp', intensity: 'light', wind: 'still', fog: 'none' }, architecture: { style: 'natural', condition: 'pristine', materials: ['rock', 'stalactites', 'water'] }, lighting: { natural: 'none', artificial: 'headlamps, lanterns' }, color_palette: ['black', 'gray', 'amber', 'green'], background_activity: ['drips', 'bats', 'echoes'], continuity_reference: 'consistent passage shape and formations' },
      { id: 'volcano', name: 'Volcano', type: 'nature', category: 'Nature', location: 'crater', time: { timeOfDay: 'dusk', season: 'any', era: 'timeless' }, weather: { condition: 'ash', intensity: 'high', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'active', materials: ['lava', 'ash', 'rock'] }, lighting: { natural: 'lava glow', artificial: 'none' }, color_palette: ['red', 'orange', 'black', 'ash gray'], background_activity: ['rumbling', 'smoke', 'flowing lava'], continuity_reference: 'consistent crater rim and lava path' },
      { id: 'river_rapids', name: 'River Rapids', type: 'nature', category: 'Nature', location: 'whitewater river', time: { timeOfDay: 'day', season: 'spring', era: 'timeless' }, weather: { condition: 'rain', intensity: 'moderate', wind: 'moderate', fog: 'mist' }, architecture: { style: 'natural', condition: 'wild', materials: ['water', 'rock', 'mud'] }, lighting: { natural: 'overcast', artificial: 'none' }, color_palette: ['white', 'green', 'brown', 'gray'], background_activity: ['rushing water', 'splash', 'birds'], continuity_reference: 'consistent rock formations and rapid names' },
      { id: 'lake_cabin', name: 'Lake Cabin', type: 'nature', category: 'Nature', location: 'wooded shore', time: { timeOfDay: 'sunset', season: 'fall', era: 'rustic' }, weather: { condition: 'clear', intensity: 'light', wind: 'calm', fog: 'none' }, architecture: { style: 'rustic cabin', condition: 'cozy', materials: ['wood', 'stone', 'glass'] }, lighting: { natural: 'sunset through trees', artificial: 'fireplace, lanterns' }, color_palette: ['wood brown', 'orange', 'lake blue', 'green'], background_activity: ['crackling fire', 'loons', 'wind in trees'], continuity_reference: 'consistent dock and cabin porch layout' },
      { id: 'meadow', name: 'Meadow', type: 'nature', category: 'Nature', location: 'grassland', time: { timeOfDay: 'day', season: 'spring', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'natural', condition: 'lush', materials: ['grass', 'wildflowers', 'soil'] }, lighting: { natural: 'bright daylight', artificial: 'none' }, color_palette: ['green', 'yellow', 'wildflower colors', 'sky blue'], background_activity: ['bees', 'butterflies', 'grass swaying'], continuity_reference: 'consistent tree line and stream bend' },
      { id: 'canyon', name: 'Canyon', type: 'nature', category: 'Nature', location: 'deep gorge', time: { timeOfDay: 'midday', season: 'fall', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'natural', condition: 'pristine', materials: ['sandstone', 'river', 'scrub'] }, lighting: { natural: 'shadow and light', artificial: 'none' }, color_palette: ['red', 'orange', 'brown', 'river blue'], background_activity: ['wind', 'river', 'hawks'], continuity_reference: 'consistent canyon layers and river bend' },
      { id: 'cliffside', name: 'Cliffside', type: 'nature', category: 'Nature', location: 'edge of plateau', time: { timeOfDay: 'sunset', season: 'any', era: 'timeless' }, weather: { condition: 'clear', intensity: 'moderate', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'pristine', materials: ['rock', 'grass', 'dirt'] }, lighting: { natural: 'golden hour', artificial: 'none' }, color_palette: ['gray', 'green', 'gold', 'sky'], background_activity: ['wind', 'birds', 'distant ocean'], continuity_reference: 'consistent cliff edge and drop-off' },
      { id: 'rainforest', name: 'Rainforest', type: 'nature', category: 'Nature', location: 'tropical forest', time: { timeOfDay: 'day', season: 'rainy', era: 'timeless' }, weather: { condition: 'rain', intensity: 'moderate', wind: 'light', fog: 'mist' }, architecture: { style: 'natural', condition: 'lush', materials: ['canopy', 'mud', 'roots'] }, lighting: { natural: 'green filtered', artificial: 'none' }, color_palette: ['green', 'brown', 'red', 'cyan'], background_activity: ['monkeys', 'rain', 'insects'], continuity_reference: 'consistent canopy gaps and stream crossings' },
      { id: 'savanna', name: 'Savanna', type: 'nature', category: 'Nature', location: 'grassland plain', time: { timeOfDay: 'day', season: 'dry', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'natural', condition: 'golden', materials: ['grass', 'acacia', 'dirt'] }, lighting: { natural: 'harsh sun', artificial: 'none' }, color_palette: ['gold', 'green', 'brown', 'sky blue'], background_activity: ['grazing herds', 'heat shimmer', 'distant storm'], continuity_reference: 'consistent acacia tree and watering hole' },
      { id: 'tundra', name: 'Tundra', type: 'nature', category: 'Nature', location: 'arctic plain', time: { timeOfDay: 'day', season: 'winter', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'frozen', materials: ['snow', 'permafrost', 'rock'] }, lighting: { natural: 'flat daylight', artificial: 'none' }, color_palette: ['white', 'blue', 'gray', 'moss green'], background_activity: ['wind', 'caribou', 'snow crunch'], continuity_reference: 'consistent snow drift and rock outcrop' },
      { id: 'coral_reef', name: 'Coral Reef', type: 'nature', category: 'Nature', location: 'tropical ocean', time: { timeOfDay: 'day', season: 'summer', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'calm', fog: 'none' }, architecture: { style: 'natural', condition: 'vibrant', materials: ['coral', 'sand', 'water'] }, lighting: { natural: 'sunlight through water', artificial: 'none' }, color_palette: ['cyan', 'coral pink', 'blue', 'white'], background_activity: ['fish', 'turtles', 'current'], continuity_reference: 'consistent coral formation and reef crest' },
      { id: 'mangrove_forest', name: 'Mangrove Forest', type: 'nature', category: 'Nature', location: 'coastal wetland', time: { timeOfDay: 'day', season: 'any', era: 'timeless' }, weather: { condition: 'humid', intensity: 'light', wind: 'calm', fog: 'none' }, architecture: { style: 'natural', condition: 'dense', materials: ['mangrove roots', 'water', 'mud'] }, lighting: { natural: 'green filtered', artificial: 'none' }, color_palette: ['green', 'brown', 'water blue', 'mud'], background_activity: ['crabs', 'birds', 'water lapping'], continuity_reference: 'consistent root maze and tidal channels' },
      { id: 'bamboo_grove', name: 'Bamboo Grove', type: 'nature', category: 'Nature', location: 'forest clearing', time: { timeOfDay: 'day', season: 'any', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'natural', condition: 'dense', materials: ['bamboo', 'soil', 'leaves'] }, lighting: { natural: 'dappled', artificial: 'none' }, color_palette: ['green', 'yellow', 'brown', 'shadow'], background_activity: ['rustling leaves', 'wind', 'pandas'], continuity_reference: 'consistent bamboo clumps and stone path' },
      { id: 'rice_terrace', name: 'Rice Terrace', type: 'nature', category: 'Nature', location: 'hillside farm', time: { timeOfDay: 'day', season: 'summer', era: 'traditional' }, weather: { condition: 'clear', intensity: 'light', wind: 'light', fog: 'none' }, architecture: { style: 'agricultural', condition: 'lush', materials: ['water', 'mud', 'stone'] }, lighting: { natural: 'soft daylight', artificial: 'none' }, color_palette: ['green', 'water blue', 'earth brown', 'gold'], background_activity: ['farmers', 'water buffalo', 'birds'], continuity_reference: 'consistent terrace steps and irrigation channels' },
      { id: 'rainy_street', name: 'Rainy Street', type: 'weather', category: 'Weather', location: 'city street', time: { timeOfDay: 'night', season: 'fall', era: 'modern' }, weather: { condition: 'rain', intensity: 'heavy', wind: 'moderate', fog: 'none' }, architecture: { style: 'urban', condition: 'wet', materials: ['asphalt', 'glass', 'neon'] }, lighting: { natural: 'none', artificial: 'neon reflections, headlights' }, color_palette: ['black', 'neon blue', 'red', 'gray'], background_activity: ['umbrellas', 'traffic', 'rain on glass'], continuity_reference: 'consistent puddle reflections and neon signs' },
      { id: 'snow_village', name: 'Snow Village', type: 'weather', category: 'Weather', location: 'alpine hamlet', time: { timeOfDay: 'dusk', season: 'winter', era: 'traditional' }, weather: { condition: 'snow', intensity: 'heavy', wind: 'light', fog: 'none' }, architecture: { style: 'wooden chalets', condition: 'snow-covered', materials: ['wood', 'snow', 'stone'] }, lighting: { natural: 'twilight', artificial: 'warm windows, street lamps' }, color_palette: ['white', 'wood brown', 'warm yellow', 'red'], background_activity: ['snow falling', 'smoke from chimneys', 'footsteps'], continuity_reference: 'consistent roofline and street lamp placement' },
      { id: 'fog_harbor', name: 'Fog Harbor', type: 'weather', category: 'Weather', location: 'port', time: { timeOfDay: 'dawn', season: 'fall', era: 'any' }, weather: { condition: 'fog', intensity: 'dense', wind: 'still', fog: 'dense' }, architecture: { style: 'harbor', condition: 'weathered', materials: ['water', 'wood', 'metal'] }, lighting: { natural: 'diffused dawn', artificial: 'ship lights, foghorn' }, color_palette: ['gray', 'white', 'navy', 'rust'], background_activity: ['foghorn', 'docking ships', 'gulls'], continuity_reference: 'consistent dock pilings and ship silhouettes' },
      { id: 'lightning_storm', name: 'Lightning Storm', type: 'weather', category: 'Weather', location: 'open field', time: { timeOfDay: 'night', season: 'summer', era: 'any' }, weather: { condition: 'storm', intensity: 'extreme', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'chaotic', materials: ['grass', 'dirt', 'water'] }, lighting: { natural: 'lightning flash', artificial: 'none' }, color_palette: ['black', 'white', 'green', 'blue'], background_activity: ['thunder', 'rain', 'trees swaying'], continuity_reference: 'consistent tree line and fence posts' },
      { id: 'dust_storm', name: 'Dust Storm', type: 'weather', category: 'Weather', location: 'desert plain', time: { timeOfDay: 'day', season: 'summer', era: 'any' }, weather: { condition: 'dust', intensity: 'extreme', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'obscured', materials: ['sand', 'dust', 'rock'] }, lighting: { natural: 'diffused orange', artificial: 'none' }, color_palette: ['orange', 'brown', 'amber', 'gray'], background_activity: ['howling wind', 'debris', 'silhouettes'], continuity_reference: 'consistent horizon line and dust density' },
      { id: 'heat_haze', name: 'Heat Haze', type: 'weather', category: 'Weather', location: 'highway', time: { timeOfDay: 'midday', season: 'summer', era: 'modern' }, weather: { condition: 'clear', intensity: 'extreme', wind: 'none', fog: 'none' }, architecture: { style: 'urban', condition: 'shimmering', materials: ['asphalt', 'concrete', 'metal'] }, lighting: { natural: 'harsh sun', artificial: 'none' }, color_palette: ['blue', 'orange', 'gray', 'white'], background_activity: ['shimmering air', 'distant traffic', 'crickets'], continuity_reference: 'consistent road markings and mirage position' },
      { id: 'aurora_night', name: 'Aurora Night', type: 'weather', category: 'Weather', location: 'arctic sky', time: { timeOfDay: 'night', season: 'winter', era: 'timeless' }, weather: { condition: 'clear', intensity: 'light', wind: 'still', fog: 'none' }, architecture: { style: 'natural', condition: 'pristine', materials: ['snow', 'ice', 'sky'] }, lighting: { natural: 'aurora borealis', artificial: 'none' }, color_palette: ['green', 'purple', 'blue', 'white'], background_activity: ['crackling ice', 'stars', 'silence'], continuity_reference: 'consistent aurora curtain shape and snow field' },
      { id: 'hail_storm', name: 'Hail Storm', type: 'weather', category: 'Weather', location: 'open plain', time: { timeOfDay: 'day', season: 'spring', era: 'any' }, weather: { condition: 'hail', intensity: 'heavy', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'chaotic', materials: ['grass', 'dirt', 'ice'] }, lighting: { natural: 'overcast', artificial: 'none' }, color_palette: ['gray', 'white', 'green', 'brown'], background_activity: ['hail impacts', 'thunder', 'running animals'], continuity_reference: 'consistent field boundary and tree line' },
      { id: 'tornado_approach', name: 'Tornado Approach', type: 'weather', category: 'Weather', location: 'great plains', time: { timeOfDay: 'dusk', season: 'spring', era: 'any' }, weather: { condition: 'storm', intensity: 'extreme', wind: 'extreme', fog: 'none' }, architecture: { style: 'rural', condition: 'threatened', materials: ['wood', 'metal', 'dirt'] }, lighting: { natural: 'greenish dusk', artificial: 'none' }, color_palette: ['green', 'gray', 'brown', 'black'], background_activity: ['debris', 'roaring wind', 'sirens'], continuity_reference: 'consistent farmhouse and silo placement' },
      { id: 'monsoon', name: 'Monsoon', type: 'weather', category: 'Weather', location: 'south asian city', time: { timeOfDay: 'afternoon', season: 'summer', era: 'any' }, weather: { condition: 'rain', intensity: 'heavy', wind: 'strong', fog: 'mist' }, architecture: { style: 'dense urban', condition: 'flooded', materials: ['brick', 'concrete', 'metal'] }, lighting: { natural: 'overcast', artificial: 'shop lights, neon' }, color_palette: ['gray', 'neon', 'brown', 'cyan'], background_activity: ['flooded streets', 'umbrellas', 'thunder'], continuity_reference: 'consistent street layout and flood marks' },
      { id: 'smoke_room', name: 'Smoke Room', type: 'atmospheric', category: 'Atmospheric', location: 'interior', time: { timeOfDay: 'night', season: 'any', era: 'any' }, weather: { condition: 'hazy', intensity: 'moderate', wind: 'still', fog: 'none' }, architecture: { style: 'luxury lounge', condition: 'dim', materials: ['leather', 'wood', 'glass'] }, lighting: { natural: 'none', artificial: 'lamps, candles' }, color_palette: ['amber', 'brown', 'black', 'smoke gray'], background_activity: ['cigarette smoke', 'quiet conversation', 'ice clinking'], continuity_reference: 'consistent lamp placement and smoke volume' },
      { id: 'fire_interior', name: 'Fire Interior', type: 'atmospheric', category: 'Atmospheric', location: 'burning room', time: { timeOfDay: 'night', season: 'any', era: 'any' }, weather: { condition: 'fire', intensity: 'high', wind: 'moderate', fog: 'smoke' }, architecture: { style: 'domestic', condition: 'damaged', materials: ['wood', 'fabric', 'glass'] }, lighting: { natural: 'none', artificial: 'fire glow, embers' }, color_palette: ['orange', 'red', 'black', 'amber'], background_activity: ['crackling fire', 'smoke', 'heat waves'], continuity_reference: 'consistent fire spread and structural damage' },
      { id: 'mist_forest', name: 'Mist Forest', type: 'atmospheric', category: 'Atmospheric', location: 'woodland', time: { timeOfDay: 'dawn', season: 'fall', era: 'timeless' }, weather: { condition: 'fog', intensity: 'dense', wind: 'still', fog: 'dense' }, architecture: { style: 'natural', condition: 'mysterious', materials: ['trees', 'moss', 'mist'] }, lighting: { natural: 'diffused dawn', artificial: 'none' }, color_palette: ['green', 'gray', 'white', 'blue'], background_activity: ['dripping mist', 'bird calls', 'silence'], continuity_reference: 'consistent fog bank and tree spacing' },
      { id: 'cloud_sky', name: 'Cloud Sky', type: 'atmospheric', category: 'Atmospheric', location: 'above clouds', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'clear above', intensity: 'light', wind: 'strong', fog: 'none' }, architecture: { style: 'natural', condition: 'ephemeral', materials: ['cloud', 'sky', 'air'] }, lighting: { natural: 'bright sun', artificial: 'none' }, color_palette: ['white', 'blue', 'gold', 'cyan'], background_activity: ['wind', 'sun glare', 'birds'], continuity_reference: 'consistent cloud formations and horizon' },
      { id: 'sun_rays', name: 'Sun Rays', type: 'atmospheric', category: 'Atmospheric', location: 'interior or forest', time: { timeOfDay: 'golden hour', season: 'any', era: 'any' }, weather: { condition: 'clear', intensity: 'light', wind: 'still', fog: 'dusty' }, architecture: { style: 'varied', condition: 'stylized', materials: ['air', 'dust', 'glass'] }, lighting: { natural: 'crepuscular rays', artificial: 'none' }, color_palette: ['gold', 'white', 'amber', 'shadow'], background_activity: ['dust motes', 'floating particles', 'stillness'], continuity_reference: 'consistent ray angle and particle density' },
      { id: 'floating_particles', name: 'Floating Particles', type: 'atmospheric', category: 'Atmospheric', location: 'interior', time: { timeOfDay: 'day', season: 'any', era: 'any' }, weather: { condition: 'clear', intensity: 'light', wind: 'gentle', fog: 'none' }, architecture: { style: 'minimal', condition: 'clean', materials: ['air', 'glass', 'dust'] }, lighting: { natural: 'window light', artificial: 'spotlight' }, color_palette: ['white', 'gold', 'amber', 'blue'], background_activity: ['floating dust', 'light beam', 'silence'], continuity_reference: 'consistent particle motion and light cone' },
      { id: 'ember_field', name: 'Ember Field', type: 'atmospheric', category: 'Atmospheric', location: 'burning field', time: { timeOfDay: 'night', season: 'any', era: 'any' }, weather: { condition: 'fire', intensity: 'high', wind: 'moderate', fog: 'smoke' }, architecture: { style: 'natural', condition: 'burning', materials: ['grass', 'ash', 'fire'] }, lighting: { natural: 'fire glow', artificial: 'none' }, color_palette: ['orange', 'red', 'black', 'amber'], background_activity: ['crackling', 'rising embers', 'heat waves'], continuity_reference: 'consistent ember trajectory and fire front' },
      { id: 'rain_droplets_windowsill', name: 'Rain Droplets Windowsill', type: 'atmospheric', category: 'Atmospheric', location: 'interior', time: { timeOfDay: 'night', season: 'any', era: 'any' }, weather: { condition: 'rain', intensity: 'moderate', wind: 'still', fog: 'none' }, architecture: { style: 'domestic', condition: 'cozy', materials: ['glass', 'wood', 'fabric'] }, lighting: { natural: 'none', artificial: 'lamp, city lights' }, color_palette: ['blue', 'amber', 'gray', 'white'], background_activity: ['dripping water', 'city hum', 'silence'], continuity_reference: 'consistent droplet pattern and window frame' },
      { id: 'neon_reflection_glass', name: 'Neon Reflection Glass', type: 'atmospheric', category: 'Atmospheric', location: 'city window', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'clear', intensity: 'none', wind: 'still', fog: 'none' }, architecture: { style: 'modern', condition: 'stylized', materials: ['glass', 'neon', 'metal'] }, lighting: { natural: 'none', artificial: 'neon reflections' }, color_palette: ['neon pink', 'cyan', 'blue', 'black'], background_activity: ['city lights', 'passing cars', 'reflections'], continuity_reference: 'consistent neon sign positions and reflections' },
      { id: 'dust_sunbeam', name: 'Dust Sunbeam', type: 'atmospheric', category: 'Atmospheric', location: 'abandoned room', time: { timeOfDay: 'day', season: 'any', era: 'any' }, weather: { condition: 'clear', intensity: 'light', wind: 'still', fog: 'dusty' }, architecture: { style: 'abandoned', condition: 'weathered', materials: ['wood', 'dust', 'glass'] }, lighting: { natural: 'single window beam', artificial: 'none' }, color_palette: ['amber', 'brown', 'white', 'shadow'], background_activity: ['floating dust', 'creaking floor', 'silence'], continuity_reference: 'consistent beam angle and dust volume' },
      { id: 'modern_kitchen', name: 'Modern Kitchen', type: 'residential', category: 'Residential', location: 'home', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'modern', condition: 'clean', materials: ['quartz', 'steel', 'glass'] }, lighting: { natural: 'large window', artificial: 'pendant lights, under-cabinet' }, color_palette: ['white', 'gray', 'wood', 'stainless'], background_activity: ['coffee brewing', 'refrigerator hum', 'quiet'], continuity_reference: 'consistent cabinet layout and appliance placement' },
      { id: 'cozy_living_room', name: 'Cozy Living Room', type: 'residential', category: 'Residential', location: 'home', time: { timeOfDay: 'night', season: 'fall', era: 'any' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'residential', condition: 'lived-in', materials: ['fabric', 'wood', 'brick'] }, lighting: { natural: 'fireplace glow', artificial: 'floor lamps, string lights' }, color_palette: ['brown', 'cream', 'orange', 'navy'], background_activity: ['crackling fire', 'TV hum', 'quiet conversation'], continuity_reference: 'consistent sofa placement and fireplace backdrop' },
      { id: 'luxury_bedroom', name: 'Luxury Bedroom', type: 'residential', category: 'Residential', location: 'penthouse', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'luxury', condition: 'pristine', materials: ['silk', 'marble', 'gold', 'glass'] }, lighting: { natural: 'city lights', artificial: 'chandelier, sconces' }, color_palette: ['gold', 'cream', 'navy', 'marble white'], background_activity: ['city hum', 'quiet', 'fabric rustle'], continuity_reference: 'consistent bed frame and window view' },
      { id: 'small_apartment', name: 'Small Apartment', type: 'residential', category: 'Residential', location: 'city studio', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'compact', condition: 'lived-in', materials: ['wood', 'paint', 'fabric'] }, lighting: { natural: 'single window', artificial: 'desk lamp, string lights' }, color_palette: ['white', 'teal', 'wood', 'poster colors'], background_activity: ['roommate chatter', 'coffee', 'city noise'], continuity_reference: 'consistent desk and bed layout' },
      { id: 'family_kitchen', name: 'Family Kitchen', type: 'residential', category: 'Residential', location: 'suburban home', time: { timeOfDay: 'morning', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'homey', condition: 'lived-in', materials: ['wood', 'tile', 'granite'] }, lighting: { natural: 'window light', artificial: 'overhead, coffee machine' }, color_palette: ['white', 'yellow', 'wood', 'granite'], background_activity: ['sizzling pans', 'family chatter', 'pets'], continuity_reference: 'consistent fridge magnets and breakfast nook' },
      { id: 'garage_workshop', name: 'Garage Workshop', type: 'residential', category: 'Residential', location: 'home garage', time: { timeOfDay: 'day', season: 'any', era: 'any' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'industrial home', condition: 'cluttered', materials: ['concrete', 'wood', 'tools'] }, lighting: { natural: 'garage door light', artificial: 'shop lights' }, color_palette: ['gray', 'oil', 'wood', 'neon accent'], background_activity: ['sawing', 'drilling', 'radio'], continuity_reference: 'consistent tool board and workbench layout' },
      { id: 'attic', name: 'Attic', type: 'residential', category: 'Residential', location: 'top floor', time: { timeOfDay: 'day', season: 'summer', era: 'any' }, weather: { condition: 'hot', intensity: 'moderate', wind: 'none', fog: 'none' }, architecture: { style: 'sloped ceilings', condition: 'dusty', materials: ['wood', 'dust', 'cardboard'] }, lighting: { natural: 'dormer window', artificial: 'bare bulb' }, color_palette: ['beige', 'wood', 'dust', 'shadow'], background_activity: ['creaking floor', 'draft', 'old fan'], continuity_reference: 'consistent trunk placement and slanted beams' },
      { id: 'basement', name: 'Basement', type: 'residential', category: 'Residential', location: 'lower level', time: { timeOfDay: 'night', season: 'any', era: 'any' }, weather: { condition: 'damp', intensity: 'light', wind: 'none', fog: 'none' }, architecture: { style: 'concrete', condition: 'unfinished', materials: ['concrete', 'wood', 'pipes'] }, lighting: { natural: 'small window', artificial: 'single bulb' }, color_palette: ['gray', 'green', 'brown', 'black'], background_activity: ['dripping water', 'furnace hum', 'silence'], continuity_reference: 'consistent water heater and stairs placement' },
      { id: 'balcony_view', name: 'Balcony View', type: 'residential', category: 'Residential', location: 'apartment balcony', time: { timeOfDay: 'sunset', season: 'summer', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'urban terrace', condition: 'stylish', materials: ['concrete', 'glass', 'plants'] }, lighting: { natural: 'golden hour', artificial: 'none' }, color_palette: ['gold', 'cyan', 'green', 'white'], background_activity: ['city hum', 'birds', 'wind chimes'], continuity_reference: 'consistent railing and skyline framing' },
      { id: 'home_office', name: 'Home Office', type: 'residential', category: 'Residential', location: 'spare room', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'professional', condition: 'organized', materials: ['wood', 'glass', 'fabric'] }, lighting: { natural: 'window light', artificial: 'desk lamp, LED strip' }, color_palette: ['white', 'wood', 'blue', 'gray'], background_activity: ['keyboard clicks', 'coffee', 'quiet'], continuity_reference: 'consistent desk setup and bookshelf arrangement' },
      { id: 'nursery', name: 'Nursery', type: 'residential', category: 'Residential', location: 'home', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'soft', condition: 'pristine', materials: ['fabric', 'wood', 'plastic'] }, lighting: { natural: 'nightlight', artificial: 'dim lamp' }, color_palette: ['pastel blue', 'white', 'yellow', 'soft green'], background_activity: ['mobile music', 'humidifier', 'quiet'], continuity_reference: 'consistent crib placement and mobile' },
      { id: 'bathroom_spa', name: 'Bathroom Spa', type: 'residential', category: 'Residential', location: 'master bath', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'humid', intensity: 'light', wind: 'none', fog: 'steam' }, architecture: { style: 'luxury', condition: 'pristine', materials: ['marble', 'glass', 'brass'] }, lighting: { natural: 'none', artificial: 'vanity lights, candles' }, color_palette: ['white', 'marble', 'brass', 'green'], background_activity: ['dripping water', 'steam', 'quiet'], continuity_reference: 'consistent tub position and vanity mirror' },
      { id: 'dining_room', name: 'Dining Room', type: 'residential', category: 'Residential', location: 'home', time: { timeOfDay: 'evening', season: 'any', era: 'any' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'formal or casual', condition: 'set', materials: ['wood', 'fabric', 'glass'] }, lighting: { natural: 'candlelight', artificial: 'chandelier, sconces' }, color_palette: ['wood brown', 'cream', 'gold', 'linen'], background_activity: ['clinking glasses', 'conversation', 'quiet music'], continuity_reference: 'consistent table setting and chandelier' },
      { id: 'porch_sunset', name: 'Porch Sunset', type: 'residential', category: 'Residential', location: 'front porch', time: { timeOfDay: 'sunset', season: 'summer', era: 'rustic' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'porch', condition: 'lived-in', materials: ['wood', 'fabric', 'plants'] }, lighting: { natural: 'golden hour', artificial: 'none' }, color_palette: ['gold', 'wood brown', 'green', 'white'], background_activity: ['crickets', 'swing creaking', 'birds'], continuity_reference: 'consistent porch swing and column spacing' },
      { id: 'hallway_mirror', name: 'Hallway Mirror', type: 'residential', category: 'Residential', location: 'apartment hallway', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'narrow corridor', condition: 'clean', materials: ['drywall', 'wood', 'glass'] }, lighting: { natural: 'none', artificial: 'sconces, overhead' }, color_palette: ['white', 'wood', 'silver', 'black'], background_activity: ['footsteps', 'door clicks', 'silence'], continuity_reference: 'consistent mirror placement and door frames' },
      { id: 'car_interior', name: 'Car Interior', type: 'transportation', category: 'Transportation', location: 'sedan or SUV', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'rain', intensity: 'moderate', wind: 'none', fog: 'none' }, architecture: { style: 'modern interior', condition: 'clean', materials: ['leather', 'plastic', 'glass'] }, lighting: { natural: 'street glow', artificial: 'dashboard lights' }, color_palette: ['black', 'dashboard blue', 'red', 'white'], background_activity: ['rain on glass', 'engine hum', 'wipers'], continuity_reference: 'consistent dashboard layout and window framing' },
      { id: 'train_window', name: 'Train Window', type: 'transportation', category: 'Transportation', location: 'passenger train', time: { timeOfDay: 'day', season: 'fall', era: 'modern' }, weather: { condition: 'rain', intensity: 'light', wind: 'none', fog: 'none' }, architecture: { style: 'modern coach', condition: 'worn', materials: ['plastic', 'glass', 'fabric'] }, lighting: { natural: 'diffused daylight', artificial: 'overhead' }, color_palette: ['gray', 'green', 'blur', 'gold'], background_activity: ['rhythmic clacking', 'announcements', 'passengers'], continuity_reference: 'consistent window frame and passing landscape' },
      { id: 'airplane_cabin', name: 'Airplane Cabin', type: 'transportation', category: 'Transportation', location: 'commercial jet', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'narrow-body', condition: 'clean', materials: ['plastic', 'fabric', 'aluminum'] }, lighting: { natural: 'none', artificial: 'dim cabin lights, screen glow' }, color_palette: ['navy', 'gray', 'blue', 'white'], background_activity: ['engine hum', 'passengers', 'soft announcements'], continuity_reference: 'consistent seat layout and window rows' },
      { id: 'bus_stop', name: 'Bus Stop', type: 'transportation', category: 'Transportation', location: 'street corner', time: { timeOfDay: 'night', season: 'fall', era: 'any' }, weather: { condition: 'rain', intensity: 'moderate', wind: 'light', fog: 'none' }, architecture: { style: 'simple shelter', condition: 'worn', materials: ['metal', 'glass', 'concrete'] }, lighting: { natural: 'street lamps', artificial: 'bus stop ad lights' }, color_palette: ['yellow', 'gray', 'neon', 'wet black'], background_activity: ['waiting people', 'passing headlights', 'rain'], continuity_reference: 'consistent shelter panel and timetable' },
      { id: 'motorcycle_road', name: 'Motorcycle Road', type: 'transportation', category: 'Transportation', location: 'highway', time: { timeOfDay: 'day', season: 'summer', era: 'any' }, weather: { condition: 'clear', intensity: 'light', wind: 'strong', fog: 'none' }, architecture: { style: 'open road', condition: 'paved', materials: ['asphalt', 'guardrail', 'dust'] }, lighting: { natural: 'bright sun', artificial: 'none' }, color_palette: ['blue', 'green', 'asphalt', 'chrome'], background_activity: ['wind', 'passing cars', 'birds'], continuity_reference: 'consistent road markings and shoulder' },
      { id: 'yacht_deck', name: 'Yacht Deck', type: 'transportation', category: 'Transportation', location: 'luxury vessel', time: { timeOfDay: 'sunset', season: 'summer', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'luxury yacht', condition: 'pristine', materials: ['teak', 'glass', 'stainless'] }, lighting: { natural: 'golden sunset', artificial: 'deck lights, candles' }, color_palette: ['navy', 'gold', 'teak', 'white'], background_activity: ['waves', 'seagulls', 'crew'], continuity_reference: 'consistent railing and horizon framing' },
      { id: 'helicopter_view', name: 'Helicopter View', type: 'transportation', category: 'Transportation', location: 'aerial', time: { timeOfDay: 'day', season: 'any', era: 'modern' }, weather: { condition: 'clear', intensity: 'light', wind: 'strong', fog: 'none' }, architecture: { style: 'aerial', condition: 'clear', materials: ['air', 'city', 'clouds'] }, lighting: { natural: 'bright daylight', artificial: 'none' }, color_palette: ['blue', 'green', 'gray', 'white'], background_activity: ['rotor whir', 'city below', 'wind'], continuity_reference: 'consistent city grid and landmark positions' },
      { id: 'subway_tunnel', name: 'Subway Tunnel', type: 'transportation', category: 'Transportation', location: 'underground', time: { timeOfDay: 'night', season: 'any', era: 'modern' }, weather: { condition: 'dry', intensity: 'none', wind: 'strong', fog: 'none' }, architecture: { style: 'industrial tunnel', condition: 'worn', materials: ['concrete', 'steel', 'tile'] }, lighting: { natural: 'none', artificial: 'tunnel lights, train headlights' }, color_palette: ['black', 'orange', 'gray', 'white'], background_activity: ['approaching train', 'wind', 'drips'], continuity_reference: 'consistent tunnel curvature and lighting gaps' },
      { id: 'taxi_rain', name: 'Taxi Rain', type: 'transportation', category: 'Transportation', location: 'city streets', time: { timeOfDay: 'night', season: 'fall', era: 'modern' }, weather: { condition: 'rain', intensity: 'heavy', wind: 'moderate', fog: 'none' }, architecture: { style: 'urban', condition: 'wet', materials: ['glass', 'asphalt', 'neon'] }, lighting: { natural: 'none', artificial: 'headlights, neon reflections' }, color_palette: ['black', 'neon yellow', 'red', 'gray'], background_activity: ['wipers', 'traffic', 'city hum'], continuity_reference: 'consistent taxi meter and window raindrops' },
      { id: 'rv_interior', name: 'RV Interior', type: 'transportation', category: 'Transportation', location: 'recreational vehicle', time: { timeOfDay: 'night', season: 'any', era: 'any' }, weather: { condition: 'wind', intensity: 'moderate', wind: 'moderate', fog: 'none' }, architecture: { style: 'compact', condition: 'lived-in', materials: ['wood', 'fabric', 'plastic'] }, lighting: { natural: 'none', artificial: 'warm overhead, lanterns' }, color_palette: ['wood brown', 'cream', 'orange', 'navy'], background_activity: ['road hum', 'clock ticking', 'quiet'], continuity_reference: 'consistent bed layout and window view' },
      { id: 'ai_server_room', name: 'AI Server Room', type: 'futuristic', category: 'Futuristic', location: 'data center', time: { timeOfDay: 'night', season: 'any', era: 'future' }, weather: { condition: 'cool', intensity: 'low', wind: 'still', fog: 'none' }, architecture: { style: 'industrial', condition: 'pristine', materials: ['steel', 'glass', 'LED'] }, lighting: { natural: 'none', artificial: 'LED racks, status lights' }, color_palette: ['blue', 'white', 'black', 'neon cyan'], background_activity: ['server hum', 'blinking lights', 'cooling'], continuity_reference: 'consistent rack layout and LED patterns' },
      { id: 'holographic_office', name: 'Holographic Office', type: 'futuristic', category: 'Futuristic', location: 'virtual workspace', time: { timeOfDay: 'day', season: 'any', era: 'future' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'virtual', condition: 'clean', materials: ['light', 'hologram', 'air'] }, lighting: { natural: 'holographic glow', artificial: 'none' }, color_palette: ['cyan', 'white', 'blue', 'purple'], background_activity: ['floating data', 'soft hum', 'silence'], continuity_reference: 'consistent hologram interface and floor grid' },
      { id: 'drone_sky', name: 'Drone Sky', type: 'futuristic', category: 'Futuristic', location: 'aerial', time: { timeOfDay: 'day', season: 'any', era: 'future' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'aerial', condition: 'clear', materials: ['air', 'city', 'drones'] }, lighting: { natural: 'bright daylight', artificial: 'none' }, color_palette: ['blue', 'white', 'gray', 'green'], background_activity: ['drone whir', 'city hum', 'wind'], continuity_reference: 'consistent drone swarm formation and city layout' },
      { id: 'quantum_lab', name: 'Quantum Lab', type: 'futuristic', category: 'Futuristic', location: 'research facility', time: { timeOfDay: 'night', season: 'any', era: 'future' }, weather: { condition: 'cool', intensity: 'low', wind: 'still', fog: 'none' }, architecture: { style: 'clean', condition: 'pristine', materials: ['steel', 'glass', 'ceramic'] }, lighting: { natural: 'none', artificial: 'laser glow, status lights' }, color_palette: ['blue', 'white', 'silver', 'neon cyan'], background_activity: ['cooling hum', 'laser pulses', 'quiet'], continuity_reference: 'consistent equipment layout and laser path' },
      { id: 'vr_world', name: 'VR World', type: 'futuristic', category: 'Futuristic', location: 'virtual', time: { timeOfDay: 'any', season: 'any', era: 'future' }, weather: { condition: 'any', intensity: 'any', wind: 'any', fog: 'any' }, architecture: { style: 'virtual', condition: 'rendered', materials: ['light', 'pixels', 'data'] }, lighting: { natural: 'dynamic', artificial: 'none' }, color_palette: ['neon', 'white', 'cyan', 'magenta'], background_activity: ['glitch effects', 'data streams', 'avatar movement'], continuity_reference: 'consistent world rules and avatar state' },
      { id: 'cyberpunk_street', name: 'Cyberpunk Street', type: 'futuristic', category: 'Futuristic', location: 'neon city', time: { timeOfDay: 'night', season: 'rainy', era: 'future' }, weather: { condition: 'rain', intensity: 'heavy', wind: 'moderate', fog: 'mist' }, architecture: { style: 'dense neon', condition: 'worn-futuristic', materials: ['neon', 'metal', 'glass'] }, lighting: { natural: 'none', artificial: 'neon, holograms, drones' }, color_palette: ['neon pink', 'cyan', 'purple', 'black'], background_activity: ['holograms', 'traffic', 'crowds'], continuity_reference: 'consistent neon sign positions and rain reflections' },
      { id: 'space_station_interior', name: 'Space Station Interior', type: 'futuristic', category: 'Futuristic', location: 'orbital station', time: { timeOfDay: 'any', season: 'any', era: 'future' }, weather: { condition: 'weightless', intensity: 'none', wind: 'still', fog: 'none' }, architecture: { style: 'modular', condition: 'lived-in', materials: ['aluminum', 'fabric', 'glass'] }, lighting: { natural: 'earth glow', artificial: 'LED panels' }, color_palette: ['white', 'gray', 'blue', 'orange'], background_activity: ['alarms', 'crew chatter', 'air recycler hum'], continuity_reference: 'consistent module layout and window earth view' },
      { id: 'mars_colony', name: 'Mars Colony', type: 'futuristic', category: 'Futuristic', location: 'martian surface', time: { timeOfDay: 'day', season: 'any', era: 'future' }, weather: { condition: 'dusty', intensity: 'moderate', wind: 'strong', fog: 'none' }, architecture: { style: 'habitat dome', condition: 'sealed', materials: ['regolith', 'plastic', 'steel'] }, lighting: { natural: 'dim red daylight', artificial: 'interior lights' }, color_palette: ['red', 'orange', 'white', 'gray'], background_activity: ['airlock cycles', 'radio chatter', 'wind'], continuity_reference: 'consistent dome structure and rover path' },
      { id: 'floating_city', name: 'Floating City', type: 'futuristic', category: 'Futuristic', location: 'sky archipelago', time: { timeOfDay: 'day', season: 'any', era: 'future' }, weather: { condition: 'clear', intensity: 'light', wind: 'breezy', fog: 'none' }, architecture: { style: 'suspended', condition: 'stylized', materials: ['glass', 'steel', 'crystal'] }, lighting: { natural: 'sunlight through clouds', artificial: 'city glow' }, color_palette: ['white', 'cyan', 'gold', 'sky blue'], background_activity: ['airships', 'wind', 'birds'], continuity_reference: 'consistent platform layout and bridge connections' },
      { id: 'neural_interface_chamber', name: 'Neural Interface Chamber', type: 'futuristic', category: 'Futuristic', location: 'medical facility', time: { timeOfDay: 'night', season: 'any', era: 'future' }, weather: { condition: 'cool', intensity: 'low', wind: 'still', fog: 'none' }, architecture: { style: 'clinical', condition: 'high-tech', materials: ['glass', 'LED', 'plastic'] }, lighting: { natural: 'none', artificial: 'neural interface glow' }, color_palette: ['blue', 'white', 'neon cyan', 'black'], background_activity: ['neural hum', 'monitor beeps', 'quiet'], continuity_reference: 'consistent chair position and interface cables' },
      { id: 'medieval_castle', name: 'Medieval Castle', type: 'historical', category: 'Historical', location: 'hilltop fortress', time: { timeOfDay: 'dusk', season: 'fall', era: 'medieval' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'stone fortress', condition: 'weathered', materials: ['stone', 'wood', 'iron'] }, lighting: { natural: 'torchlight dusk', artificial: 'torches, braziers' }, color_palette: ['gray', 'brown', 'orange', 'green'], background_activity: ['guards', 'horses', 'fire'], continuity_reference: 'consistent gatehouse and tower positions' },
      { id: 'victorian_street', name: 'Victorian Street', type: 'historical', category: 'Historical', location: 'gas-lit lane', time: { timeOfDay: 'dusk', season: 'fall', era: 'victorian' }, weather: { condition: 'fog', intensity: 'light', wind: 'light', fog: 'light' }, architecture: { style: 'row houses', condition: 'weathered', materials: ['brick', 'gas lamp', 'cobble'] }, lighting: { natural: 'dim dusk', artificial: 'gas lamps' }, color_palette: ['sepia', 'brown', 'amber', 'gray'], background_activity: ['horse carts', 'vendors', 'gentlemen'], continuity_reference: 'consistent gas lamp spacing and shopfronts' },
      { id: 'wild_west_town', name: 'Wild West Town', type: 'historical', category: 'Historical', location: 'frontier main street', time: { timeOfDay: 'midday', season: 'summer', era: '1800s' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'wooden false-front', condition: 'weathered', materials: ['wood', 'dust', 'tin'] }, lighting: { natural: 'harsh sun', artificial: 'none' }, color_palette: ['brown', 'tan', 'dust', 'red'], background_activity: ['horses', 'cowboys', 'saloon piano'], continuity_reference: 'consistent false-front facades and hitching posts' },
      { id: '1920s_speakeasy', name: '1920s Speakeasy', type: 'historical', category: 'Historical', location: 'hidden bar', time: { timeOfDay: 'night', season: 'winter', era: '1920s' }, weather: { condition: 'indoor', intensity: 'none', wind: 'none', fog: 'none' }, architecture: { style: 'art deco', condition: 'dim', materials: ['wood', 'mirror', 'brass'] }, lighting: { natural: 'none', artificial: 'candlelight, amber lamps' }, color_palette: ['gold', 'black', 'amber', 'red'], background_activity: ['jazz band', 'glasses clinking', 'secret knock'], continuity_reference: 'consistent bar layout and hidden door' },
      { id: 'ancient_temple', name: 'Ancient Temple', type: 'historical', category: 'Historical', location: 'jungle ruins', time: { timeOfDay: 'day', season: 'any', era: 'ancient' }, weather: { condition: 'clear', intensity: 'light', wind: 'light', fog: 'none' }, architecture: { style: 'stone temple', condition: 'ruined', materials: ['stone', 'ivy', 'gold'] }, lighting: { natural: 'sunbeams through cracks', artificial: 'none' }, color_palette: ['stone gray', 'green', 'gold', 'brown'], background_activity: ['monkeys', 'wind', 'echoes'], continuity_reference: 'consistent column alignment and altar placement' },
      { id: 'roman_forum', name: 'Roman Forum', type: 'historical', category: 'Historical', location: 'ancient city center', time: { timeOfDay: 'day', season: 'summer', era: 'roman' }, weather: { condition: 'clear', intensity: 'light', wind: 'light', fog: 'none' }, architecture: { style: 'classical ruins', condition: 'excavated', materials: ['marble', 'stone', 'earth'] }, lighting: { natural: 'bright sun', artificial: 'none' }, color_palette: ['white', 'tan', 'green', 'blue'], background_activity: ['tourists', 'birds', 'wind'], continuity_reference: 'consistent column rows and arch placement' },
      { id: 'pirate_ship', name: 'Pirate Ship', type: 'historical', category: 'Historical', location: 'high seas', time: { timeOfDay: 'sunset', season: 'any', era: '1700s' }, weather: { condition: 'clear', intensity: 'moderate', wind: 'strong', fog: 'none' }, architecture: { style: 'wooden galleon', condition: 'weathered', materials: ['wood', 'canvas', 'rope'] }, lighting: { natural: 'golden sunset', artificial: 'lanterns' }, color_palette: ['brown', 'navy', 'gold', 'white'], background_activity: ['waves', 'gulls', 'rigging creaks'], continuity_reference: 'consistent mast placement and deck layout' },
      { id: 'world_war_trench', name: 'World War Trench', type: 'historical', category: 'Historical', location: 'battlefield', time: { timeOfDay: 'dawn', season: 'winter', era: '1910s' }, weather: { condition: 'rain', intensity: 'moderate', wind: 'light', fog: 'mist' }, architecture: { style: 'muddy trench', condition: 'destroyed', materials: ['mud', 'wood', 'sandbag'] }, lighting: { natural: 'gray dawn', artificial: 'none' }, color_palette: ['brown', 'gray', 'green', 'black'], background_activity: ['distant artillery', 'rain', 'rats'], continuity_reference: 'consistent trench zigzag and sandbag walls' },
      { id: 'civil_rights_march', name: 'Civil Rights March', type: 'historical', category: 'Historical', location: 'city street', time: { timeOfDay: 'day', season: 'spring', era: '1960s' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'urban', condition: 'busy', materials: ['asphalt', 'buildings', 'banners'] }, lighting: { natural: 'bright sun', artificial: 'none' }, color_palette: ['sepia', 'sign red', 'blue', 'gray'], background_activity: ['marchers', 'singing', 'police'], continuity_reference: 'consistent street perspective and banner colors' },
      { id: 'gold_rush_town', name: 'Gold Rush Town', type: 'historical', category: 'Historical', location: 'frontier settlement', time: { timeOfDay: 'dusk', season: 'fall', era: '1800s' }, weather: { condition: 'clear', intensity: 'light', wind: 'moderate', fog: 'none' }, architecture: { style: 'wooden frontier', condition: 'weathered', materials: ['wood', 'dust', 'canvas'] }, lighting: { natural: 'golden dusk', artificial: 'oil lamps' }, color_palette: ['brown', 'gold', 'tan', 'red'], background_activity: ['miners', 'horses', 'saloon music'], continuity_reference: 'consistent main street and boardwalk layout' }
    ];

    for (const env of environments) {
      this.register(env);
    }
  }

  register(env) {
    if (!env || !env.id) {
      throw new Error('Environment must have a valid id');
    }
    this._registry.set(env.id, env);
    if (!this._categoryIndex.has(env.category)) {
      this._categoryIndex.set(env.category, []);
    }
    this._categoryIndex.get(env.category).push(env.id);
    if (!this._typeIndex.has(env.type)) {
      this._typeIndex.set(env.type, []);
    }
    this._typeIndex.get(env.type).push(env.id);
  }

  get(id) {
    return this._registry.get(id) || null;
  }

  getAll() {
    return Array.from(this._registry.values());
  }

  getByType(type) {
    const typeLower = String(type).toLowerCase();
    return this.getAll().filter((item) => String(item.type).toLowerCase() === typeLower);
  }

  getByCategory(category) {
    const categoryLower = String(category).toLowerCase();
    const ids = this._categoryIndex.get(categoryLower) || [];
    return ids.map((id) => this._registry.get(id)).filter(Boolean);
  }

  search(query) {
    const q = String(query).toLowerCase();
    return this.getAll().filter((item) => {
      const haystack = `${item.id} ${item.name} ${item.type} ${item.category} ${item.location} ${(item.color_palette || []).join(' ')} ${(item.background_activity || []).join(' ')}`.toLowerCase();
      return haystack.includes(q);
    });
  }
}

export const environmentRegistry = new EnvironmentRegistry();
