export const NICHES = {
  'Barber Shop': [['shop', 'hairdresser']], 'Hair Salon': [['shop', 'hairdresser']],
  'Beauty Salon': [['shop', 'beauty']], 'Nail Salon': [['shop', 'nails'], ['shop', 'beauty']],
  'Spa': [['leisure', 'spa'], ['shop', 'spa']], 'Massage Center': [['shop', 'massage']],
  'Tattoo Studio': [['shop', 'tattoo']], 'Makeup Artist': [['shop', 'beauty'], ['craft', 'beautician']],
  'Lash & Brow Studio': [['shop', 'beauty']], 'Bridal Makeup': [['shop', 'beauty']],
  'Gym / Fitness': [['leisure', 'fitness_centre']], 'Yoga Studio': [['leisure', 'fitness_centre'], ['sport', 'yoga']],
  'Personal Trainer': [['leisure', 'fitness_centre']], 'Martial Arts': [['sport', 'martial_arts'], ['sport', 'karate']],
  'Cricket Academy': [['sport', 'cricket']], 'Football Academy': [['sport', 'soccer'], ['sport', 'football']],
  'Swim School': [['leisure', 'swimming_pool'], ['sport', 'swimming']],
  'Badminton / Court Booking': [['sport', 'badminton'], ['leisure', 'sports_centre']],
  'Dentist': [['amenity', 'dentist'], ['healthcare', 'dentist']],
  'Doctor / GP': [['amenity', 'doctors'], ['healthcare', 'doctor']],
  'Medical Clinic': [['amenity', 'clinic'], ['amenity', 'doctors']],
  'Pharmacy': [['amenity', 'pharmacy'], ['healthcare', 'pharmacy']],
  'Veterinary Clinic': [['amenity', 'veterinary']],
  'Optometrist': [['shop', 'optician'], ['healthcare', 'optometrist']],
  'Physiotherapy': [['healthcare', 'physiotherapist']], 'Chiropractor': [['healthcare', 'chiropractor']],
  'Hospital': [['amenity', 'hospital']], 'Dermatology Clinic': [['healthcare:speciality', 'dermatology']],
  'Orthodontist': [['healthcare:speciality', 'orthodontics']],
  'Fertility / IVF Centre': [['healthcare:speciality', 'fertility']],
  'Mental Health Clinic': [['healthcare', 'psychotherapist'], ['healthcare:speciality', 'psychiatry']],
  'Diagnostic Lab': [['healthcare', 'laboratory']],
  'Restaurant': [['amenity', 'restaurant']], 'Cafe': [['amenity', 'cafe']],
  'Bakery': [['shop', 'bakery'], ['shop', 'pastry']], 'Bar': [['amenity', 'bar']],
  'Pub': [['amenity', 'pub']], 'Fast Food': [['amenity', 'fast_food']],
  'Ice Cream Shop': [['amenity', 'ice_cream'], ['shop', 'ice_cream']],
  'Pizzeria': [['cuisine', 'pizza'], ['amenity', 'fast_food']],
  'Food Truck': [['amenity', 'fast_food']], 'Brewery': [['craft', 'brewery'], ['industrial', 'brewery']],
  'Winery': [['craft', 'winery'], ['shop', 'wine']],
  'Coffee Shop / Roaster': [['shop', 'coffee']], 'Juice / Smoothie Bar': [['shop', 'beverages']],
  'Wine / Liquor Shop': [['shop', 'wine'], ['shop', 'alcohol']],
  'Nightclub': [['amenity', 'nightclub']], 'Lounge': [['amenity', 'bar']],
  'Catering Service': [['craft', 'caterer']], 'Deli / Fine Food': [['shop', 'deli']],
  'Health Food Shop': [['shop', 'health_food']], 'Tea House': [['shop', 'tea']],
  'Confectionery / Sweets': [['shop', 'confectionery'], ['shop', 'chocolate']],
  'Plumber': [['craft', 'plumber']], 'Electrician': [['craft', 'electrician']],
  'HVAC / Heating': [['craft', 'hvac'], ['craft', 'heating_engineer']],
  'Carpenter': [['craft', 'carpenter'], ['craft', 'joiner']],
  'Painter / Decorator': [['craft', 'painter']], 'Roofer': [['craft', 'roofer']],
  'Gardener / Landscaper': [['craft', 'gardener']], 'Cleaning Service': [['craft', 'cleaning'], ['shop', 'cleaning']],
  'Pest Control': [['craft', 'pest_control']], 'Locksmith': [['craft', 'locksmith'], ['shop', 'locksmith']],
  'Solar Installer': [['craft', 'solar']], 'Security Company': [['office', 'security']],
  'Moving Company': [['office', 'moving_company']], 'Pool Service': [['craft', 'pool_maintenance']],
  'Water Purifier / RO': [['shop', 'water']], 'AC Repair & Service': [['craft', 'hvac']],
  'Chimney Sweep': [['craft', 'chimney_sweeper']], 'Scaffolder': [['craft', 'scaffolder']],
  'Stonemason': [['craft', 'stonemason']], 'Upholsterer': [['craft', 'upholsterer']],
  'Auto Repair Garage': [['shop', 'car_repair']], 'Car Wash': [['amenity', 'car_wash']],
  'Car Dealership': [['shop', 'car']], 'Tyre Shop': [['shop', 'tyres']],
  'Motorcycle Workshop': [['shop', 'motorcycle_repair']], 'Car Detailing': [['shop', 'car_repair']],
  'Car Rental': [['amenity', 'car_rental']], 'Taxi Company': [['amenity', 'taxi'], ['office', 'taxi']],
  'EV Charging Network': [['amenity', 'charging_station']], 'Bicycle Shop': [['shop', 'bicycle']],
  'Towing Service': [['shop', 'car_repair']], 'Used Car Dealer': [['shop', 'car']],
  'Bike / Motorcycle Dealer': [['shop', 'motorcycle']],
  'Real Estate Agency': [['office', 'estate_agent']], 'Construction Company': [['office', 'construction_company'], ['craft', 'builder']],
  'Interior Designer': [['shop', 'interior_decoration'], ['office', 'interior_design']],
  'Architect': [['office', 'architect']], 'Estate Agent': [['office', 'estate_agent']],
  'Property Management': [['office', 'property_management']], 'Law Firm': [['office', 'lawyer']],
  'Accountant': [['office', 'accountant']], 'Insurance Agency': [['office', 'insurance']],
  'Marketing Agency': [['office', 'advertising_agency'], ['office', 'marketing']],
  'Photography Studio': [['craft', 'photographer'], ['shop', 'photo']],
  'Travel Agency': [['shop', 'travel_agency']], 'Consulting': [['office', 'consulting']],
  'Recruitment Agency': [['office', 'employment_agency']], 'Translation Service': [['office', 'translator']],
  'BPO / Call Centre': [['office', 'telecommunication']],
  'Financial Advisor': [['office', 'financial_advisor'], ['office', 'financial']],
  'Tax Consultant': [['office', 'tax_advisor']], 'Bookkeeping': [['office', 'accountant']],
  'Mortgage Broker': [['office', 'mortgage_broker']], 'Loan Agency': [['office', 'financial']],
  'Stock Broker': [['office', 'financial']], 'Company Secretary': [['office', 'company']],
  'Notary': [['office', 'notary']], 'Immigration Lawyer': [['office', 'lawyer']],
  'Personal Injury Lawyer': [['office', 'lawyer']],
  'Video Production': [['craft', 'photographer'], ['office', 'film_production']],
  'Wedding Photography': [['craft', 'photographer']], 'Branding Studio': [['office', 'graphic_design']],
  'Web Design Studio': [['office', 'it'], ['office', 'web_design']], 'IT Company': [['office', 'it']],
  'Copywriting Studio': [['office', 'advertising_agency']],
  'Picture Framer': [['craft', 'frame_maker'], ['shop', 'frame']],
  'Art Gallery / Studio': [['shop', 'art'], ['tourism', 'gallery']],
  'Adventure Tours': [['shop', 'outdoor'], ['office', 'tour_operator']],
  'Tour Operator': [['office', 'tour_operator'], ['shop', 'travel_agency']],
  'Visa Consultant': [['office', 'visa']],
  'Hotel': [['tourism', 'hotel']], 'Guest House / B&B': [['tourism', 'guest_house'], ['tourism', 'bed_and_breakfast']],
  'Hostel': [['tourism', 'hostel']], 'Motel': [['tourism', 'motel']],
  'School': [['amenity', 'school']], 'Driving School': [['amenity', 'driving_school']],
  'Coding Bootcamp': [['amenity', 'training']], 'Music School': [['amenity', 'music_school']],
  'Dance Academy': [['leisure', 'dance'], ['amenity', 'dancing_school']],
  'Childcare / Nursery': [['amenity', 'childcare'], ['amenity', 'kindergarten']],
  'Pet Grooming': [['shop', 'pet_grooming']], 'Pet Store': [['shop', 'pet']],
  'Pet Boarding': [['amenity', 'animal_boarding']], 'Dog Training': [['amenity', 'animal_training']],
  'Florist': [['shop', 'florist']], 'Jewellery Store': [['shop', 'jewelry']],
  'Clothing Store': [['shop', 'clothes']], 'Shoe Store': [['shop', 'shoes']],
  'Furniture Store': [['shop', 'furniture']], 'Electronics Store': [['shop', 'electronics']],
  'Grocery / Convenience': [['shop', 'convenience'], ['shop', 'grocery']],
  'Supermarket': [['shop', 'supermarket']], 'Butcher': [['shop', 'butcher']],
  'Bookstore': [['shop', 'books']], 'Gift Shop': [['shop', 'gift']],
  'Laundry / Dry Clean': [['shop', 'laundry'], ['shop', 'dry_cleaning']],
  'Tailor / Alterations': [['craft', 'tailor'], ['shop', 'tailor']],
  'Watch Store / Repair': [['shop', 'watches'], ['craft', 'watchmaker']],
  'Home Decor': [['shop', 'houseware'], ['shop', 'interior_decoration']],
  'Hardware Store': [['shop', 'hardware'], ['shop', 'doityourself']],
  'Garden Centre / Nursery': [['shop', 'garden_centre'], ['shop', 'nursery']],
  'Farm Shop': [['shop', 'farm']], 'Toy Store': [['shop', 'toys']], 'Sports Shop': [['shop', 'sports']],
  'Church': [['building', 'church'], ['religion', 'christian']],
  'Temple': [['building', 'temple'], ['religion', 'hindu']],
  'Mosque': [['building', 'mosque'], ['religion', 'muslim']],
  'NGO / Charity': [['office', 'ngo'], ['office', 'charity']],
  'Ashram / Retreat': [['amenity', 'monastery']], 'Gurudwara': [['religion', 'sikh']],
  'Community Organisation': [['amenity', 'community_centre'], ['office', 'association']],
  'Funeral Director': [['shop', 'funeral_directors']], 'Government Office': [['office', 'government']],
  'Event Venue': [['amenity', 'events_venue']], 'Wedding Venue': [['amenity', 'events_venue']],
  'Wedding Planner': [['office', 'wedding_planner']], 'Event Management': [['office', 'event_management']],
  'Banquet Hall': [['amenity', 'events_venue']], 'Wedding Decorator': [['shop', 'party']],
  'Event Rentals': [['shop', 'party'], ['shop', 'rental']],
  'DJ & Entertainment': [['office', 'event_management']],
  'Cinema': [['amenity', 'cinema']], 'Bowling Alley': [['leisure', 'bowling_alley']],
  'Museum': [['tourism', 'museum']], 'Amusement Park': [['tourism', 'theme_park']],
  'Escape Room': [['leisure', 'escape_game']], 'Gaming Center': [['leisure', 'amusement_arcade'], ['amenity', 'internet_cafe']],
  'Bank / Credit Union': [['amenity', 'bank']],
  'Textile Manufacturer': [['craft', 'textile'], ['industrial', 'textile']],
  'Furniture Manufacturer': [['craft', 'cabinet_maker'], ['industrial', 'furniture']],
  'Steel & Metal Works': [['industrial', 'steel'], ['industrial', 'foundry']],
  'Food Processing': [['industrial', 'food'], ['man_made', 'works']],
  'Pharma Manufacturer': [['industrial', 'pharmaceutical']],
  'Packaging Company': [['industrial', 'packaging']],
  'Courier Service': [['amenity', 'post_office'], ['office', 'courier']],
  'Warehouse': [['building', 'warehouse'], ['landuse', 'logistics']],
  'Logistics Company': [['office', 'logistics']], 'Freight Forwarder': [['office', 'forwarding_agency'], ['office', 'logistics']],
  'Farm': [['place', 'farm'], ['landuse', 'farmyard']], 'Dairy Farm': [['shop', 'dairy'], ['landuse', 'farmyard']],
  'Poultry Farm': [['landuse', 'farmyard']], 'Agri Company': [['shop', 'agrarian']],
  'Plant Nursery': [['shop', 'garden_centre'], ['landuse', 'plant_nursery']],
  'Co-working Space': [['office', 'coworking'], ['amenity', 'coworking_space']],
  'Print Shop': [['shop', 'copyshop'], ['shop', 'printing']],
};
export const SEGMENTS = {};
for (const [niche, tags] of Object.entries(NICHES)) {
  const key = tags[0][0]; const val = tags[0][1];
  if (key === 'shop' || key === 'craft') SEGMENTS[niche] = 'Retail & Services';
  else if (key === 'amenity') {
    if (['restaurant','cafe','fast_food','bar','pub','ice_cream','nightclub'].includes(val)) SEGMENTS[niche] = 'Food & Drink';
    else if (['hospital','clinic','doctors','dentist','pharmacy','veterinary'].includes(val)) SEGMENTS[niche] = 'Healthcare';
    else if (['school','college','university','kindergarten','driving_school','music_school','language_school','dancing_school'].includes(val)) SEGMENTS[niche] = 'Education';
    else if (['bank','atm'].includes(val)) SEGMENTS[niche] = 'Finance';
    else if (['fuel','charging_station'].includes(val)) SEGMENTS[niche] = 'Automotive';
    else if (['cinema','theatre','community_centre','events_venue','townhall'].includes(val)) SEGMENTS[niche] = 'Entertainment';
    else SEGMENTS[niche] = 'Other';
  } else if (key === 'leisure') {
    if (['fitness_centre','sports_centre','pitch','track','swimming_pool'].includes(val)) SEGMENTS[niche] = 'Fitness & Sports';
    else if (['spa','park','garden','nature_reserve'].includes(val)) SEGMENTS[niche] = 'Wellness';
    else SEGMENTS[niche] = 'Leisure';
  } else if (key === 'tourism') {
    if (['hotel','motel','guest_house','hostel','camp_site','caravan_site','apartment','chalet','resort'].includes(val)) SEGMENTS[niche] = 'Hospitality';
    else SEGMENTS[niche] = 'Attractions';
  } else if (key === 'office') SEGMENTS[niche] = 'Professional Services';
  else if (key === 'healthcare') SEGMENTS[niche] = 'Healthcare';
  else if (key === 'industrial' || key === 'man_made') SEGMENTS[niche] = 'Manufacturing';
  else if (key === 'building') SEGMENTS[niche] = 'Property';
  else if (key === 'religion') SEGMENTS[niche] = 'Religious';
  else SEGMENTS[niche] = 'Other';
}
export function getGroupedNiches() { const groups = {}; for (const [niche, segment] of Object.entries(SEGMENTS)) (groups[segment] = groups[segment] || []).push(niche); for (const seg of Object.keys(groups)) groups[seg].sort(); return groups; }
export function getNicheNames() { return Object.keys(NICHES).sort(); }
