/**
 * modelDescriptions.js
 *
 * Human-readable one-line descriptions for every model id served by the
 * /api/model-catalog endpoint.  Shown in the TemplateStudio model
 * dropdown (truncated to 80 chars by the frontend).
 *
 * Three IDs appear in more than one pool (flux-pulid, flux-redux,
 * qwen-text-to-image-2512) so the map is keyed by modelType.
 */

export const DESCRIPTIONS = {
  t2i: {
    'nano-banana': 'Fast and playful AI image generation with a creative twist.',
    'flux-dev': 'High-quality Flux-based image generation with full parameter control.',
    'flux-kontext-dev-t2i': 'Context-aware Flux image generation for complex scene prompts.',
    'ai-anime-generator': 'Specialised AI anime and illustration image generation.',
    'wan2.1-text-to-image': 'Wan 2.1 text-to-image with dimension constraints for reliable output.',
    'flux-kontext-pro-t2i': 'Professional Flux Kontext with advanced aspect ratio options.',
    'flux-kontext-max-t2i': 'Maximum-quality Flux Kontext generation with aspect ratio control.',
    'gpt4o-text-to-image': 'OpenAI GPT-4o text-to-image with selectable aspect ratios.',
    'midjourney-v7-text-to-image': 'Midjourney v7 stylised text-to-image with speed and stylisation.',
    'flux-schnell': 'Ultra-fast Flux image generation for rapid prototyping and iteration.',
    'qwen-image': 'Alibaba Qwen versatile image generation with multi-aspect ratio support.',
    'flux-pulid': 'Flux-based identity-preserving image generation from a reference face.',
    'ideogram-v3-t2i': 'Ideogram v3 text-to-image with render speed and style controls.',
    'google-imagen4': 'Google Imagen 4 — high-fidelity text-to-image with aspect ratio options.',
    'google-imagen4-fast': 'Google Imagen 4 in a fast, low-latency mode.',
    'google-imagen4-ultra': 'Google Imagen 4 ultra-quality mode for maximum detail.',
    'sdxl-image': 'Stable Diffusion XL image generation with full width and height control.',
    'bytedance-seedream-v4': 'ByteDance Seedream v4 with resolution and multi-image support.',
    'hunyuan-image-2.1': 'Tencent Hunyuan Image 2.1 — cinematic-quality text-to-image.',
    'chroma-image': 'Vivid chromatic gradients and surreal colour-field image generation.',
    'flux-redux': 'Flux Redux image reimagining driven by an input image and prompt.',
    'flux-krea-dev': 'Flux Dev optimised for Krea integration with widescreen aspect ratios.',
    'perfect-pony-xl': 'High-detail animal and fantasy character image generation.',
    'neta-lumina': 'Painterly anime-style character image generation with refined textures.',
    'wan2.5-text-to-image': 'Wan 2.5 text-to-image with 768–1440px resolution range.',
    'hunyuan-image-3.0': 'Tencent Hunyuan Image 3.0 with refined aesthetics and quality.',
    'leonardoai-phoenix-1.0': 'Leonardo AI Phoenix 1.0 creative image generation with aspect ratio control.',
    'leonardoai-lucid-origin': 'Leonardo AI Lucid Origin cinematic image generation with widescreen support.',
    'reve-text-to-image': 'REVE photorealistic text-to-image with cinematic widescreen support.',
    'grok-imagine-text-to-image': 'xAI Grok Imagine text-to-image with fast turnaround.',
    'nano-banana-pro': 'Higher-fidelity creative AI image generation with resolution control.',
    'kling-o1-text-to-image': 'Kling O1 high-resolution text-to-image with 1K and 2K modes.',
    'z-image-turbo': 'Z Image Turbo — ultra-fast high-detail image generation.',
    'flux-2-dev': 'Flux 2 development model for high-quality experimental image generation.',
    'flux-2-flex': 'Flux 2 flexible model with resolution and aspect ratio control.',
    'flux-2-pro': 'Flux 2 professional-grade image generation for production use cases.',
    'vidu-q2-text-to-image': 'Vidu Q2 fast text-to-image generation.',
    'bytedance-seedream-v4.5': 'Latest ByteDance Seedream v4.5 image generation model.',
    'gpt-image-1.5': 'OpenAI GPT Image 1.5 with aspect ratio and multi-image support.',
    'wan2.6-text-to-image': 'Wan 2.6 latest text-to-image model with refined output quality.',
    'qwen-text-to-image-2512': 'Alibaba Qwen text-to-image model for creative asset generation.',
    'flux-2-klein-4b': 'Flux 2 Klein 4B lightweight parameter-efficient image generation.',
    'flux-2-klein-9b': 'Flux 2 Klein 9B balanced parameter-efficient image generation.',
    'z-image-base': 'Z Image Base foundational high-detail text-to-image generation.',
    'nano-banana-2': 'Next-generation Nano Banana creative image generation.',
    'seedream-5.0': 'ByteDance Seedream 5.0 high-fidelity image generation.',
  },
  i2i: {
    'ai-image-upscaler': 'AI-powered image upscaling and resolution enhancement.',
    'ai-image-face-swap': 'AI face swapping between source and target images.',
    'ai-dress-change': 'AI virtual clothing replacement and fashion editing.',
    'ai-background-remover': 'AI-powered background removal from any source image.',
    'ai-product-shot': 'Quick AI product shot generation for e-commerce catalogs.',
    'ai-skin-enhancer': 'AI skin retouching and portrait enhancement tool.',
    'ai-color-photo': 'AI colourisation and enhancement for black and white photographs.',
    'flux-kontext-dev-i2i': 'Flux Kontext Dev image-to-image style transformation.',
    'ai-product-photography': 'AI product photography generation with professional lighting.',
    'ai-ghibli-style': 'Ghibli art style filter and transformation for any image.',
    'ai-image-extension': 'AI-powered outpainting and image border extension.',
    'ai-object-eraser': 'AI-powered object removal and inpainting from images.',
    'flux-kontext-pro-i2i': 'Flux Kontext Pro professional image-to-image editing.',
    'flux-kontext-max-i2i': 'Flux Kontext Max maximum-quality image-to-image editing.',
    'gpt4o-image-to-image': 'GPT-4o image-to-image transformation with strength and size control.',
    'gpt4o-edit': 'GPT-4o image editing with configurable strength and aspect ratio.',
    'midjourney-v7-image-to-image': 'Midjourney v7 image-to-image with stylisation and variety control.',
    'bytedance-seededit-v3': 'ByteDance SeedEdit v3 precision image editing.',
    'midjourney-v7-style-reference': 'Midjourney v7 style-reference driven image-to-image editing.',
    'midjourney-v7-omni-reference': 'Midjourney v7 omnidirectional reference image generation.',
    'minimax-image-01-subject-reference': 'MiniMax Image 01 subject-reference driven editing.',
    'ideogram-character': 'Ideogram v3 consistent character generation and reference.',
    'flux-pulid': 'Flux-based identity-preserving image generation from a reference face.',
    'qwen-image-edit': 'Alibaba Qwen image editing with aspect ratio controls.',
    'image-effects': 'General image effects processing and enhancement.',
    'nano-banana-edit': 'Nano Banana creative image editing with style guidance.',
    'ideogram-v3-reframe': 'Ideogram v3 aspect ratio reframing and recomposition.',
    'bytedance-seedream-edit-v4': 'ByteDance Seedream v4 guided image editing.',
    'nano-banana-effects': 'Nano Banana creative visual effects image generation.',
    'flux-kontext-effects': 'Flux Kontext visual effects and stylisation filter.',
    'flux-redux': 'Flux Redux image reimagining driven by an input image and prompt.',
    'qwen-image-edit-plus': 'Alibaba Qwen enhanced image editing with LoRA support.',
    'wan2.5-image-edit': 'Wan 2.5 image editing with strength and resolution control.',
    'reve-image-edit': 'REVE image editing and transformation toolkit.',
    'topaz-image-upscale': 'Topaz Labs AI image upscaling and detail enhancement.',
    'seedvr2-image-upscale': 'ByteDance SeedVR2 AI image upscaling and restoration.',
    'qwen-image-edit-plus-lora': 'Qwen image editing with LoRA model weight injection.',
    'nano-banana-pro-edit': 'Nano Banana Pro image editing with higher fidelity.',
    'kling-o1-edit-image': 'Kling O1 image editing and inpainting with object control.',
    'flux-2-dev-edit': 'Flux 2 Dev image editing with strength and size controls.',
    'flux-2-flex-edit': 'Flux 2 Flex image editing with aspect ratio and strength.',
    'flux-2-pro-edit': 'Flux 2 Pro image editing with strength and aspect ratio control.',
    'vidu-q2-reference-to-image': 'Vidu Q2 reference-to-image style transfer generation.',
    'bytedance-seedream-v4.5-edit': 'ByteDance Seedream v4.5 guided image editing.',
    'qwen-image-edit-2511': 'Alibaba Qwen image editing — November 2025 release.',
    'wan2.6-image-edit': 'Wan 2.6 latest image editing with enhanced controls.',
    'qwen-text-to-image-2512': 'Alibaba Qwen text-to-image model for creative asset generation.',
    'gpt-image-1.5-edit': 'OpenAI GPT Image 1.5 image editing with strength control.',
    'grok-imagine-image-to-image': 'xAI Grok Imagine image-to-image style transfer.',
    'flux-2-klein-4b-edit': 'Flux 2 Klein 4B lightweight image editing.',
    'flux-2-klein-9b-edit': 'Flux 2 Klein 9B balanced parameter-efficient image editing.',
    'add-image-watermark': 'Batch image watermark overlay and branding tool.',
    'nano-banana-2-edit': 'Nano Banana 2 image editing and guided transformation.',
    'seedream-5.0-edit': 'ByteDance Seedream 5.0 precision image editing.',
  },
  i2v: {
    'ai-video-effects': 'AI video effects processing and enhancement pipeline.',
    'motion-controls': 'Motion parameter control overlay for image-to-video pipelines.',
    'vfx': 'Visual effects processing and compositing for images and video.',
    'veo3-image-to-video': 'Google Veo 3 high-quality image-to-video generation.',
    'veo3-fast-image-to-video': 'Google Veo 3 fast image-to-video generation.',
    'runway-image-to-video': 'Runway Gen image-to-video cinematic generation.',
    'wan2.1-image-to-video': 'Wan 2.1 image-to-video with motion control.',
    'midjourney-v7-image-to-video': 'Midjourney v7 image-to-video cinematic generation.',
    'hunyuan-image-to-video': 'Tencent Hunyuan image-to-video cinematic generation.',
    'kling-v2.1-master-i2v': 'Kling V2.1 Master flagship image-to-video generation.',
    'kling-v2.1-standard-i2v': 'Kling V2.1 Standard image-to-video generation.',
    'kling-v2.1-pro-i2v': 'Kling V2.1 Pro high-quality image-to-video generation.',
    'wan2.2-image-to-video': 'Wan 2.2 improved image-to-video generation.',
    'runway-act-two-i2v': 'Runway Act Two expressive image-to-video generation.',
    'pixverse-v4.5-i2v': 'PixVerse v4.5 image-to-video generation.',
    'vidu-v2.0-i2v': 'Vidu 2.0 image-to-video with scene coherence.',
    'vidu-q1-reference': 'Vidu Q1 reference-video guided generation.',
    'minimax-hailuo-02-standard-i2v': 'MiniMax Hailuo 02 Standard image-to-video generation.',
    'minimax-hailuo-02-pro-i2v': 'MiniMax Hailuo 02 Pro image-to-video generation.',
    'video-effects': 'Video effects processing, filters and transitions.',
    'seedance-lite-i2v': 'ByteDance Seedance Lite lightweight image-to-video.',
    'seedance-pro-i2v': 'ByteDance Seedance Pro image-to-video generation.',
    'pixverse-v5-i2v': 'PixVerse v5 image-to-video with improved motion coherence.',
    'seedance-lite-reference-video': 'Seedance Lite reference-video guided generation.',
    'wan2.1-reference-video': 'Wan 2.1 reference-video guided generation.',
    'kling-v2.5-turbo-pro-i2v': 'Kling V2.5 Turbo Pro fast image-to-video generation.',
    'wan2.5-image-to-video': 'Wan 2.5 image-to-video with enhanced motion fidelity.',
    'wan2.5-image-to-video-fast': 'Wan 2.5 fast mode image-to-video for rapid iteration.',
    'openai-sora-2-image-to-video': 'OpenAI Sora 2 cinematic image-to-video generation.',
    'ovi-image-to-video': 'OVI image-to-video generation engine.',
    'openai-sora-2-pro-image-to-video': 'OpenAI Sora 2 Pro high-fidelity image-to-video.',
    'leonardoai-motion-2.0': 'Leonardo AI Motion 2.0 image animation and motion generation.',
    'veo3.1-image-to-video': 'Google Veo 3.1 high-fidelity image-to-video generation.',
    'veo3.1-fast-image-to-video': 'Google Veo 3.1 fast image-to-video generation.',
    'veo3.1-reference-to-video': 'Google Veo 3.1 reference-driven video generation.',
    'seedance-pro-i2v-fast': 'ByteDance Seedance Pro fast image-to-video.',
    'ltx-2-pro-image-to-video': 'LTX 2 Pro high-quality image-to-video generation.',
    'ltx-2-fast-image-to-video': 'LTX 2 fast low-latency image-to-video generation.',
    'vidu-q2-reference': 'Vidu Q2 reference-video driven generation.',
    'vidu-q2-turbo-start-end-video': 'Vidu Q2 turbo start-to-end video generation.',
    'vidu-q2-pro-start-end-video': 'Vidu Q2 Pro start-to-end video generation.',
    'minimax-hailuo-2.3-pro-i2v': 'MiniMax Hailuo 2.3 Pro image-to-video generation.',
    'minimax-hailuo-2.3-standard-i2v': 'MiniMax Hailuo 2.3 Standard image-to-video.',
    'minimax-hailuo-2.3-fast': 'MiniMax Hailuo 2.3 fast inference image-to-video.',
    'kling-v2.5-turbo-std-i2v': 'Kling V2.5 Turbo Standard fast image-to-video.',
    'grok-imagine-image-to-video': 'xAI Grok Imagine image-to-video generation.',
    'kling-o1-image-to-video': 'Kling O1 high-resolution image-to-video generation.',
    'kling-o1-reference-to-video': 'Kling O1 reference-video guided generation.',
    'kling-v2.6-pro-i2v': 'Kling V2.6 Pro latest image-to-video generation.',
    'pixverse-v5.5-i2v': 'PixVerse v5.5 latest image-to-video generation.',
    'wan2.2-spicy-image-to-video': 'Wan 2.2 Spicy high-energy image-to-video mode.',
    'wan2.6-image-to-video': 'Wan 2.6 latest image-to-video with improved quality.',
    'kling-o1-standard-image-to-video': 'Kling O1 Standard image-to-video generation.',
    'kling-o1-standard-reference-to-video': 'Kling O1 Standard reference-to-video.',
    'seedance-v1.5-pro-i2v': 'ByteDance Seedance 1.5 Pro image-to-video generation.',
    'seedance-v1.5-pro-i2v-fast': 'ByteDance Seedance 1.5 Pro fast image-to-video.',
    'ltx-2-19b-image-to-video': 'LTX 2 19B large-scale image-to-video cinematic generation.',
    'kling-v3.0-pro-image-to-video': 'Kling V3.0 Pro cinematic image-to-video generation.',
    'kling-v3.0-standard-image-to-video': 'Kling V3.0 Standard image-to-video generation.',
    'seedance-v2.0-i2v': 'ByteDance Seedance 2.0 latest image-to-video generation.',
  },
  v2v: {
    'video-watermark-remover': 'Remove watermarks, logos, captions, and unwanted text from videos.',
  },
};

/**
 * Return a one-line description for a model within a given modelType.
 * Returns null when no hand-written description exists (caller may fall back).
 */
export function getModelDescription(modelType, modelId) {
  return DESCRIPTIONS[modelType]?.[modelId] || null;
}
