import { ALL_NICHE_TEMPLATES, RESTAURANT_TEMPLATES, MED_SPA_TEMPLATES, SALON_TEMPLATES, FITNESS_TEMPLATES, REAL_ESTATE_TEMPLATES, DENTAL_TEMPLATES, CHIROPRACTIC_TEMPLATES, LEGAL_TEMPLATES, AUTOMOTIVE_TEMPLATES, FASHION_TEMPLATES, EVENT_TEMPLATES, LUXURY_TEMPLATES } from './nicheTemplatesIndex.js';
import { MATRIX_TEMPLATES } from './templateMatrix.js';

export const TEMPLATE_CATEGORIES = {
  SOCIAL: 'Social Media',
  STYLE: 'Style Transfer',
  ENTERTAINMENT: 'Entertainment',
  COMMERCIAL: 'Commercial',
  VFX: 'VFX & Action',
  PORTRAIT: 'Portrait & Creator',
  DECADE: 'Decade & Era',
  CAMERA: 'Camera & Cinematic',
  // Niche categories
  INDUSTRY: 'Industry',
  RESTAURANT: 'Restaurant & Cafe',
  MED_SPA: 'Med Spa',
  SALON: 'Salon & Beauty',
  FITNESS: 'Fitness & Training',
  REAL_ESTATE: 'Real Estate',
  DENTAL: 'Dental',
  CHIROPRACTIC: 'Chiropractic',
  LEGAL: 'Legal',
  AUTOMOTIVE: 'Automotive',
  FASHION: 'Fashion',
  EVENT: 'Events',
  LUXURY: 'Luxury',
};

export const templates = [
  {
    id: 'tiktok-video',
    name: 'TikTok Video Creator',
    description: 'Create viral 9:16 videos with trending effects',
    category: TEMPLATE_CATEGORIES.SOCIAL,
    icon: '🎵',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '9:16',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Describe the video', placeholder: 'e.g. dancing in the rain' },
      { name: 'name', type: 'select', label: 'Effect', options: ['360 Rotation', 'Cakeify', 'Disney Princess It', 'Lego', 'Pixar', 'Super Saiyan Transformation', 'VHS Footage', 'Wind Blast'] },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['9:16', '16:9', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    basePrompt: '{prompt}, TikTok video format, vertical 9:16, trending content, viral style, Gen Z aesthetic, mobile-optimized, engaging, share-worthy, 4K quality',
    defaultParams: { resolution: '720p', duration: 5 },
  },
  {
    id: 'instagram-reel',
    name: 'Instagram Reel Generator',
    description: 'Aesthetic reels with cinematic motion',
    category: TEMPLATE_CATEGORIES.SOCIAL,
    icon: '📸',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '9:16',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Describe the scene', placeholder: 'e.g. fashion editorial vibe' },
      { name: 'name', type: 'select', label: 'Camera Motion', options: ['Dolly In', 'Dolly Zoom In', 'Crane Up', 'Arc Shot', 'FPV Drone Cam', 'Whip Pan', 'Zoom In'] },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['9:16', '16:9', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    basePrompt: '{prompt}, Instagram Reel format, vertical 9:16, social media content, cinematic motion, professional cinematography, engaging, mobile-optimized, trending, high quality, 4K',
    defaultParams: { resolution: '720p', duration: 5 },
  },
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail',
    description: 'Bold, eye-catching thumbnails that drive clicks',
    category: TEMPLATE_CATEGORIES.SOCIAL,
    icon: '▶️',
    outputType: 'image',
    model: 'nano-banana',
    modelType: 't2i',
    aspectRatio: '16:9',
    inputs: [
      { name: 'prompt', type: 'textarea', label: 'Describe your thumbnail', placeholder: 'e.g. shocked face reaction with fire background, bold text overlay' },
    ],
    basePrompt: '{prompt}, YouTube thumbnail style, bold dramatic composition, vibrant saturated colors, high contrast, eye-catching, professional, 4K',
  },
  {
    id: 'reaction-thumbnail',
    name: 'Reaction Thumbnail',
    description: 'Expressive reaction images for content',
    category: TEMPLATE_CATEGORIES.SOCIAL,
    icon: '😱',
    outputType: 'image',
    model: 'image-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. shocked expression, dramatic lighting' },
      { name: 'name', type: 'select', label: 'Effect', options: ['Advanced Photography', 'Cyberpunk', 'Futuristic American Comics'] },
    ],
    basePrompt: '{prompt}, reaction thumbnail style, expressive emotion, dramatic lighting, high impact, YouTube clickbait, bold composition, vibrant colors, professional quality, 4K',
    defaultParams: {},
  },
  {
    id: 'short-form-ad',
    name: 'Short-Form Ad',
    description: 'Product promo videos for social feeds',
    category: TEMPLATE_CATEGORIES.SOCIAL,
    icon: '📢',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '9:16',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload product image' },
      { name: 'prompt', type: 'text', label: 'Product description', placeholder: 'e.g. luxury sneaker reveal' },
      { name: 'name', type: 'select', label: 'Camera Motion', options: ['Dolly In', 'Crash Zoom In', 'Lazy Susan', '360 Orbit', 'Zoom In'] },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['9:16', '16:9', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10', '15'] },
    ],
    basePrompt: '{prompt}, short-form advertisement, vertical 9:16, product showcase, commercial quality, brand storytelling, engaging, mobile-first, professional marketing, high conversion, 4K',
    defaultParams: { resolution: '720p', duration: 5 },
  },
  {
    id: 'story-highlight-cover',
    name: 'Story Highlight Cover',
    description: 'Minimalist icon-style story covers',
    category: TEMPLATE_CATEGORIES.SOCIAL,
    icon: '⭐',
    outputType: 'image',
    model: 'nano-banana',
    modelType: 't2i',
    aspectRatio: '1:1',
    inputs: [
      { name: 'prompt', type: 'textarea', label: 'Describe the icon', placeholder: 'e.g. travel, food, fitness, beauty' },
    ],
    basePrompt: 'Minimal icon for Instagram story highlight cover: {prompt}, clean flat design, pastel gradient background, centered icon, simple elegant aesthetic, no text',
  },
  {
    id: 'profile-picture',
    name: 'Profile Picture Generator',
    description: 'Professional AI-generated profile photos',
    category: TEMPLATE_CATEGORIES.SOCIAL,
    icon: '👤',
    outputType: 'image',
    model: 'flux-kontext-effects',
    modelType: 'i2i',
    aspectRatio: '1:1',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'name', type: 'select', label: 'Enhancement', options: ['Professional Photo', 'Face Enhancement', 'Background Change', 'Color Correction', 'Style Transfer'] },
      { name: 'prompt', type: 'text', label: 'Additional instructions', placeholder: 'e.g. warm studio lighting' },
    ],
    basePrompt: '{prompt}, professional profile picture, LinkedIn-ready, clean background, professional lighting, high quality, polished, corporate, trustworthy, 4K',
  },
  {
    id: 'banner-creator',
    name: 'Banner Creator',
    description: 'Wide cinematic banners for channels and pages',
    category: TEMPLATE_CATEGORIES.SOCIAL,
    icon: '🖼️',
    outputType: 'image',
    model: 'nano-banana',
    modelType: 't2i',
    aspectRatio: '21:9',
    inputs: [
      { name: 'prompt', type: 'textarea', label: 'Describe your banner', placeholder: 'e.g. futuristic cityscape at sunset' },
    ],
    basePrompt: '{prompt}, ultra-wide cinematic banner, panoramic composition, professional, detailed, high quality, 8K resolution',
  },
  {
    id: 'anime-converter',
    name: 'Anime Converter',
    description: 'Transform any photo into anime style',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '🎌',
    outputType: 'image',
    model: 'ai-ghibli-style',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. dramatic anime scene with action' },
    ],
    basePrompt: '{prompt}, anime style, Japanese animation, hand-drawn, Studio Ghibli inspired, vibrant colors, expressive, detailed, anime aesthetic, 4K quality',
    defaultParams: {},
  },
  {
    id: 'comic-book',
    name: 'Comic Book Style',
    description: 'Turn photos into American comic art',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '💥',
    outputType: 'image',
    model: 'image-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. superhero action scene' },
      { name: 'name', type: 'select', label: 'Style', options: ['American Comic Style', 'Futuristic American Comics'] },
    ],
    basePrompt: '{prompt}, American comic book style, bold colors, dynamic action, superhero pose, Marvel DC aesthetic, comic panel, ink lines, dramatic lighting, pop art, 4K quality',
  },
  {
    id: 'gta-loading-screen',
    name: 'GTA Loading Screen',
    description: 'Rockstar Games satirical illustration style',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '🎮',
    outputType: 'image',
    model: 'nano-banana',
    modelType: 't2i',
    aspectRatio: '9:16',
    inputs: [
      { name: 'prompt', type: 'textarea', label: 'Describe the character', placeholder: 'e.g. man in sunglasses leaning against a sports car' },
    ],
    basePrompt: 'GTA V loading screen art style, satirical illustration, bold outlines, {prompt}, vibrant city backdrop, Rockstar Games aesthetic, stylized digital painting, dramatic pose, Los Santos vibe, comic-book shading',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art Creator',
    description: 'Retro 16-bit pixel art from photos',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '👾',
    outputType: 'image',
    model: 'image-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. fantasy character in a dungeon' },
    ],
    basePrompt: '{prompt}, pixel art style, 16-bit retro game, chiptune aesthetic, NES SNES era, pixelated, nostalgic, video game graphics, detailed pixel work, 4K',
    defaultParams: { name: 'Lofi Pixel Character' },
  },
  {
    id: 'ghibli-style',
    name: 'Ghibli Style',
    description: 'Studio Ghibli-inspired transformation',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '🌿',
    outputType: 'image',
    model: 'ai-ghibli-style',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. magical forest with flyingna ship' },
      { name: 'style', type: 'select', label: 'Style', options: ['Auto', 'Realistic', 'Fiction'] },
    ],
    basePrompt: '{prompt}, Studio Ghibli style, Hayao Miyazaki aesthetic, hand-drawn animation, whimsical, magical realism, lush nature, soft colors, Japanese anime, detailed, 4K quality',
  },
  {
    id: 'cyberpunk-style',
    name: 'Cyberpunk Style',
    description: 'Neon-soaked cyberpunk transformation',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '🌃',
    outputType: 'image',
    model: 'image-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. neon city with rain' },
    ],
    basePrompt: '{prompt}, cyberpunk style, neon lights, futuristic, high tech low life, rain-soaked streets, holographic billboards, chrome, LED lights, Blade Runner aesthetic, 4K',
    defaultParams: { name: 'Cyberpunk' },
  },
  {
    id: 'vhs-retro',
    name: 'VHS Retro',
    description: 'Analog VHS tape effect with scan lines',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '📼',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Scene description', placeholder: 'e.g. home video nostalgia' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    basePrompt: '{prompt}, VHS retro style, analog video effect, 80s aesthetic, scan lines, tracking errors, vintage home video, nostalgic, retro, lo-fi, 4K quality',
    defaultParams: { name: 'VHS Footage', resolution: '480p', duration: 5 },
  },
  {
    id: 'film-noir',
    name: 'Film Noir',
    description: 'Classic black & white detective cinema',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '🎬',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Scene mood', placeholder: 'e.g. rainy night detective' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    basePrompt: '{prompt}, film noir style, classic black and white, noir cinema, detective mystery, rainy streets, dramatic shadows, high contrast, Hitchcock aesthetic, vintage, 4K quality',
    defaultParams: { name: 'Film Noir', resolution: '720p', duration: 5 },
  },
  {
    id: 'movie-poster',
    name: 'Movie Poster',
    description: 'Cinematic theatrical movie poster design',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '🎥',
    outputType: 'image',
    model: 'nano-banana',
    modelType: 't2i',
    aspectRatio: '3:4',
    inputs: [
      { name: 'prompt', type: 'textarea', label: 'Describe the movie poster', placeholder: 'e.g. action hero standing in flames with city skyline' },
    ],
    basePrompt: 'Cinematic movie poster, dramatic lighting, epic composition, {prompt}, theatrical release style, professional film poster design, bold composition, high contrast, 4K quality',
  },
  {
    id: 'magazine-cover',
    name: 'Magazine Cover',
    description: 'High fashion magazine cover aesthetic',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '📰',
    outputType: 'image',
    model: 'nano-banana',
    modelType: 't2i',
    aspectRatio: '3:4',
    inputs: [
      { name: 'prompt', type: 'textarea', label: 'Describe the cover', placeholder: 'e.g. elegant woman in haute couture evening gown' },
    ],
    basePrompt: 'High fashion magazine cover, editorial photography, {prompt}, sophisticated layout, professional studio lighting, Vogue aesthetic, luxury fashion, pristine quality, 4K',
  },
  {
    id: 'bullet-time',
    name: 'Bullet Time Scene',
    description: 'Matrix-style freeze-frame rotation',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '⏱️',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Action description', placeholder: 'e.g. dodging in slow motion' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    basePrompt: '{prompt}, bullet time effect, Matrix-style freeze frame, slow motion rotation, cinematic action, dynamic composition, time freeze, epic stunt, 4K quality',
    defaultParams: { name: 'Matrix Shot', resolution: '720p', duration: 5 },
  },
  {
    id: 'action-figure',
    name: 'Action Figure',
    description: 'Turn yourself into a collectible action figure',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '🧸',
    outputType: 'image',
    model: 'nano-banana-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. heroic pose with cape' },
    ],
    basePrompt: '{prompt}, action figure style, collectible toy, 3D render, plastic material, realistic details, packaging design, Hasbro Mattel style, collector item, 4K quality',
    defaultParams: { name: 'Action Figure' },
  },
  {
    id: 'disney-pixar',
    name: 'Disney / Pixar Style',
    description: 'Pixar-quality 3D character render',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '✨',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Character description', placeholder: 'e.g. friendly adventurer' },
      { name: 'name', type: 'select', label: 'Style', options: ['Pixar', 'Disney Princess It', 'Snow White It'] },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    basePrompt: '{prompt}, Disney Pixar style, 3D animated movie, CGI character, Pixar quality, heartwarming, expressive, detailed fur and textures, cinematic lighting, feature film quality, 4K',
    defaultParams: { resolution: '720p', duration: 5 },
  },
  {
    id: 'superhero-transform',
    name: 'Superhero Transform',
    description: 'Epic transformation into a superhero',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '🦸',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Hero style', placeholder: 'e.g. powerful energy burst' },
      { name: 'name', type: 'select', label: 'Transformation', options: ['Hulk Transformation', 'Super Saiyan Transformation', 'Kamehameha'] },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    basePrompt: '{prompt}, superhero transformation, epic power-up, comic book style, Marvel DC aesthetic, dramatic energy burst, heroic, powerful, cinematic, 4K quality',
    defaultParams: { resolution: '720p', duration: 5 },
  },
  {
    id: 'lego-style',
    name: 'Lego Style',
    description: 'Everything is awesome in Lego form',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '🧱',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Scene', placeholder: 'e.g. lego city builder' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Lego', resolution: '720p', duration: 5 },
  },
  {
    id: 'squid-game',
    name: 'Squid Game Style',
    description: 'Korean drama survival game aesthetic',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '🔴',
    outputType: 'video',
    model: 'video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. dramatic survival game scene' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Squid Game' },
  },
  {
    id: 'product-hero',
    name: 'Product Hero Shot',
    description: 'Studio-quality product photography',
    category: TEMPLATE_CATEGORIES.COMMERCIAL,
    icon: '📦',
    outputType: 'image',
    model: 'ai-product-shot',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload product image' },
      { name: 'prompt', type: 'text', label: 'Scene description', placeholder: 'e.g. luxury marble countertop, soft lighting' },
    ],
  },
  {
    id: 'product-photography',
    name: 'Product Photography',
    description: 'Professional commercial product photos',
    category: TEMPLATE_CATEGORIES.COMMERCIAL,
    icon: '📷',
    outputType: 'image',
    model: 'ai-product-photography',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload product image' },
      { name: 'prompt', type: 'text', label: 'Photography style', placeholder: 'e.g. minimalist white studio' },
    ],
  },
  {
    id: 'billboard-ad',
    name: 'Billboard Ad',
    description: 'Ultra-wide billboard advertisement design',
    category: TEMPLATE_CATEGORIES.COMMERCIAL,
    icon: '🏗️',
    outputType: 'image',
    model: 'nano-banana',
    modelType: 't2i',
    aspectRatio: '21:9',
    inputs: [
      { name: 'prompt', type: 'textarea', label: 'Describe the billboard', placeholder: 'e.g. luxury watch on black velvet background' },
    ],
    basePrompt: 'Professional billboard advertisement, {prompt}, clean modern design, bold layout, eye-catching commercial quality, outdoor advertising, ultra-wide composition, 8K',
  },
  {
    id: 'asmr-video',
    name: 'ASMR Video',
    description: 'Satisfying slow-motion close-up content',
    category: TEMPLATE_CATEGORIES.COMMERCIAL,
    icon: '🎧',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '9:16',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload close-up photo' },
      { name: 'prompt', type: 'text', label: 'ASMR theme', placeholder: 'e.g. satisfying slime, soap cutting' },
      { name: 'name', type: 'select', label: 'Motion', options: ['Dolly In', 'Crash Zoom In', 'Focus Shift', 'Zoom In'] },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['9:16', '16:9', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { resolution: '720p', duration: 5 },
  },
  {
    id: 'product-placement',
    name: 'Product Placement',
    description: 'Natural lifestyle product integration',
    category: TEMPLATE_CATEGORIES.COMMERCIAL,
    icon: '🛍️',
    outputType: 'image',
    model: 'ai-product-shot',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload product image' },
      { name: 'prompt', type: 'text', label: 'Scene context', placeholder: 'e.g. coffee shop table, morning light' },
    ],
  },
  {
    id: 'unboxing-scene',
    name: 'Unboxing Scene',
    description: 'Dramatic product unboxing reveal',
    category: TEMPLATE_CATEGORIES.COMMERCIAL,
    icon: '📭',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '9:16',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload product image' },
      { name: 'prompt', type: 'text', label: 'Product name', placeholder: 'e.g. premium headphones' },
      { name: 'name', type: 'select', label: 'Reveal Style', options: ['Crash Zoom In', 'Dolly In', 'Dolly Zoom In', 'Zoom In'] },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['9:16', '16:9', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { resolution: '720p', duration: 5 },
  },
  {
    id: 'building-explosion',
    name: 'Building Explosion',
    description: 'Hollywood-grade building explosion VFX',
    category: TEMPLATE_CATEGORIES.VFX,
    icon: '💣',
    outputType: 'video',
    model: 'vfx',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload a building photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. apocalyptic destruction scene' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Building Explosion' },
  },
  {
    id: 'car-explosion',
    name: 'Car Explosion',
    description: 'Action movie car explosion effect',
    category: TEMPLATE_CATEGORIES.VFX,
    icon: '🚗',
    outputType: 'video',
    model: 'vfx',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload a car photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. action movie explosion' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Car Explosion' },
  },
  {
    id: 'disintegration',
    name: 'Disintegration',
    description: 'Thanos snap disintegration effect',
    category: TEMPLATE_CATEGORIES.VFX,
    icon: '💨',
    outputType: 'video',
    model: 'vfx',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. heroic disintegration' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Disintegration' },
  },
  {
    id: 'electricity',
    name: 'Electricity / Lightning',
    description: 'Electric shock and lightning effects',
    category: TEMPLATE_CATEGORIES.VFX,
    icon: '⚡',
    outputType: 'video',
    model: 'vfx',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. supercharged electrical storm' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Electricity' },
  },
  {
    id: 'tornado',
    name: 'Tornado',
    description: 'Devastating tornado VFX scene',
    category: TEMPLATE_CATEGORIES.VFX,
    icon: '🌪️',
    outputType: 'video',
    model: 'vfx',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload a landscape photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. apocalyptic tornado destruction' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Tornado' },
  },
  {
    id: 'fire-breath',
    name: 'Fire Breath',
    description: 'Dragon-style fire breath effect',
    category: TEMPLATE_CATEGORIES.VFX,
    icon: '🔥',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. fierce dragon warrior' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Fire', resolution: '720p', duration: 5 },
  },
  {
    id: 'face-swap',
    name: 'Face Swap',
    description: 'Realistic AI face swap technology',
    category: TEMPLATE_CATEGORIES.PORTRAIT,
    icon: '🔄',
    outputType: 'image',
    model: 'ai-image-face-swap',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload source face' },
      { name: 'prompt', type: 'text', label: 'Target image URL', placeholder: 'URL of target image' },
    ],
  },
  {
    id: 'gender-swap',
    name: 'Gender Swap',
    description: 'AI-powered gender transformation',
    category: TEMPLATE_CATEGORIES.PORTRAIT,
    icon: '⚧️',
    outputType: 'video',
    model: 'video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. professional headshot style' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Gender Swap' },
  },
  {
    id: 'age-progression',
    name: 'Age Progression',
    description: 'See yourself at different ages',
    category: TEMPLATE_CATEGORIES.PORTRAIT,
    icon: '⏳',
    outputType: 'image',
    model: 'flux-kontext-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Age instruction', placeholder: 'e.g. 20 years older' },
    ],
    defaultParams: { name: 'Age Progression' },
  },
  {
    id: 'younger-self',
    name: 'Younger Self',
    description: 'Travel back in time with a younger selfie',
    category: TEMPLATE_CATEGORIES.PORTRAIT,
    icon: '👶',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Memory style', placeholder: 'e.g. nostalgic summer day' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Younger Self Selfie', resolution: '720p', duration: 5 },
  },
  {
    id: 'fashion-stride',
    name: 'Fashion Stride',
    description: 'Runway model walk animation',
    category: TEMPLATE_CATEGORIES.PORTRAIT,
    icon: '👠',
    outputType: 'video',
    model: 'video-effects',
    modelType: 'i2v',
    aspectRatio: '9:16',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. high fashion runway walk' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['9:16', '16:9', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Fashion Stride' },
  },
  {
    id: 'glamour-portrait',
    name: 'Glamour Portrait',
    description: 'Hollywood glamour photo enhancement',
    category: TEMPLATE_CATEGORIES.PORTRAIT,
    icon: '💎',
    outputType: 'video',
    model: 'ai-video-effects',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Style', placeholder: 'e.g. red carpet glamour' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Glamor', resolution: '720p', duration: 5 },
  },
  {
    id: '1920s-style',
    name: '1920s Style',
    description: 'Roaring twenties art deco aesthetic',
    category: TEMPLATE_CATEGORIES.DECADE,
    icon: '🎩',
    outputType: 'image',
    model: 'nano-banana-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. art deco style, jazz age aesthetic' },
    ],
    defaultParams: { name: '1920s Decade' },
  },
  {
    id: '1950s-style',
    name: '1950s Style',
    description: 'Mid-century Americana nostalgia',
    category: TEMPLATE_CATEGORIES.DECADE,
    icon: '🚗',
    outputType: 'image',
    model: 'nano-banana-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. vintage diner, rockabilly style' },
    ],
    defaultParams: { name: '1950s Decade' },
  },
  {
    id: '1970s-style',
    name: '1970s Style',
    description: 'Groovy seventies retro vibes',
    category: TEMPLATE_CATEGORIES.DECADE,
    icon: '🕺',
    outputType: 'image',
    model: 'nano-banana-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. disco aesthetic, hippie vibe' },
    ],
    defaultParams: { name: '1970s Decade' },
  },
  {
    id: '1980s-style',
    name: '1980s Style',
    description: 'Neon-lit synthwave eighties look',
    category: TEMPLATE_CATEGORIES.DECADE,
    icon: '🎸',
    outputType: 'image',
    model: 'nano-banana-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. synthwave, neon lights, Miami Vice style' },
    ],
    defaultParams: { name: '1980s Decade' },
  },
  {
    id: 'drone-fpv',
    name: 'Drone FPV Shot',
    description: 'First-person drone flythrough footage',
    category: TEMPLATE_CATEGORIES.CAMERA,
    icon: '🛸',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload landscape or scene' },
      { name: 'prompt', type: 'text', label: 'Flight path', placeholder: 'e.g. through a forest canopy' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'FPV Drone Cam', resolution: '720p', duration: 5 },
  },
  {
    id: 'dolly-zoom',
    name: 'Dolly Zoom',
    description: 'Hitchcock vertigo zoom effect',
    category: TEMPLATE_CATEGORIES.CAMERA,
    icon: '🔭',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Scene description', placeholder: 'e.g. dramatic hallway reveal' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Dolly Zoom In', resolution: '720p', duration: 5 },
  },
  {
    id: 'car-chase',
    name: 'Car Chase Scene',
    description: 'Action movie car chase footage',
    category: TEMPLATE_CATEGORIES.CAMERA,
    icon: '🏎️',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload car or street photo' },
      { name: 'prompt', type: 'text', label: 'Chase description', placeholder: 'e.g. high speed through city streets' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Car Chase', resolution: '720p', duration: 5 },
  },
  {
    id: 'matrix-shot',
    name: 'Matrix Shot',
    description: 'Frozen-time multi-angle camera rotation',
    category: TEMPLATE_CATEGORIES.CAMERA,
    icon: '🕶️',
    outputType: 'video',
    model: 'motion-controls',
    modelType: 'i2v',
    aspectRatio: '16:9',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Action', placeholder: 'e.g. mid-air jump kick' },
      { name: 'aspect_ratio', type: 'select', label: 'Aspect Ratio', options: ['16:9', '9:16', '1:1', '4:3', '3:4'] },
      { name: 'duration', type: 'select', label: 'Duration', options: ['5', '8', '10'] },
    ],
    defaultParams: { name: 'Matrix Shot', resolution: '720p', duration: 5 },
  },
  {
    id: '3d-figurine',
    name: '3D Figurine',
    description: 'Turn yourself into a collectible 3D figure',
    category: TEMPLATE_CATEGORIES.ENTERTAINMENT,
    icon: '🗿',
    outputType: 'image',
    model: 'nano-banana-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. collectible toy style, detailed paint finish' },
    ],
    defaultParams: { name: '3D Figurine' },
  },
  {
    id: 'glass-ball',
    name: 'Glass Ball',
    description: 'Scene captured inside a crystal glass ball',
    category: TEMPLATE_CATEGORIES.STYLE,
    icon: '🔮',
    outputType: 'image',
    model: 'image-effects',
    modelType: 'i2i',
    inputs: [
      { name: 'image_url', type: 'image', label: 'Upload your photo' },
      { name: 'prompt', type: 'text', label: 'Description', placeholder: 'e.g. magical crystal ball, winter snow scene' },
    ],
    defaultParams: { name: 'Glass Ball' },
  },
];

// Combine all templates including niche templates and matrix templates
export const allTemplates = [...templates, ...ALL_NICHE_TEMPLATES, ...MATRIX_TEMPLATES];

export function getTemplateById(id) {
  return allTemplates.find(t => t.id === id);
}

export function getTemplatesByCategory(category) {
  return allTemplates.filter(t => t.category === category);
}

export function getAllCategories() {
  return [...new Set(allTemplates.map(t => t.category))];
}

export { ALL_NICHE_TEMPLATES, RESTAURANT_TEMPLATES, MED_SPA_TEMPLATES, SALON_TEMPLATES, FITNESS_TEMPLATES, REAL_ESTATE_TEMPLATES, DENTAL_TEMPLATES, CHIROPRACTIC_TEMPLATES, LEGAL_TEMPLATES, AUTOMOTIVE_TEMPLATES, FASHION_TEMPLATES, EVENT_TEMPLATES, LUXURY_TEMPLATES, MATRIX_TEMPLATES };
