// Common web fonts for text elements
export default [
  'Arial',
  'Helvetica',
  'Times New Roman',
  'Times',
  'Courier New',
  'Courier',
  'Verdana',
  'Georgia',
  'Palatino',
  'Garamond',
  'Bookman',
  'Comic Sans MS',
  'Trebuchet MS',
  'Arial Black',
  'Impact',
  'Lucida Sans Unicode',
  'Lucida Grande',
  'Tahoma',
  'Geneva',
  'Anton', // Default font
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Poppins',
  'Nunito',
  'Inter',
  'Work Sans',
  'Fira Sans',
  'Source Sans Pro',
];