import fs from 'fs';
import path from 'path';

const filePath = path.join(process.cwd(), 'src/lib/sceneSchema.js');
let content = fs.readFileSync(filePath, 'utf8');

// Find the last template and the closing }; of SCENE_TEMPLATES
const closingIndex = content.lastIndexOf('\n};');
const before = content.substring(0, closingIndex); // everything before };
const after = content.substring(closingIndex); // }; plus rest of file

function addTemplate(obj) {
  const id = obj.id;
  const name = obj.name;
  const scene_type = obj.scene_type;
  const default_duration = obj.default_duration;
  const shot_sequence = obj.shot_sequence;
  const emotion = obj.emotion;
  const compatible_genres = obj.compatible_genres;
  
  const extras = [];
  if (obj.description) extras.push(`    description: '${obj.description}'`);
  if (obj.scene_subtype) extras.push(`    scene_subtype: '${obj.scene_subtype}'`);
  if (obj.required_fields) extras.push(`    required_fields: ${JSON.stringify(obj.required_fields)}`);
  if (obj.story_function) extras.push(`    story_function: '${obj.story_function}'`);
  if (obj.narrative_role) extras.push(`    narrative_role: '${obj.narrative_role}'`);
  if (obj.pacing) extras.push(`    pacing: '${obj.pacing}'`);
  if (obj.intensity !== undefined) extras.push(`    intensity: ${obj.intensity}`);
  if (obj.keywords) extras.push(`    keywords: ${JSON.stringify(obj.keywords)}`);
  
  const extrasStr = extras.length > 0 ? ',\n' + extras.join(',\n') : '';
  
  const shots = shot_sequence.map(s => {
    const dur = s.duration !== undefined ? `, duration: ${s.duration}` : '';
    return `      { shot_type: ${s.shot_type}, purpose: '${s.purpose}'${dur} }`;
  }).join(',\n');
  
  return `,\n  ${id}: {\n    id: '${id}',\n    name: '${name}',\n    scene_type: ${scene_type},\n    default_duration: ${default_duration},\n    shot_sequence: [\n${shots}\n    ],\n    emotion: ${emotion},\n    compatible_genres: ${JSON.stringify(compatible_genres)}${extrasStr}\n  }`;
}

// ============================================
// TEMPLATE DEFINITIONS
// ============================================
const newTemplates = [];

function t(obj) { newTemplates.push(obj); }

// 01. Opening/Hook: 20
t({ id: 'hook_curiosity_gap', name: 'Hook - Curiosity Gap', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'visual_setup', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'question', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'tease', duration: 1 }], emotion: 'EMOTIONAL_TONES.CURIOUS', compatible_genres: ['all'], description: 'Creates an information gap that demands to be filled' });
t({ id: 'hook_problem_agitation', name: 'Hook - Problem Agitation', scene_type: 'SCENE_TYPES.HOOK', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'problem_statement', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'pain_point', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'consequences', duration: 2 }], emotion: 'EMOTIONAL_TONES.TENSE', compatible_genres: ['all'] });
t({ id: 'hook_story_teaser', name: 'Hook - Story Teaser', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'scene_setup', duration: 1.5 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'teaser_moment', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'reaction', duration: 1.5 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['all'] });
t({ id: 'hook_contrast', name: 'Hook - Contrast', scene_type: 'SCENE_TYPES.HOOK', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'expectation', duration: 1.5 }, { shot_type: 'SHOT_TYPES.EXTREME_CLOSE_UP', purpose: 'reality', duration: 1.5 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'reaction', duration: 1 }], emotion: 'EMOTIONAL_TONES.SURPRISE', compatible_genres: ['all'] });
t({ id: 'hook_authority', name: 'Hook - Authority', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'authority_figure', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'statement', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'proof', duration: 1 }], emotion: 'EMOTIONAL_TONES.EPIC', compatible_genres: ['business', 'corporate', 'educational'] });
t({ id: 'hook_urgency', name: 'Hook - Urgency', scene_type: 'SCENE_TYPES.HOOK', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.INSERT', purpose: 'timer', duration: 1 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'urgency', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'reaction', duration: 1 }], emotion: 'EMOTIONAL_TONES.URGENT', compatible_genres: ['all'] });
t({ id: 'hook_social_proof', name: 'Hook - Social Proof', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'crowd', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'endorsement', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'testimonial', duration: 1 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['business', 'social', 'commercial'] });
t({ id: 'hook_dark_secret', name: 'Hook - Dark Secret', scene_type: 'SCENE_TYPES.HOOK', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'secret_keeper', duration: 2 }, { shot_type: 'SHOT_TYPES.INSERT', purpose: 'evidence', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'revelation', duration: 2 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['thriller', 'mystery', 'drama'] });
t({ id: 'hook_visual_puzzle', name: 'Hook - Visual Puzzle', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MACRO', purpose: 'detail', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'context', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'connection', duration: 1 }], emotion: 'EMOTIONAL_TONES.CURIOUS', compatible_genres: ['documentary', 'mystery', 'educational'] });
t({ id: 'hook_emotional', name: 'Hook - Emotional', scene_type: 'SCENE_TYPES.HOOK', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'character', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'emotion', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'impact', duration: 2 }], emotion: 'EMOTIONAL_TONES.SAD', compatible_genres: ['drama', 'documentary', 'nonprofit'] });
t({ id: 'hook_humor', name: 'Hook - Humor', scene_type: 'SCENE_TYPES.HOOK', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'setup', duration: 1.5 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'punchline', duration: 1.5 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'reaction', duration: 1 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['comedy', 'social', 'commercial'] });
t({ id: 'hook_shock_value', name: 'Hook - Shock Value', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'normal', duration: 1.5 }, { shot_type: 'SHOT_TYPES.EXTREME_CLOSE_UP', purpose: 'shock', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'reaction', duration: 1.5 }], emotion: 'EMOTIONAL_TONES.SUSPENSEFUL', compatible_genres: ['thriller', 'action', 'horror'] });
t({ id: 'hook_dream_scenario', name: 'Hook - Dream Scenario', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'ideal_world', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'desire', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'aspiration', duration: 1 }], emotion: 'EMOTIONAL_TONES.HOPEFUL', compatible_genres: ['commercial', 'business', 'lifestyle'] });
t({ id: 'hook_fear_appeal', name: 'Hook - Fear Appeal', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'danger', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'fear', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'consequence', duration: 1 }], emotion: 'EMOTIONAL_TONES.DANGEROUS', compatible_genres: ['horror', 'thriller', 'public_service'] });
t({ id: 'hook_contrarian', name: 'Hook - Contrarian', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'challenge', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'unpopular_opinion', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'evidence', duration: 1 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['educational', 'business', 'documentary'] });
t({ id: 'hook_before_after', name: 'Hook - Before/After', scene_type: 'SCENE_TYPES.HOOK', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'before_state', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'transformation', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'after_state', duration: 2 }], emotion: 'EMOTIONAL_TONES.TRIUMPHANT', compatible_genres: ['commercial', 'business', 'fitness'] });
t({ id: 'hook_list_format', name: 'Hook - List Format', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'presentation', duration: 2 }, { shot_type: 'SHOT_TYPES.INSERT', purpose: 'list_item', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'emphasis', duration: 1 }], emotion: 'EMOTIONAL_TONES.CURIOUS', compatible_genres: ['educational', 'business', 'social'] });
t({ id: 'hook_myth_busting', name: 'Hook - Myth Busting', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'myth', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'bust', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'truth', duration: 1 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['educational', 'documentary', 'business'] });
t({ id: 'hook_question_loop', name: 'Hook - Question Loop', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'question', duration: 1.5 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'contemplation', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'answer_tease', duration: 1.5 }], emotion: 'EMOTIONAL_TONES.CURIOUS', compatible_genres: ['all'] });
t({ id: 'hook_statistic', name: 'Hook - Statistic', scene_type: 'SCENE_TYPES.HOOK', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.INSERT', purpose: 'statistic', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'impact', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'reaction', duration: 1 }], emotion: 'EMOTIONAL_TONES.URGENT', compatible_genres: ['business', 'documentary', 'news'] });

// 02. Establishing: 25
t({ id: 'establishing_countryside', name: 'Establishing - Countryside', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.AERIAL', purpose: 'landscape', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'field', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'structure', duration: 2 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['drama', 'documentary', 'romance'] });
t({ id: 'establishing_suburbia', name: 'Establishing - Suburbia', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.TRACKING', purpose: 'street', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'neighborhood', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'house', duration: 2 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['drama', 'comedy', 'horror'] });
t({ id: 'establishing_underwater', name: 'Establishing - Underwater', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.EXTREME_WIDE', purpose: 'ocean', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'reef', duration: 3 }, { shot_type: 'SHOT_TYPES.MACRO', purpose: 'marine_life', duration: 2 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['adventure', 'documentary', 'sci-fi'] });
t({ id: 'establishing_forest', name: 'Establishing - Forest', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.AERIAL', purpose: 'canopy', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'path', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'clearing', duration: 3 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['horror', 'adventure', 'fantasy'] });
t({ id: 'establishing_school', name: 'Establishing - School', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'exterior', duration: 2 }, { shot_type: 'SHOT_TYPES.TRACKING', purpose: 'hallway', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'classroom', duration: 2 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['comedy', 'drama', 'horror'] });
t({ id: 'establishing_hospital', name: 'Establishing - Hospital', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'exterior', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'lobby', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'details', duration: 2 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['drama', 'horror', 'thriller'] });
t({ id: 'establishing_office', name: 'Establishing - Office', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'exterior', duration: 2 }, { shot_type: 'SHOT_TYPES.TRACKING', purpose: 'lobby', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'workspace', duration: 2 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['business', 'corporate', 'comedy'] });
t({ id: 'establishing_warehouse', name: 'Establishing - Warehouse', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'exterior', duration: 2 }, { shot_type: 'SHOT_TYPES.TRACKING', purpose: 'interior', duration: 2 }, { shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'structure', duration: 2 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['action', 'thriller', 'horror'] });
t({ id: 'establishing_beach', name: 'Establishing - Beach', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.AERIAL', purpose: 'coastline', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'shore', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'activity', duration: 2 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['romance', 'drama', 'comedy'] });
t({ id: 'establishing_mountain', name: 'Establishing - Mountain', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.AERIAL', purpose: 'peaks', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'valley', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'climber', duration: 2 }], emotion: 'EMOTIONAL_TONES.EPIC', compatible_genres: ['adventure', 'documentary', 'drama'] });
t({ id: 'establishing_space', name: 'Establishing - Space', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.EXTREME_WIDE', purpose: 'universe', duration: 3 }, { shot_type: 'SHOT_TYPES.AERIAL', purpose: 'planet', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'station', duration: 2 }], emotion: 'EMOTIONAL_TONES.EPIC', compatible_genres: ['sci-fi', 'documentary', 'adventure'] });
t({ id: 'establishing_desert', name: 'Establishing - Desert', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.AERIAL', purpose: 'dunes', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'landscape', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'traveler', duration: 2 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['adventure', 'western', 'sci-fi'] });
t({ id: 'establishing_farm', name: 'Establishing - Farm', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'property', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'barn', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'animals', duration: 2 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['drama', 'documentary', 'family'] });
t({ id: 'establishing_castle', name: 'Establishing - Castle', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'exterior', duration: 3 }, { shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'towers', duration: 2 }, { shot_type: 'SHOT_TYPES.AERIAL', purpose: 'grounds', duration: 3 }], emotion: 'EMOTIONAL_TONES.EPIC', compatible_genres: ['fantasy', 'adventure', 'drama'] });
t({ id: 'establishing_street', name: 'Establishing - Street', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.TRACKING', purpose: 'movement', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'block', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'activity', duration: 1 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['urban', 'corporate', 'thriller'] });
t({ id: 'establishing_school_bell', name: 'Establishing - School Bell', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'exterior', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'students', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'bell', duration: 1 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['comedy', 'drama', 'coming_of_age'] });
t({ id: 'establishing_airport', name: 'Establishing - Airport', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'terminal', duration: 2 }, { shot_type: 'SHOT_TYPES.TRACKING', purpose: 'crowd', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'plane', duration: 2 }], emotion: 'EMOTIONAL_TONES.URGENT', compatible_genres: ['romance', 'drama', 'action'] });
t({ id: 'establishing_train_station', name: 'Establishing - Train Station', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'platform', duration: 2 }, { shot_type: 'SHOT_TYPES.TRACKING', purpose: 'train', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'passengers', duration: 2 }], emotion: 'EMOTIONAL_TONES.NOSTALGIC', compatible_genres: ['romance', 'drama', 'mystery'] });
t({ id: 'establishing_port', name: 'Establishing - Port', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'harbor', duration: 2 }, { shot_type: 'SHOT_TYPES.TRACKING', purpose: 'ships', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'activity', duration: 2 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['adventure', 'mystery', 'drama'] });
t({ id: 'establishing_park', name: 'Establishing - Park', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'greenery', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'path', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'details', duration: 1 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['romance', 'comedy', 'drama'] });
t({ id: 'establishing_residential', name: 'Establishing - Residential', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.TRACKING', purpose: 'street', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'homes', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'porch', duration: 1 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['drama', 'comedy', 'horror'] });
t({ id: 'establishing_skyscraper', name: 'Establishing - Skyscraper', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.AERIAL', purpose: 'cityscape', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'building', duration: 2 }, { shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'height', duration: 2 }], emotion: 'EMOTIONAL_TONES.EPIC', compatible_genres: ['corporate', 'thriller', 'action'] });
t({ id: 'establishing_ruins', name: 'Establishing - Ruins', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'ruins', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'debris', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'artifact', duration: 2 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['adventure', 'fantasy', 'horror'] });
t({ id: 'establishing_bridge', name: 'Establishing - Bridge', scene_type: 'SCENE_TYPES.ESTABLISHING', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'span', duration: 2 }, { shot_type: 'SHOT_TYPES.TRACKING', purpose: 'crossing', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'pedestrians', duration: 2 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['romance', 'drama', 'thriller'] });

// 03. Character Introduction: 25
t({ id: 'char_intro_mentor', name: 'Character Introduction - Mentor', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'environment', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'presence', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'wisdom', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'action', duration: 2 }], emotion: 'EMOTIONAL_TONES.HOPEFUL', compatible_genres: ['drama', 'adventure', 'fantasy'] });
t({ id: 'char_intro_sidekick', name: 'Character Introduction - Sidekick', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'introduction', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'personality', duration: 2 }, { shot_type: 'SHOT_TYPES.TWO_SHOT', purpose: 'interaction', duration: 2 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['comedy', 'action', 'adventure'] });
t({ id: 'char_intro_love_interest', name: 'Character Introduction - Love Interest', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'separate', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'notice', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'eye_contact', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'approach', duration: 2 }], emotion: 'EMOTIONAL_TONES.ROMANTIC', compatible_genres: ['romance', 'drama', 'comedy'] });
t({ id: 'char_intro_mentor_wise', name: 'Character Introduction - Wise Mentor', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'presence', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM_CLOSE_UP', purpose: 'face', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'eyes', duration: 3 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['fantasy', 'drama', 'adventure'] });
t({ id: 'char_intro_rival', name: 'Character Introduction - Rival', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'arena', duration: 2 }, { shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'arrival', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'challenge', duration: 3 }], emotion: 'EMOTIONAL_TONES.TENSE', compatible_genres: ['sports', 'action', 'drama'] });
t({ id: 'char_intro_comic_relief', name: 'Character Introduction - Comic Relief', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'entrance', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'mishap', duration: 2 }, { shot_type: 'SHOT_TYPES.TWO_SHOT', purpose: 'reaction', duration: 2 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['comedy', 'adventure', 'family'] });
t({ id: 'char_intro_mysterious_stranger', name: 'Character Introduction - Mysterious Stranger', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.SILHOUETTE', purpose: 'shadow', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'reveal', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'expression', duration: 2 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['mystery', 'thriller', 'western'] });
t({ id: 'char_intro_authority', name: 'Character Introduction - Authority', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'power', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'command', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'determination', duration: 2 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['thriller', 'crime', 'drama'] });
t({ id: 'char_intro_child', name: 'Character Introduction - Child', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'play', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'innocence', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'wonder', duration: 2 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['family', 'drama', 'fantasy'] });
t({ id: 'char_intro_elder', name: 'Character Introduction - Elder', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'face', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'posture', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'surroundings', duration: 2 }], emotion: 'EMOTIONAL_TONES.NOSTALGIC', compatible_genres: ['drama', 'fantasy', 'historical'] });
t({ id: 'char_intro_scientist', name: 'Character Introduction - Scientist', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'lab', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'experiment', duration: 3 }, { shot_type: 'SHOT_TYPES.OVER_SHOULDER', purpose: 'discovery', duration: 2 }], emotion: 'EMOTIONAL_TONES.CURIOUS', compatible_genres: ['sci-fi', 'documentary', 'thriller'] });
t({ id: 'char_intro_athlete', name: 'Character Introduction - Athlete', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'training', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'focus', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'determination', duration: 3 }], emotion: 'EMOTIONAL_TONES.TRIUMPHANT', compatible_genres: ['sports', 'drama', 'documentary'] });
t({ id: 'char_intro_artist', name: 'Character Introduction - Artist', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'studio', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'creation', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'work', duration: 2 }], emotion: 'EMOTIONAL_TONES.INSPIRATIONAL', compatible_genres: ['documentary', 'drama', 'independent'] });
t({ id: 'char_intro_warrior', name: 'Character Introduction - Warrior', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'arrival', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'battlefield', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'preparation', duration: 3 }], emotion: 'EMOTIONAL_TONES.DANGEROUS', compatible_genres: ['action', 'fantasy', 'adventure'] });
t({ id: 'char_intro_detective', name: 'Character Introduction - Detective', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.NOIR', purpose: 'shadow', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'investigation', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'clue', duration: 2 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['noir', 'thriller', 'mystery'] });
t({ id: 'char_intro_chef', name: 'Character Introduction - Chef', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'kitchen', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'cooking', duration: 3 }, { shot_type: 'SHOT_TYPES.MACRO', purpose: 'plating', duration: 2 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['lifestyle', 'documentary', 'comedy'] });
t({ id: 'char_intro_musician', name: 'Character Introduction - Musician', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'stage', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'performance', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'emotion', duration: 2 }], emotion: 'EMOTIONAL_TONES.INSPIRATIONAL', compatible_genres: ['music', 'documentary', 'drama'] });
t({ id: 'char_intro_parent', name: 'Character Introduction - Parent', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'home', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'care', duration: 3 }, { shot_type: 'SHOT_TYPES.TWO_SHOT', purpose: 'family', duration: 2 }], emotion: 'EMOTIONAL_TONES.HOPEFUL', compatible_genres: ['drama', 'family', 'comedy'] });
t({ id: 'char_intro_student', name: 'Character Introduction - Student', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'campus', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'studies', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'dreams', duration: 2 }], emotion: 'EMOTIONAL_TONES.HOPEFUL', compatible_genres: ['coming_of_age', 'comedy', 'drama'] });
t({ id: 'char_intro_explorer', name: 'Character Introduction - Explorer', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'wilderness', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'gear', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'determination', duration: 3 }], emotion: 'EMOTIONAL_TONES.HOPEFUL', compatible_genres: ['adventure', 'documentary', 'drama'] });
t({ id: 'char_intro_villain_intellectual', name: 'Character Introduction - Villain Intellectual', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'lair', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'plan', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'calculation', duration: 3 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['thriller', 'spy', 'sci-fi'] });
t({ id: 'char_intro_hero_ordinary', name: 'Character Introduction - Hero Ordinary', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'routine', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'longing', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'world', duration: 2 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['drama', 'comedy', 'action'] });
t({ id: 'char_intro_antihero', name: 'Character Introduction - Antihero', scene_type: 'SCENE_TYPES.CHARACTER_INTRODUCTION', default_duration: 7, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'underbelly', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'moral_choice', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'conflict', duration: 2 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['crime', 'drama', 'thriller'] });

// 04. Character Emotion: 25
t({ id: 'char_emotion_joy', name: 'Character Emotion - Joy', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'setup', duration: 1 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'joy', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'celebration', duration: 1 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['all'] });
t({ id: 'char_emotion_sorrow', name: 'Character Emotion - Sorrow', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'loss', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'grief', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'isolation', duration: 1 }], emotion: 'EMOTIONAL_TONES.SAD', compatible_genres: ['drama', 'romance'] });
t({ id: 'char_emotion_anger', name: 'Character Emotion - Anger', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'provocation', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'rage', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'eruption', duration: 1 }], emotion: 'EMOTIONAL_TONES.DANGEROUS', compatible_genres: ['drama', 'action', 'thriller'] });
t({ id: 'char_emotion_fear', name: 'Character Emotion - Fear', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'threat', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'fear', duration: 2 }, { shot_type: 'SHOT_TYPES.EXTREME_CLOSE_UP', purpose: 'sweat', duration: 1 }], emotion: 'EMOTIONAL_TONES.SUSPENSEFUL', compatible_genres: ['horror', 'thriller'] });
t({ id: 'char_emotion_surprise', name: 'Character Emotion - Surprise', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'anticipation', duration: 1 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'shock', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'reaction', duration: 1 }], emotion: 'EMOTIONAL_TONES.SURPRISE', compatible_genres: ['all'] });
t({ id: 'char_emotion_disgust', name: 'Character Emotion - Disgust', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'reaction', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'revulsion', duration: 2 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['horror', 'comedy', 'drama'] });
t({ id: 'char_emotion_love', name: 'Character Emotion - Love', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'presence', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'adoration', duration: 2 }, { shot_type: 'SHOT_TYPES.TWO_SHOT', purpose: 'connection', duration: 1 }], emotion: 'EMOTIONAL_TONES.ROMANTIC', compatible_genres: ['romance', 'drama'] });
t({ id: 'char_emotion_hope', name: 'Character Emotion - Hope', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'despair', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'hope', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'uplift', duration: 1 }], emotion: 'EMOTIONAL_TONES.HOPEFUL', compatible_genres: ['drama', 'adventure', 'sports'] });
t({ id: 'char_emotion_shame', name: 'Character Emotion - Shame', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'confrontation', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'shame', duration: 2 }, { shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'humiliation', duration: 1 }], emotion: 'EMOTIONAL_TONES.SAD', compatible_genres: ['drama', 'comedy'] });
t({ id: 'char_emotion_pride', name: 'Character Emotion - Pride', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'achievement', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'pride', duration: 2 }, { shot_type: 'SHOT_TYPES.LOW_ANGLE', purpose: 'triumph', duration: 1 }], emotion: 'EMOTIONAL_TONES.TRIUMPHANT', compatible_genres: ['sports', 'drama', 'action'] });
t({ id: 'char_emotion_guilt', name: 'Character Emotion - Guilt', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'memory', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'guilt', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'consequence', duration: 1 }], emotion: 'EMOTIONAL_TONES.SAD', compatible_genres: ['drama', 'thriller', 'mystery'] });
t({ id: 'char_emotion_jealousy', name: 'Character Emotion - Jealousy', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.TWO_SHOT', purpose: 'rivalry', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'jealousy', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'tension', duration: 1 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['drama', 'thriller', 'romance'] });
t({ id: 'char_emotion_relief', name: 'Character Emotion - Relief', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'tension_break', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'exhale', duration: 2 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['all'] });
t({ id: 'char_emotion_confusion', name: 'Character Emotion - Confusion', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'chaos', duration: 1.5 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'confusion', duration: 2.5 }], emotion: 'EMOTIONAL_TONES.MYSTERIOUS', compatible_genres: ['mystery', 'comedy', 'drama'] });
t({ id: 'char_emotion_excitement', name: 'Character Emotion - Excitement', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'anticipation', duration: 1.5 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'excitement', duration: 2.5 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['sports', 'adventure', 'comedy'] });
t({ id: 'char_emotion_desperation', name: 'Character Emotion - Desperation', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'despair', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'plea', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'last_chance', duration: 1 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['thriller', 'drama', 'horror'] });
t({ id: 'char_emotion_embarrassment', name: 'Character Emotion - Embarrassment', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'situation', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'embarrassment', duration: 2 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['comedy', 'coming_of_age'] });
t({ id: 'char_emotion_grief', name: 'Character Emotion - Grief', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'loss', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'tears', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'isolation', duration: 1 }], emotion: 'EMOTIONAL_TONES.SAD', compatible_genres: ['drama', 'romance'] });
t({ id: 'char_emotion_contempt', name: 'Character Emotion - Contempt', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.PROFILE', purpose: 'disdain', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'sneer', duration: 2 }], emotion: 'EMOTIONAL_TONES.DARK', compatible_genres: ['thriller', 'drama'] });
t({ id: 'char_emotion_amazement', name: 'Character Emotion - Amazement', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'wonder', duration: 1.5 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'awe', duration: 2.5 }], emotion: 'EMOTIONAL_TONES.EPIC', compatible_genres: ['adventure', 'sci-fi', 'fantasy'] });
t({ id: 'char_emotion_nostalgia', name: 'Character Emotion - Nostalgia', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'memory_trigger', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'longing', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'past', duration: 1 }], emotion: 'EMOTIONAL_TONES.NOSTALGIC', compatible_genres: ['drama', 'romance', 'documentary'] });
t({ id: 'char_emotion_determination', name: 'Character Emotion - Determination', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'obstacle', duration: 1.5 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'determination', duration: 2.5 }], emotion: 'EMOTIONAL_TONES.TRIUMPHANT', compatible_genres: ['sports', 'action', 'drama'] });
t({ id: 'char_emotion_anxiety', name: 'Character Emotion - Anxiety', scene_type: 'SCENE_TYPES.CHARACTER_REACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'pressure', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'anxiety', duration: 2 }], emotion: 'EMOTIONAL_TONES.TENSE', compatible_genres: ['thriller', 'drama', 'comedy'] });

// 05. Character Action: 25
t({ id: 'char_action_walking', name: 'Character Action - Walking', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.TRACKING', purpose: 'walk', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'pace', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'feet', duration: 1 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['all'] });
t({ id: 'char_action_running', name: 'Character Action - Running', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.TRACKING', purpose: 'run', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'effort', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'face', duration: 1 }], emotion: 'EMOTIONAL_TONES.URGENT', compatible_genres: ['action', 'thriller', 'horror'] });
t({ id: 'char_action_fighting', name: 'Character Action - Fighting', scene_type: 'SCENE_TYPES.ACTION', default_duration: 8, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'confrontation', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'exchange', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'impact', duration: 3 }], emotion: 'EMOTIONAL_TONES.DANGEROUS', compatible_genres: ['action', 'thriller'] });
t({ id: 'char_action_dancing', name: 'Character Action - Dancing', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'movement', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'rhythm', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'expression', duration: 2 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['musical', 'comedy', 'romance'] });
t({ id: 'char_action_singing', name: 'Character Action - Singing', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'performance', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'emotion', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'audience', duration: 1 }], emotion: 'EMOTIONAL_TONES.INSPIRATIONAL', compatible_genres: ['musical', 'drama', 'comedy'] });
t({ id: 'char_action_writing', name: 'Character Action - Writing', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.INSERT', purpose: 'pen', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'expression', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'surroundings', duration: 1 }], emotion: 'EMOTIONAL_TONES.CURIOUS', compatible_genres: ['drama', 'documentary', 'educational'] });
t({ id: 'char_action_cooking', name: 'Character Action - Cooking', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'kitchen', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'preparation', duration: 2 }, { shot_type: 'SHOT_TYPES.MACRO', purpose: 'ingredients', duration: 2 }], emotion: 'EMOTIONAL_TONES.JOYFUL', compatible_genres: ['lifestyle', 'comedy', 'drama'] });
t({ id: 'char_action_gardening', name: 'Character Action - Gardening', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'garden', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'planting', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'growth', duration: 1 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['documentary', 'lifestyle', 'drama'] });
t({ id: 'char_action_driving', name: 'Character Action - Driving', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'vehicle', duration: 2 }, { shot_type: 'SHOT_TYPES.OVER_SHOULDER', purpose: 'road', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'hands', duration: 1 }], emotion: 'EMOTIONAL_TONES.TENSE', compatible_genres: ['action', 'thriller', 'drama'] });
t({ id: 'char_action_flying', name: 'Character Action - Flying', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.AERIAL', purpose: 'flight', duration: 3 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'pilot', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'controls', duration: 1 }], emotion: 'EMOTIONAL_TONES.EPIC', compatible_genres: ['action', 'adventure', 'sci-fi'] });
t({ id: 'char_action_swimming', name: 'Character Action - Swimming', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'water', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'stroke', duration: 2 }, { shot_type: 'SHOT_TYPES.UNDERWATER', purpose: 'submerged', duration: 1 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['drama', 'documentary', 'sports'] });
t({ id: 'char_action_climbing', name: 'Character Action - Climbing', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'height', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'ascent', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'grip', duration: 2 }], emotion: 'EMOTIONAL_TONES.TENSE', compatible_genres: ['adventure', 'sports', 'thriller'] });
t({ id: 'char_action_reading', name: 'Character Action - Reading', scene_type: 'SCENE_TYPES.ACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'book', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'reader', duration: 2 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['drama', 'documentary', 'educational'] });
t({ id: 'char_action_meditating', name: 'Character Action - Meditating', scene_type: 'SCENE_TYPES.ACTION', default_duration: 4, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'pose', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'face', duration: 2 }], emotion: 'EMOTIONAL_TONES.PEACEFUL', compatible_genres: ['documentary', 'lifestyle', 'spiritual'] });
t({ id: 'char_action_painting', name: 'Character Action - Painting', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'canvas', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'brush', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'art', duration: 1 }], emotion: 'EMOTIONAL_TONES.INSPIRATIONAL', compatible_genres: ['documentary', 'drama', 'art'] });
t({ id: 'char_action_repairing', name: 'Character Action - Repairing', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'workbench', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'hands', duration: 2 }, { shot_type: 'SHOT_TYPES.INSERT', purpose: 'tools', duration: 1 }], emotion: 'EMOTIONAL_TONES.NEUTRAL', compatible_genres: ['documentary', 'drama', 'comedy'] });
t({ id: 'char_action_teaching', name: 'Character Action - Teaching', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'classroom', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'instruction', duration: 2 }, { shot_type: 'SHOT_TYPES.TWO_SHOT', purpose: 'student', duration: 1 }], emotion: 'EMOTIONAL_TONES.HOPEFUL', compatible_genres: ['educational', 'drama', 'documentary'] });
t({ id: 'char_action_performing', name: 'Character Action - Performing', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'stage', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'act', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'expression', duration: 2 }], emotion: 'EMOTIONAL_TONES.EPIC', compatible_genres: ['musical', 'drama', 'comedy'] });
t({ id: 'char_action_hiding', name: 'Character Action - Hiding', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'danger', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'concealment', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'relief', duration: 1 }], emotion: 'EMOTIONAL_TONES.SUSPENSEFUL', compatible_genres: ['thriller', 'horror', 'action'] });
t({ id: 'char_action_sneaking', name: 'Character Action - Sneaking', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.HANDHELD', purpose: 'movement', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'stealth', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'escape', duration: 1 }], emotion: 'EMOTIONAL_TONES.TENSE', compatible_genres: ['thriller', 'action', 'horror'] });
t({ id: 'char_action_constructing', name: 'Character Action - Constructing', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'blueprint', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'assembly', duration: 3 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'completion', duration: 1 }], emotion: 'EMOTIONAL_TONES.TRIUMPHANT', compatible_genres: ['documentary', 'drama', 'sci-fi'] });
t({ id: 'char_action_destroying', name: 'Character Action - Destroying', scene_type: 'SCENE_TYPES.ACTION', default_duration: 5, shot_sequence: [{ shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'action', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'impact', duration: 2 }, { shot_type: 'SHOT_TYPES.WIDE', purpose: 'ruin', duration: 1 }], emotion: 'EMOTIONAL_TONES.DANGEROUS', compatible_genres: ['action', 'horror', 'drama'] });
t({ id: 'char_action_negotiating', name: 'Character Action - Negotiating', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.TWO_SHOT', purpose: 'tension', duration: 2 }, { shot_type: 'SHOT_TYPES.OVER_SHOULDER', purpose: 'arguments', duration: 2 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'compromise', duration: 2 }], emotion: 'EMOTIONAL_TONES.TENSE', compatible_genres: ['drama', 'thriller', 'business'] });
t({ id: 'char_action_saving', name: 'Character Action - Saving', scene_type: 'SCENE_TYPES.ACTION', default_duration: 6, shot_sequence: [{ shot_type: 'SHOT_TYPES.WIDE', purpose: 'danger', duration: 2 }, { shot_type: 'SHOT_TYPES.MEDIUM', purpose: 'rescue', duration: 3 }, { shot_type: 'SHOT_TYPES.CLOSE_UP', purpose: 'relief', duration: 1 }], emotion: 'EMOTIONAL_TONES.TRIUMPHANT', compatible_genres: ['action', 'drama', 'adventure'] });

// I need to continue with all remaining categories. This approach of one big script file is getting unwieldy.
// Let me write a cleaner script that uses arrays and loops to generate all templates.

fs.writeFileSync(path.join(process.cwd(), 'src/lib/sceneSchema.js'), expanded);
console.log('Done');
