import { TEMPLATE_RECIPES_02 } from "./02-ai-filmmaking";
import { TEMPLATE_RECIPES_03 } from "./03-faceless-ai-channels";
import { TEMPLATE_RECIPES_04 } from "./04-ai-content-factories";
import { TEMPLATE_RECIPES_05 } from "./05-ai-avatars-and-influencers";
import { TEMPLATE_RECIPES_06 } from "./06-ai-audio-and-music";
import { TEMPLATE_RECIPES_07 } from "./07-ai-product-photography";
import { TEMPLATE_RECIPES_08 } from "./08-ai-fashion-and-virtual-tryon";
import { TEMPLATE_RECIPES_09 } from "./09-ai-real-estate-staging";
import { TEMPLATE_RECIPES_10 } from "./10-ai-headshots-and-portraits";
import { TEMPLATE_RECIPES_11 } from "./11-ai-print-on-demand-and-merch";
import { TEMPLATE_RECIPES_12 } from "./12-ai-stock-content-and-licensing";
import { TEMPLATE_RECIPES_13 } from "./13-ai-tools-mastery";
import { TEMPLATE_RECIPES_14 } from "./14-ai-freelancing-and-agency-business";
import { TEMPLATE_RECIPES_15 } from "./15-ai-agents-and-vibe-coding";
import { getTemplateMeta } from "../catalog.ts";

const MAP: Record<string, string> = {
  ...TEMPLATE_RECIPES_02,   ...TEMPLATE_RECIPES_03,   ...TEMPLATE_RECIPES_04,   ...TEMPLATE_RECIPES_05,   ...TEMPLATE_RECIPES_06,
  ...TEMPLATE_RECIPES_07,   ...TEMPLATE_RECIPES_08,   ...TEMPLATE_RECIPES_09,   ...TEMPLATE_RECIPES_10,   ...TEMPLATE_RECIPES_11,
  ...TEMPLATE_RECIPES_12,   ...TEMPLATE_RECIPES_13,   ...TEMPLATE_RECIPES_14,   ...TEMPLATE_RECIPES_15, 
};

// Resolves the recipe id for an academy template. Prefers the curated
// per-track map (tracks 02-15) and falls back to the catalog meta recipeId
// (track 01 / UGC, generated by gen-academy-catalog.mjs).
export function getTemplateRecipeId(templateId: string): string | undefined {
  return MAP[templateId] ?? getTemplateMeta(templateId)?.recipeId;
}

export const TEMPLATE_RECIPE_MAP = MAP;
