export const RECIPES_14 = {
  '14-ai-freelancing-and-agency-business::case-study-portfolio-template': {
    id: '14-ai-freelancing-and-agency-business::case-study-portfolio-template',
    title: 'Build B2B Case Study',
    description: 'Generate a ROI-driven B2B commercial case study from the 4-part case study architecture.',
    category: '14-ai-freelancing-and-agency-business',
    target: 'commercial',
    icon: 'LineChart',
    buildPrompt(ctx = {}) {
      const client = (ctx.client || 'the client').toString().trim();
      return [
        `Produce a B2B commercial case study for: ${client}`,
        '',
        'Use this 4-part case study architecture to present a past AI agency project and close a high-ticket proposal:',
        '',
        '## CASE STUDY: [Client Company Name]',
        'PROJECT TITLE: [e.g., 24-Hour Remote Team Corporate Headshot Overhaul]',
        'INDUSTRY: [e.g., B2B SaaS / Enterprise Technology]',
        'CONTRACT VALUE: $ [Amount, e.g., $7,500.00]',
        '',
        '### 1. The Client Challenge',
        'Describe client baseline setup, previous traditional costs, slow turnaround timelines, and pain points.',
        '• Previous Traditional Shoot Quote: $28,500',
        '• Previous Production Timeline: 4 Weeks',
        '• Core Pain Point: distributed team making physical shoots impossible.',
        '',
        '### 2. The AI Agency Solution',
        'Detail the custom AI generation pipeline, model selection, identity locking, and quality control.',
        '• Pipeline: custom batch workflow with 1:1 facial geometry locking.',
        '• Inputs: smartphone selfies via automated form.',
        '• Post-Processing: upscaling to 4500x4500px @ 300 DPI print-ready masters.',
        '',
        '### 3. Quantifiable Business Metrics',
        'Table comparing Total Financial Cost, Delivery Speed, Employee Downtime, Usage Rights (traditional vs AI agency) with measurable impact.',
        '',
        '### 4. Client Testimonial & Interactive Proof',
        'Quote from client executive + a before/after interactive comparison slider (raw selfie -> 8k studio headshot).',
        '',
        'Style: client-facing, ROI-forward, confident, with concrete numbers and a before/after proof asset.',
      ].join('\n');
    },
  },

  '14-ai-freelancing-and-agency-business::outreach-and-discovery-script': {
    id: '14-ai-freelancing-and-agency-business::outreach-and-discovery-script',
    title: 'Build Outreach & Discovery Kit',
    description: 'Generate cold email sequences, a discovery call script, and objection-handling for closing $5k+ AI clients.',
    category: '14-ai-freelancing-and-agency-business',
    target: 'commercial',
    icon: 'Send',
    buildPrompt(ctx = {}) {
      const niche = (ctx.niche || 'remote tech teams needing corporate headshots').toString().trim();
      return [
        `Produce an outbound client-acquisition kit for the AI agency niche: ${niche}`,
        '',
        'Include the three tested components below:',
        '',
        '## 1. Outbound Cold Email Sequences',
        'Sequence A — B2B Corporate Headshots (Tech / Remote Teams): subject + opener referencing recent team growth, replace $25k physical shoots with 8k AI headshots from selfies in 24h, cite a similar-company result, end with a quick before/after demo ask.',
        'Sequence B — E-Commerce Apparel Renders & Ads: reference a recent launch, turn flat vector art into 8k lifestyle mockups + video ads without $15k model shoots, cite a 10->80 SKU catalog expansion, close with a prototype video render ask.',
        '',
        '## 2. The 20-Minute Sales Discovery Call Script',
        '0–3 min: Agenda & frame setting.',
        '3–10 min: Diagnostic questions (12-month shoot spend, booking-to-delivery time, biggest campaign bottleneck).',
        '10–15 min: Prototype demo & value anchor with before/after slider.',
        '15–20 min: The close with a specific package + 1-page SOW ask.',
        '',
        '## 3. Handling Live Client Objections',
        'Table mapping objection -> script response for: "Isn\'t AI media recognizable?", "Why not do this internally?", "Can you do it cheaper?"',
        '',
        'Style: direct, proof-led, ROI-anchored sales copy ready to send or speak.',
      ].join('\n');
    },
  },
};
