export const RECIPES_15 = {
  '15-ai-agents-and-vibe-coding::vibe-coding-session-brief': {
    id: '15-ai-agents-and-vibe-coding::vibe-coding-session-brief',
    title: 'Build Vibe-Coding Session Brief',
    description: 'Generate a pre-session brief that scopes a sellable micro-tool for a coding agent.',
    category: '15-ai-agents-and-vibe-coding',
    target: 'apps',
    icon: 'Code2',
    buildPrompt(ctx = {}) {
      const tool = (ctx.tool || 'a sellable micro-tool').toString().trim();
      return [
        `Plan a vibe-coding session to build: ${tool}`,
        '',
        'Use this session brief structure before opening the coding agent:',
        '',
        '## Session Details',
        'Date, Tool Name, Session Goal (e.g., build working v1.0 and verify on 10 inputs), Agent Platform (Claude Code / Cursor / Windsurf), Target Session Length.',
        '',
        '## Tool Specification',
        '• One-Sentence Description: [Tool] reads [INPUT] and produces [OUTPUT] by [TRANSFORMATION].',
        '• Input Definition: file name, format, example row.',
        '• Output Definition: file name, format/columns, example row.',
        '• Transformation: API/service used, API key storage, core prompt/logic.',
        '',
        '## Error Handling Rules',
        'Blank input lines, API rate limit/timeout (retry once, then log), invalid file format (clear error + exit).',
        '',
        '## Technical Constraints',
        'Allowed packages, Python version, output encoding (UTF-8), max input size.',
        '',
        '## Definition of Done (Phase 3 Test Checklist)',
        'Runs on real 10-row input; correct row count; exact output format; handles >=1 edge case; <60s for 50 rows; clear error messages.',
        '',
        '## Phase 4 — SHIP Checklist',
        'Generate README.md, requirements.txt, sample_input, sample_output, version tag v1.0.',
        '',
        'Output: a complete, unambiguous brief an agent can execute to ship a tested, packaged micro-tool.',
      ].join('\n');
    },
  },

  '15-ai-agents-and-vibe-coding::tool-scope-definition': {
    id: '15-ai-agents-and-vibe-coding::tool-scope-definition',
    title: 'Define Micro-Tool Scope',
    description: 'Generate a 4-question scope definition that prevents scope creep before building a micro-tool.',
    category: '15-ai-agents-and-vibe-coding',
    target: 'apps',
    icon: 'FileText',
    buildPrompt(ctx = {}) {
      const idea = (ctx.idea || 'an Etsy SEO title generator').toString().trim();
      return [
        `Define the scope for the micro-tool idea: ${idea}`,
        '',
        'Answer the 4 Scope Questions so the agent gets an unambiguous instruction:',
        '',
        '### 1. What is the exact input?',
        'File format, name, and example content (e.g., products.txt, one name per line).',
        '',
        '### 2. What is the exact output?',
        'File format, name, column structure, and example row (e.g., seo_titles.csv with ProductName,Title1,Title2,Keywords).',
        '',
        '### 3. What is the one transformation?',
        'The single operation converting input to output (e.g., per product send a fixed SEO API prompt, parse JSON, write CSV).',
        '',
        '### 4. Who is the exact buyer?',
        'Target buyer job, platform, and specific pain point (not "creators in general").',
        '',
        '## Tool Validation Checklist',
        'Does exactly one thing; concrete input; concrete output; specific buyer; real sample input ready.',
        '',
        '## Monetization Estimate',
        'Table: hours saved/month, buyer hourly rate, monthly value saved, suggested price (10% of value), break-even sales.',
        '',
        'Output: a tight scope doc an agent can build from with zero ambiguity.',
      ].join('\n');
    },
  },
};
