export const ANIMATION_TYPES = {
  IN: 'in',
  IDLE: 'idle',
  OUT: 'out',
};

export const ANIMATED_CLASS = 'animated';

export const INFINITE_CLASS = 'infinite';

export const NONE_CLASS = 'none';

export const animations = {
  [ANIMATION_TYPES.IN]: [
    { name: 'Bounce In', value: 'bounceIn' },
    { name: 'Bounce In Down', value: 'bounceInDown' },
    { name: 'Bounce In Left', value: 'bounceInLeft' },
    { name: 'Bounce In Right', value: 'bounceInRight' },
    { name: 'Bounce In Up', value: 'bounceInUp' },
    { name: 'Fade In', value: 'fadeIn' },
    { name: 'Fade In Down', value: 'fadeInDown' },
    { name: 'Fade In Down Big', value: 'fadeInDownBig' },
    { name: 'Fade In Left', value: 'fadeInLeft' },
    { name: 'Fade In Left Big', value: 'fadeInLeftBig' },
    { name: 'Fade In Right', value: 'fadeInRight' },
    { name: 'Fade In Right Big', value: 'fadeInRightBig' },
    { name: 'Fade In Up', value: 'fadeInUp' },
    { name: 'Fade In Up Big', value: 'fadeInUpBig' },
    { name: 'Flip In X', value: 'flipInX' },
    { name: 'Flip In Y', value: 'flipInY' },
    { name: 'Light Speed In', value: 'lightSpeedIn' },
    { name: 'Rotate In', value: 'rotateIn' },
    { name: 'Rotate In Down Left', value: 'rotateInDownLeft' },
    { name: 'Rotate In Down Right', value: 'rotateInDownRight' },
    { name: 'Rotate In Up Left', value: 'rotateInUpLeft' },
    { name: 'Rotate In Up Right', value: 'rotateInUpRight' },
    { name: 'Slide In Up', value: 'slideInUp' },
    { name: 'Slide In Down', value: 'slideInDown' },
    { name: 'Slide In Left', value: 'slideInLeft' },
    { name: 'Slide In Right', value: 'slideInRight' },
    { name: 'Zoom In', value: 'zoomIn' },
    { name: 'Zoom In Down', value: 'zoomInDown' },
    { name: 'Zoom In Left', value: 'zoomInLeft' },
    { name: 'Zoom In Right', value: 'zoomInRight' },
    { name: 'Zoom In Up', value: 'zoomInUp' },
    { name: 'Jack In The Box', value: 'jackInTheBox' },
    { name: 'Roll In', value: 'rollIn' },
  ],
  [ANIMATION_TYPES.OUT]: [
    { name: 'Bounce Out', value: 'bounceOut' },
    { name: 'Bounce Out Down', value: 'bounceOutDown' },
    { name: 'Bounce Out Left', value: 'bounceOutLeft' },
    { name: 'Bounce Out Right', value: 'bounceOutRight' },
    { name: 'Bounce Out Up', value: 'bounceOutUp' },
    { name: 'Fade Out', value: 'fadeOut' },
    { name: 'Fade Out Down', value: 'fadeOutDown' },
    { name: 'Fade Out Down Big', value: 'fadeOutDownBig' },
    { name: 'Fade Out Left', value: 'fadeOutLeft' },
    { name: 'Fade Out Left Big', value: 'fadeOutLeftBig' },
    { name: 'Fade Out Right', value: 'fadeOutRight' },
    { name: 'Fade Out Right Big', value: 'fadeOutRightBig' },
    { name: 'Fade Out Up', value: 'fadeOutUp' },
    { name: 'Fade Out Up Big', value: 'fadeOutUpBig' },
    { name: 'Flip Out X', value: 'flipOutX' },
    { name: 'Flip Out Y', value: 'flipOutY' },
    { name: 'Light Speed Out', value: 'lightSpeedOut' },
    { name: 'Rotate Out', value: 'rotateOut' },
    { name: 'Rotate Out Down Left', value: 'rotateOutDownLeft' },
    { name: 'Rotate Out Down Right', value: 'rotateOutDownRight' },
    { name: 'Rotate Out Up Left', value: 'rotateOutUpLeft' },
    { name: 'Rotate Out Up Right', value: 'rotateOutUpRight' },
    { name: 'Slide Out Up', value: 'slideOutUp' },
    { name: 'Slide Out Down', value: 'slideOutDown' },
    { name: 'Slide Out Left', value: 'slideOutLeft' },
    { name: 'Slide Out Right', value: 'slideOutRight' },
    { name: 'Zoom Out', value: 'zoomOut' },
    { name: 'Zoom Out Down', value: 'zoomOutDown' },
    { name: 'Zoom Out Left', value: 'zoomOutLeft' },
    { name: 'Zoom Out Right', value: 'zoomOutRight' },
    { name: 'Zoom Out Up', value: 'zoomOutUp' },
    { name: 'Hinge', value: 'hinge' },
    { name: 'Roll Out', value: 'rollOut' },
  ],
  [ANIMATION_TYPES.IDLE]: [
    { name: 'Bounce', value: 'bounce' },
    { name: 'Flash', value: 'flash' },
    { name: 'Pulse', value: 'pulse' },
    { name: 'Rubber Band', value: 'rubberBand' },
    { name: 'Shake', value: 'shake' },
    { name: 'Swing', value: 'swing' },
    { name: 'Tada', value: 'tada' },
    { name: 'Wobble', value: 'wobble' },
    { name: 'Jello', value: 'jello' },
    { name: 'Heart Beat', value: 'heartBeat' },
    { name: 'Flip', value: 'flip' },
  ],
};
