export default [
  'Kanit',
  'Russo One',
  'Beth Ellen',
  'Exo 2',
  'Italianno',
  'Fjalla One',
  'Gentium Book Basic',
  'Source Sans Pro',
  'Poppins',
  'Squada One',
  'Lato',
  'Questrial',
  'Sintony',
  'Lora',
  'Roboto',
  'Khula',
  'Yanone Kaffeesatz',
  'Syncopate',
  'Economica',
  'Vollkorn',
  'Rajdhani',
  'Merriweather',
  'Ek Mukta',
  'Merriweather Sans',
  'Istok Web',
  'Metrophobic',
  'Montserrat',
  'Gravitas One',
  'PT Sans',
  'Open Sans',
  'Oswald',
  'Palanquin',
  'Bangers',
  'Fredoka One',
  'Covered By Your Grace',
  'Coda',
  'Bowlby One SC',
  'Titan One',
  'Bevan',
  'Teko',
  'Tienne',
  'Alfa Slab One',
  'Martel Sans',
  'Raleway',
  'Fredericka the Great',
  'Cabin Sketch',
  'Special Elite',
  'Anton',
  'Zeyada',
  'La Belle Aurore',
  'Homemade Apple',
  'Crete Round',
  'Palanquin Dark',
  'Dawning of a New Day',
  'Give You Glory',
  'Indie Flower',
  'Just Me Again Down Here',
  'Over the Rainbow',
  'Permanent Marker',
  'Reenie Beanie',
  'Rock Salt',
  'Waiting for the Sunrise',
  'Walter Turncoat',
  'Vast Shadow',
  'Lily Script One',
  'Cookie',
];
