export const GOOGLE_MAP_VALUES = {
  ROADMAP: 'ROADMAP',
  SATELLITE: 'SATELLITE',
  SIDEBYSIDE: 'SIDEBYSIDE',
  STREETVIEW: 'STREETVIEW',
  HYBRID: 'HYBRID',
  TERRAIN: 'TERRAIN',
};

export const GOOGLE_MAP_ITEMS = [
  { label: 'Road Map', value: GOOGLE_MAP_VALUES.ROADMAP },
  { label: 'Satellite', value: GOOGLE_MAP_VALUES.SATELLITE },
  { label: 'Side-By-Side', value: GOOGLE_MAP_VALUES.SIDEBYSIDE },
  { label: 'Street View', value: GOOGLE_MAP_VALUES.STREETVIEW },
  { label: 'Hybrid', value: GOOGLE_MAP_VALUES.HYBRID },
  { label: 'Terrain', value: GOOGLE_MAP_VALUES.TERRAIN },
];

export const GOOGLE_MAP_CONSTANTS = {
  MAX_MAP_ZOOM_VALUE: 22,
  MAX_STREETVIEW_ZOOM_VALUE: 4,
  DEFAULT_STREETVIEW_ZOOM_VALUE: 1,
  MAX_MAP_PITCH_VALUE: 12,
  MAX_MAP_HEADING_VALUE: 12,
  TOP_DEFAULT: 15,
  LEFT_DEFAULT: 15,
  WIDTH_DEFAULT: 70,
  HEIGHT_DEFAULT: 70,
  ZOOM_DEFAULT: 10,
};
