/**
 * MuAPI catalog — image and video models extracted from the live
 * https://api.muapi.ai/api/v1/models endpoint.
 * 
 * This file is generated from the live catalog. Regenerate it with:
 * python3 scripts/update-muapi-catalog.py
 */

export const MUAPI_CATALOG = [
  {
    name: 'flux-dev',
    nodeType: 'flux-dev',
    id: 'flux-dev',
    category: 'image',
    description: 'Generate stunning visuals from simple text prompts. Flux Dev transforms your ideas into high-quality...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-dev',
    endpoint: 'flux-dev',
    cost: 0.015,
    inputs: [],
  },
  {
    name: 'flux-schnell',
    nodeType: 'flux-schnell',
    id: 'flux-schnell',
    category: 'image',
    description: 'Flux Schnell is a lightning-fast image generation model designed for rapid iterations. It delivers g...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-schnell',
    endpoint: 'flux-schnell',
    cost: 0.003,
    inputs: [],
  },
  {
    name: 'flux-kontext-dev-t2i',
    nodeType: 'flux-kontext-dev-t2i',
    id: 'flux-kontext-dev-t2i',
    category: 'image',
    description: 'Generates an image from a text prompt, with optional reference image for pose or style guidance. Ide...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-kontext-dev-t2i',
    endpoint: 'flux-kontext-dev-t2i',
    cost: 0.02,
    inputs: [],
  },
  {
    name: 'flux-kontext-pro-t2i',
    nodeType: 'flux-kontext-pro-t2i',
    id: 'flux-kontext-pro-t2i',
    category: 'image',
    description: 'Flux Kontext Pro T2I offers fast and reliable generation with creative flexibility. It supports styl...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-kontext-pro-t2i',
    endpoint: 'flux-kontext-pro-t2i',
    cost: 0.03,
    inputs: [],
  },
  {
    name: 'flux-kontext-max-t2i',
    nodeType: 'flux-kontext-max-t2i',
    id: 'flux-kontext-max-t2i',
    category: 'image',
    description: 'Flux Kontext Max T2I delivers photorealistic or cinematic-quality images with exceptional detail. It...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-kontext-max-t2i',
    endpoint: 'flux-kontext-max-t2i',
    cost: 0.06,
    inputs: [],
  },
  {
    name: 'hidream-i1-fast',
    nodeType: 'hidream-i1-fast',
    id: 'hidream-i1-fast',
    category: 'image',
    description: 'Optimized for speed, this variant generates images in just a few steps. Ideal for previews, real-tim...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'hidream-i1-fast',
    endpoint: 'hidream-i1-fast',
    cost: 0.008,
    inputs: [],
  },
  {
    name: 'hidream-i1-dev',
    nodeType: 'hidream-i1-dev',
    id: 'hidream-i1-dev',
    category: 'image',
    description: 'Optimized for speed, this variant generates images in just a few steps. Ideal for previews, real-tim...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'hidream-i1-dev',
    endpoint: 'hidream-i1-dev',
    cost: 0.02,
    inputs: [],
  },
  {
    name: 'hidream-i1-full',
    nodeType: 'hidream-i1-full',
    id: 'hidream-i1-full',
    category: 'image',
    description: 'The most advanced version of HiDream I1, delivering high-resolution, detailed images with superior p...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'hidream-i1-full',
    endpoint: 'hidream-i1-full',
    cost: 0.04,
    inputs: [],
  },
  {
    name: 'midjourney-v7',
    nodeType: 'midjourney-v7',
    id: 'midjourney-v7',
    category: 'image',
    description: 'Generate 4 photorealistic images per run with Midjourney V7. Supports text-to-image and reference im...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'midjourney-v7',
    endpoint: 'midjourney-v7',
    cost: 0.1,
    inputs: [],
  },
  {
    name: 'midjourney-v8',
    nodeType: 'midjourney-v8',
    id: 'midjourney-v8',
    category: 'image',
    description: 'Generate 4 photorealistic images per run with Midjourney V8. Improved coherence and detail over V7. ...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'midjourney-v8',
    endpoint: 'midjourney-v8',
    cost: 0.1,
    inputs: [],
  },
  {
    name: 'midjourney-niji',
    nodeType: 'midjourney-niji',
    id: 'midjourney-niji',
    category: 'image',
    description: 'Generate 4 anime and illustration-style images per run with Midjourney Niji. Optimized for character...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'midjourney-niji',
    endpoint: 'midjourney-niji',
    cost: 0.1,
    inputs: [],
  },
  {
    name: 'gpt4o-text-to-image',
    nodeType: 'gpt4o-text-to-image',
    id: 'gpt4o-text-to-image',
    category: 'image',
    description: 'Generate images from text prompts using GPT-4o\'s vision capabilities. Ideal for basic concept visua...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'gpt4o-text-to-image',
    endpoint: 'gpt4o-text-to-image',
    cost: 0.04,
    inputs: [],
  },
  {
    name: 'gpt-image-1.5',
    nodeType: 'gpt-image-1.5',
    id: 'gpt-image-1.5',
    category: 'image',
    description: 'GPT-Image-1.5 is a high-quality text-to-image generation model designed for rich visual reasoning, d...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'gpt-image-1.5',
    endpoint: 'gpt-image-1.5',
    cost: 0.054,
    inputs: [],
  },
  {
    name: 'gpt-image-2-text-to-image',
    nodeType: 'gpt-image-2-text-to-image',
    id: 'gpt-image-2-text-to-image',
    category: 'image',
    description: 'Generate high-quality images from text prompts using GPT Image 2, supporting up to 20,000 character ...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'gpt-image-2-text-to-image',
    endpoint: 'gpt-image-2-text-to-image',
    cost: 0.09,
    inputs: [],
  },
  {
    name: 'reve-text-to-image',
    nodeType: 'reve-text-to-image',
    id: 'reve-text-to-image',
    category: 'image',
    description: 'Generate images from text prompts using reve\'s vision capabilities. Ideal for basic concept visuals...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'reve-text-to-image',
    endpoint: 'reve-text-to-image',
    cost: 0.032,
    inputs: [],
  },
  {
    name: 'qwen-image',
    nodeType: 'qwen-image',
    id: 'qwen-image',
    category: 'image',
    description: 'Generate high-quality, detailed images from text prompts in various styles — from realistic to artis...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'qwen-image',
    endpoint: 'qwen-image',
    cost: 0.03,
    inputs: [],
  },
  {
    name: 'qwen-image-2.0',
    nodeType: 'qwen-image-2.0',
    id: 'qwen-image-2.0',
    category: 'image',
    description: 'Qwen 2.0 Text to Image model with enhanced realism....',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'qwen-image-2.0',
    endpoint: 'qwen-image-2.0',
    cost: 0.04,
    inputs: [],
  },
  {
    name: 'qwen-image-2.0-pro',
    nodeType: 'qwen-image-2.0-pro',
    id: 'qwen-image-2.0-pro',
    category: 'image',
    description: 'Qwen 2.0 Pro Text to Image model with maximum realism and fidelity....',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'qwen-image-2.0-pro',
    endpoint: 'qwen-image-2.0-pro',
    cost: 0.09,
    inputs: [],
  },
  {
    name: 'nano-banana',
    nodeType: 'nano-banana',
    id: 'nano-banana',
    category: 'image',
    description: 'Nano Banana is an advanced AI model excelling in natural language-driven image generation and editin...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'nano-banana',
    endpoint: 'nano-banana',
    cost: 0.03,
    inputs: [],
  },
  {
    name: 'nano-banana-2',
    nodeType: 'nano-banana-2',
    id: 'nano-banana-2',
    category: 'image',
    description: 'Nano Banana 2 (Gemini 3.1 Flash Image) is Google\'s most advanced image generation model, combining ...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'nano-banana-2',
    endpoint: 'nano-banana-2',
    cost: 0.06,
    inputs: [],
  },
  {
    name: 'nano-banana-pro',
    nodeType: 'nano-banana-pro',
    id: 'nano-banana-pro',
    category: 'image',
    description: 'Nano Banana 2 is the next-generation image generation developed by Google DeepMind, following the or...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'nano-banana-pro',
    endpoint: 'nano-banana-pro',
    cost: 0.12,
    inputs: [],
  },
  {
    name: 'flux-2-dev',
    nodeType: 'flux-2-dev',
    id: 'flux-2-dev',
    category: 'image',
    description: 'Flux 2 Dev is a powerful text-to-image diffusion model designed for high-quality, fast, and highly d...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-2-dev',
    endpoint: 'flux-2-dev',
    cost: 0.015,
    inputs: [],
  },
  {
    name: 'flux-2-flex',
    nodeType: 'flux-2-flex',
    id: 'flux-2-flex',
    category: 'image',
    description: 'Flux-2-Flex Text-to-Image is a flexible, high-fidelity generative model capable of producing detaile...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-2-flex',
    endpoint: 'flux-2-flex',
    cost: 0.09,
    inputs: [],
  },
  {
    name: 'flux-2-pro',
    nodeType: 'flux-2-pro',
    id: 'flux-2-pro',
    category: 'image',
    description: 'Flux-2-Pro Text-to-Image is a premium, high-fidelity generative model capable of producing ultra-rea...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-2-pro',
    endpoint: 'flux-2-pro',
    cost: 0.032,
    inputs: [],
  },
  {
    name: 'flux-3-dev',
    nodeType: 'flux-3-dev',
    id: 'flux-3-dev',
    category: 'image',
    description: 'FLUX 3 Dev is the faster, lower-cost variant of Black Forest Labs\' FLUX 3 frontier model, planned f...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-3-dev',
    endpoint: 'flux-3-dev',
    cost: 0.025,
    inputs: [],
  },
  {
    name: 'flux-3-text-to-image',
    nodeType: 'flux-3-text-to-image',
    id: 'flux-3-text-to-image',
    category: 'image',
    description: 'FLUX 3 Text-to-Image is Black Forest Labs\' next-generation multimodal frontier model, jointly train...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'flux-3-text-to-image',
    endpoint: 'flux-3-text-to-image',
    cost: 0.05,
    inputs: [],
  },
  {
    name: 'ideogram-v3-t2i',
    nodeType: 'ideogram-v3-t2i',
    id: 'ideogram-v3-t2i',
    category: 'image',
    description: 'Ideogram v3 is an advanced text-to-image model designed for creating highly detailed and visually st...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'ideogram-v3-t2i',
    endpoint: 'ideogram-v3-t2i',
    cost: 0.02,
    inputs: [],
  },
  {
    name: 'google-imagen4',
    nodeType: 'google-imagen4',
    id: 'google-imagen4',
    category: 'image',
    description: 'Google Imagen 4 is the latest text-to-image AI model from DeepMind, designed to produce stunningly p...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'google-imagen4',
    endpoint: 'google-imagen4',
    cost: 0.03,
    inputs: [],
  },
  {
    name: 'google-imagen4-fast',
    nodeType: 'google-imagen4-fast',
    id: 'google-imagen4-fast',
    category: 'image',
    description: 'Imagen 4 Fast is optimized for speed and accessibility, allowing you to generate high-quality images...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'google-imagen4-fast',
    endpoint: 'google-imagen4-fast',
    cost: 0.02,
    inputs: [],
  },
  {
    name: 'google-imagen4-ultra',
    nodeType: 'google-imagen4-ultra',
    id: 'google-imagen4-ultra',
    category: 'image',
    description: 'Imagen 4 Ultra is Google’s flagship model, designed for photorealism, rich textures, and production-...',
    outputType: 'image',
    provider: 'muapi',
    muapiModelId: 'google-imagen4-ultra',
    endpoint: 'google-imagen4-ultra',
    cost: 0.06,
    inputs: [],
  },
  {
    name: 'veo3-text-to-video',
    nodeType: 'veo3-text-to-video',
    id: 'veo3-text-to-video',
    category: 'video',
    description: 'VEO3 T2V generates cinematic videos from text prompts, capturing dynamic motion, rich scenes, and st...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'veo3-text-to-video',
    endpoint: 'veo3-text-to-video',
    cost: 2.5,
    inputs: [],
  },
  {
    name: 'veo3-fast-text-to-video',
    nodeType: 'veo3-fast-text-to-video',
    id: 'veo3-fast-text-to-video',
    category: 'video',
    description: 'VEO3 Fast T2V creates short videos from text instantly, balancing speed and quality for quick conten...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'veo3-fast-text-to-video',
    endpoint: 'veo3-fast-text-to-video',
    cost: 0.6,
    inputs: [],
  },
  {
    name: 'veo3.1-text-to-video',
    nodeType: 'veo3.1-text-to-video',
    id: 'veo3.1-text-to-video',
    category: 'video',
    description: 'Veo 3.1 is Google\'s advanced AI video generation model that transforms text prompts into high-quali...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'veo3.1-text-to-video',
    endpoint: 'veo3.1-text-to-video',
    cost: 2.5,
    inputs: [],
  },
  {
    name: 'veo3.1-fast-text-to-video',
    nodeType: 'veo3.1-fast-text-to-video',
    id: 'veo3.1-fast-text-to-video',
    category: 'video',
    description: 'Veo 3.1 Fast T2V is a high-speed AI video model that transforms text prompts into realistic 8-second...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'veo3.1-fast-text-to-video',
    endpoint: 'veo3.1-fast-text-to-video',
    cost: 0.6,
    inputs: [],
  },
  {
    name: 'kling-v3.0-pro-text-to-video',
    nodeType: 'kling-v3.0-pro-text-to-video',
    id: 'kling-v3.0-pro-text-to-video',
    category: 'video',
    description: 'Kling 3.0 Pro is a high-end video generation model capable of producing longer, smoother, and more r...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-v3.0-pro-text-to-video',
    endpoint: 'kling-v3.0-pro-text-to-video',
    cost: 0.72,
    inputs: [],
  },
  {
    name: 'kling-v3.0-standard-text-to-video',
    nodeType: 'kling-v3.0-standard-text-to-video',
    id: 'kling-v3.0-standard-text-to-video',
    category: 'video',
    description: 'Kling 3.0 Standard Text-to-Video generates smooth, realistic videos from text with stable motion and...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-v3.0-standard-text-to-video',
    endpoint: 'kling-v3.0-standard-text-to-video',
    cost: 0.72,
    inputs: [],
  },
  {
    name: 'kling-v2.5-turbo-pro-t2v',
    nodeType: 'kling-v2.5-turbo-pro-t2v',
    id: 'kling-v2.5-turbo-pro-t2v',
    category: 'video',
    description: 'Kling 2.5 Turbo Pro: Top-tier text-to-video generation with unparalleled motion fluidity, cinematic ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-v2.5-turbo-pro-t2v',
    endpoint: 'kling-v2.5-turbo-pro-t2v',
    cost: 0.45,
    inputs: [],
  },
  {
    name: 'kling-v2.6-pro-t2v',
    nodeType: 'kling-v2.6-pro-t2v',
    id: 'kling-v2.6-pro-t2v',
    category: 'video',
    description: 'Kling-v2.6-Pro Text-to-Video generates high-fidelity cinematic videos directly from text prompts. It...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-v2.6-pro-t2v',
    endpoint: 'kling-v2.6-pro-t2v',
    cost: 0.9,
    inputs: [],
  },
  {
    name: 'kling-o1-text-to-video',
    nodeType: 'kling-o1-text-to-video',
    id: 'kling-o1-text-to-video',
    category: 'video',
    description: 'Kling O1 is a unified, multi-modal video generation engine that transforms natural language prompts ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-o1-text-to-video',
    endpoint: 'kling-o1-text-to-video',
    cost: 0.72,
    inputs: [],
  },
  {
    name: 'wan2.1-text-to-video',
    nodeType: 'wan2.1-text-to-video',
    id: 'wan2.1-text-to-video',
    category: 'video',
    description: 'WAN 2.1 turns your written prompts into vivid, cinematic video clips. Ideal for storytelling, conten...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.1-text-to-video',
    endpoint: 'wan2.1-text-to-video',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'wan2.2-text-to-video',
    nodeType: 'wan2.2-text-to-video',
    id: 'wan2.2-text-to-video',
    category: 'video',
    description: 'Wan 2.2’s T2V mode transforms descriptive text prompts into high-quality, stylized video sequences. ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.2-text-to-video',
    endpoint: 'wan2.2-text-to-video',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'wan2.5-text-to-video',
    nodeType: 'wan2.5-text-to-video',
    id: 'wan2.5-text-to-video',
    category: 'video',
    description: 'WAN 2.5 Text-to-Video transforms written prompts into cinematic video clips with dynamic motion, rea...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.5-text-to-video',
    endpoint: 'wan2.5-text-to-video',
    cost: 0.65,
    inputs: [],
  },
  {
    name: 'wan2.6-text-to-video',
    nodeType: 'wan2.6-text-to-video',
    id: 'wan2.6-text-to-video',
    category: 'video',
    description: 'WAN 2.6 Text-to-Video generates smooth, cinematic videos directly from text prompts. It’s designed f...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.6-text-to-video',
    endpoint: 'wan2.6-text-to-video',
    cost: 0.65,
    inputs: [],
  },
  {
    name: 'wan2.7-text-to-video',
    nodeType: 'wan2.7-text-to-video',
    id: 'wan2.7-text-to-video',
    category: 'video',
    description: 'Alibaba WAN 2.7 Text-to-Video turns plain prompts into coherent, cinematic clips....',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.7-text-to-video',
    endpoint: 'wan2.7-text-to-video',
    cost: 0.1,
    inputs: [],
  },
  {
    name: 'wan3.0-text-to-video',
    nodeType: 'wan3.0-text-to-video',
    id: 'wan3.0-text-to-video',
    category: 'video',
    description: 'Wan 3.0 Text to Video is an upcoming AI video model. Confirmed API controls, output specifications, ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan3.0-text-to-video',
    endpoint: 'wan3.0-text-to-video',
    cost: 0.0,
    inputs: [],
  },
  {
    name: 'seedance-pro-t2v',
    nodeType: 'seedance-pro-t2v',
    id: 'seedance-pro-t2v',
    category: 'video',
    description: 'Seedance Pro delivers high-fidelity video generation from text, producing rich visuals, smooth camer...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'seedance-pro-t2v',
    endpoint: 'seedance-pro-t2v',
    cost: 0.18,
    inputs: [],
  },
  {
    name: 'seedance-lite-t2v',
    nodeType: 'seedance-lite-t2v',
    id: 'seedance-lite-t2v',
    category: 'video',
    description: 'Seedance Lite T2V offers quick video generation from text with decent visual quality and motion. Ide...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'seedance-lite-t2v',
    endpoint: 'seedance-lite-t2v',
    cost: 0.1,
    inputs: [],
  },
  {
    name: 'seedance-2-text-to-video',
    nodeType: 'seedance-2-text-to-video',
    id: 'seedance-2-text-to-video',
    category: 'video',
    description: 'SD 2 Text-to-Video (Pro) by ByteDance. Generates high-quality cinematic video from a text prompt wit...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'seedance-2-text-to-video',
    endpoint: 'seedance-2-text-to-video',
    cost: 1.25,
    inputs: [],
  },
  {
    name: 'seedance-2.5-text-to-video',
    nodeType: 'seedance-2.5-text-to-video',
    id: 'seedance-2.5-text-to-video',
    category: 'video',
    description: 'Seedance 2.5 Text-to-Video is the early-access preview build of the Seedance 2.5 family, generating ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'seedance-2.5-text-to-video',
    endpoint: 'seedance-2.5-text-to-video',
    cost: 1.7,
    inputs: [],
  },
  {
    name: 'hunyuan-text-to-video',
    nodeType: 'hunyuan-text-to-video',
    id: 'hunyuan-text-to-video',
    category: 'video',
    description: 'Hunyuan T2V generates detailed and dynamic videos from text prompts with a focus on realism and cohe...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'hunyuan-text-to-video',
    endpoint: 'hunyuan-text-to-video',
    cost: 0.15,
    inputs: [],
  },
  {
    name: 'hunyuan-fast-text-to-video',
    nodeType: 'hunyuan-fast-text-to-video',
    id: 'hunyuan-fast-text-to-video',
    category: 'video',
    description: 'Hunyuan Fast T2V provides accelerated video generation from text prompts with slightly reduced detai...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'hunyuan-fast-text-to-video',
    endpoint: 'hunyuan-fast-text-to-video',
    cost: 0.05,
    inputs: [],
  },
  {
    name: 'runway-text-to-video',
    nodeType: 'runway-text-to-video',
    id: 'runway-text-to-video',
    category: 'video',
    description: 'Generate short, high-quality videos from plain text prompts. RunwayML’s text-to-video model interpre...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'runway-text-to-video',
    endpoint: 'runway-text-to-video',
    cost: 0.09,
    inputs: [],
  },
  {
    name: 'pixverse-v4.5-t2v',
    nodeType: 'pixverse-v4.5-t2v',
    id: 'pixverse-v4.5-t2v',
    category: 'video',
    description: 'PixVerse v4.5 transforms descriptive text into vivid, high-resolution video clips. It understands co...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'pixverse-v4.5-t2v',
    endpoint: 'pixverse-v4.5-t2v',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'pixverse-v5-t2v',
    nodeType: 'pixverse-v5-t2v',
    id: 'pixverse-v5-t2v',
    category: 'video',
    description: 'PixVerse V5 delivers a major leap forward in AI-powered video creation — now featuring smoother moti...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'pixverse-v5-t2v',
    endpoint: 'pixverse-v5-t2v',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'pixverse-v5.5-t2v',
    nodeType: 'pixverse-v5.5-t2v',
    id: 'pixverse-v5.5-t2v',
    category: 'video',
    description: 'PixVerse v5.5 T2V generates cinematic short videos directly from text. It excels at stylized fantasy...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'pixverse-v5.5-t2v',
    endpoint: 'pixverse-v5.5-t2v',
    cost: 0.1,
    inputs: [],
  },
  {
    name: 'pixverse-v6-t2v',
    nodeType: 'pixverse-v6-t2v',
    id: 'pixverse-v6-t2v',
    category: 'video',
    description: 'Generate high-quality videos from text prompts using PixVerse V6. Supports resolutions up to 1080p, ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'pixverse-v6-t2v',
    endpoint: 'pixverse-v6-t2v',
    cost: 0.295,
    inputs: [],
  },
  {
    name: 'vidu-q2-pro-text-to-video',
    nodeType: 'vidu-q2-pro-text-to-video',
    id: 'vidu-q2-pro-text-to-video',
    category: 'video',
    description: 'Vidu Q2 Pro Text-to-Video generates cinematic, prompt-faithful clips from text alone with strong tem...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'vidu-q2-pro-text-to-video',
    endpoint: 'vidu-q2-pro-text-to-video',
    cost: 0.2,
    inputs: [],
  },
  {
    name: 'vidu-q2-turbo-text-to-video',
    nodeType: 'vidu-q2-turbo-text-to-video',
    id: 'vidu-q2-turbo-text-to-video',
    category: 'video',
    description: 'Vidu Q2 Turbo Text-to-Video is the fast, affordable Q2 tier for prompt-only generation. Use it for s...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'vidu-q2-turbo-text-to-video',
    endpoint: 'vidu-q2-turbo-text-to-video',
    cost: 0.13,
    inputs: [],
  },
  {
    name: 'vidu-q3-pro-text-to-video',
    nodeType: 'vidu-q3-pro-text-to-video',
    id: 'vidu-q3-pro-text-to-video',
    category: 'video',
    description: 'Vidu Q3 Pro Text-to-Video generates cinematic, prompt-faithful clips with strong temporal consistenc...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'vidu-q3-pro-text-to-video',
    endpoint: 'vidu-q3-pro-text-to-video',
    cost: 0.75,
    inputs: [],
  },
  {
    name: 'vidu-q3-turbo-text-to-video',
    nodeType: 'vidu-q3-turbo-text-to-video',
    id: 'vidu-q3-turbo-text-to-video',
    category: 'video',
    description: 'Vidu Q3 Turbo Text-to-Video is the fast, affordable tier of Vidu Q3 — same prompt understanding and ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'vidu-q3-turbo-text-to-video',
    endpoint: 'vidu-q3-turbo-text-to-video',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'minimax-hailuo-02-pro-t2v',
    nodeType: 'minimax-hailuo-02-pro-t2v',
    id: 'minimax-hailuo-02-pro-t2v',
    category: 'video',
    description: 'High-fidelity text-to-video with cinematic rendering. Best for storytelling, cinematic clips, or rea...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'minimax-hailuo-02-pro-t2v',
    endpoint: 'minimax-hailuo-02-pro-t2v',
    cost: 0.6,
    inputs: [],
  },
  {
    name: 'minimax-hailuo-02-standard-t2v',
    nodeType: 'minimax-hailuo-02-standard-t2v',
    id: 'minimax-hailuo-02-standard-t2v',
    category: 'video',
    description: 'Fast and lightweight text-to-video generation. Ideal for quick drafts, previews, or playful content ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'minimax-hailuo-02-standard-t2v',
    endpoint: 'minimax-hailuo-02-standard-t2v',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'minimax-hailuo-2.3-pro-t2v',
    nodeType: 'minimax-hailuo-2.3-pro-t2v',
    id: 'minimax-hailuo-2.3-pro-t2v',
    category: 'video',
    description: 'Hailuo 2.3 Pro T2V turns your imagination into motion-picture realism. It interprets natural languag...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'minimax-hailuo-2.3-pro-t2v',
    endpoint: 'minimax-hailuo-2.3-pro-t2v',
    cost: 0.63,
    inputs: [],
  },
  {
    name: 'minimax-hailuo-2.3-standard-t2v',
    nodeType: 'minimax-hailuo-2.3-standard-t2v',
    id: 'minimax-hailuo-2.3-standard-t2v',
    category: 'video',
    description: 'Hailuo 2.3 Standard T2V transforms pure imagination into moving cinematic visuals. Simply describe a...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'minimax-hailuo-2.3-standard-t2v',
    endpoint: 'minimax-hailuo-2.3-standard-t2v',
    cost: 0.36,
    inputs: [],
  },
  {
    name: 'openai-sora-2-text-to-video',
    nodeType: 'openai-sora-2-text-to-video',
    id: 'openai-sora-2-text-to-video',
    category: 'video',
    description: 'Sora 2 T2V converts text prompts into short, dynamic 10-second video clips with synchronized audio. ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'openai-sora-2-text-to-video',
    endpoint: 'openai-sora-2-text-to-video',
    cost: 0.8,
    inputs: [],
  },
  {
    name: 'openai-sora-2-pro-text-to-video',
    nodeType: 'openai-sora-2-pro-text-to-video',
    id: 'openai-sora-2-pro-text-to-video',
    category: 'video',
    description: 'Sora 2 Pro T2V is the high-fidelity version of OpenAI’s video generation model. It converts your tex...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'openai-sora-2-pro-text-to-video',
    endpoint: 'openai-sora-2-pro-text-to-video',
    cost: 2.4,
    inputs: [],
  },
  {
    name: 'openai-sora',
    nodeType: 'openai-sora',
    id: 'openai-sora',
    category: 'video',
    description: 'Sora is a text-to-video generative AI model developed by OpenAI. It can generate short video clips b...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'openai-sora',
    endpoint: 'openai-sora',
    cost: 0.5,
    inputs: [],
  },
  {
    name: 'kling-v3.0-pro-image-to-video',
    nodeType: 'kling-v3.0-pro-image-to-video',
    id: 'kling-v3.0-pro-image-to-video',
    category: 'video',
    description: 'Kling 3.0 Pro Image-to-Video animates a single input image into a high-quality, realistic video with...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-v3.0-pro-image-to-video',
    endpoint: 'kling-v3.0-pro-image-to-video',
    cost: 0.72,
    inputs: [],
  },
  {
    name: 'kling-v3.0-standard-image-to-video',
    nodeType: 'kling-v3.0-standard-image-to-video',
    id: 'kling-v3.0-standard-image-to-video',
    category: 'video',
    description: 'Kling 3.0 Standard Image-to-Video animates a single input image into a short, realistic video with s...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-v3.0-standard-image-to-video',
    endpoint: 'kling-v3.0-standard-image-to-video',
    cost: 0.72,
    inputs: [],
  },
  {
    name: 'kling-v2.5-turbo-pro-i2v',
    nodeType: 'kling-v2.5-turbo-pro-i2v',
    id: 'kling-v2.5-turbo-pro-i2v',
    category: 'video',
    description: 'Kling 2.5 Turbo Pro: Top-tier image-to-video generation with unparalleled motion fluidity, cinematic...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-v2.5-turbo-pro-i2v',
    endpoint: 'kling-v2.5-turbo-pro-i2v',
    cost: 0.45,
    inputs: [],
  },
  {
    name: 'kling-v2.6-pro-i2v',
    nodeType: 'kling-v2.6-pro-i2v',
    id: 'kling-v2.6-pro-i2v',
    category: 'video',
    description: 'Kling-v2.6-Pro Image-to-Video transforms a single creative image into a short cinematic video. It pr...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-v2.6-pro-i2v',
    endpoint: 'kling-v2.6-pro-i2v',
    cost: 0.9,
    inputs: [],
  },
  {
    name: 'kling-o1-image-to-video',
    nodeType: 'kling-o1-image-to-video',
    id: 'kling-o1-image-to-video',
    category: 'video',
    description: 'Kling O1’s Image-to-Video mode transforms one or more reference images into short cinematic video cl...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'kling-o1-image-to-video',
    endpoint: 'kling-o1-image-to-video',
    cost: 0.72,
    inputs: [],
  },
  {
    name: 'seedance-2-image-to-video',
    nodeType: 'seedance-2-image-to-video',
    id: 'seedance-2-image-to-video',
    category: 'video',
    description: 'SD 2 Image-to-Video (Pro) by ByteDance. Animates a start-frame image into a high-quality video with ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'seedance-2-image-to-video',
    endpoint: 'seedance-2-image-to-video',
    cost: 1.25,
    inputs: [],
  },
  {
    name: 'seedance-2.5-image-to-video',
    nodeType: 'seedance-2.5-image-to-video',
    id: 'seedance-2.5-image-to-video',
    category: 'video',
    description: 'Seedance 2.5 Image-to-Video is the early-access preview build of the Seedance 2.5 family, animating ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'seedance-2.5-image-to-video',
    endpoint: 'seedance-2.5-image-to-video',
    cost: 1.7,
    inputs: [],
  },
  {
    name: 'seedance-2-omni-reference',
    nodeType: 'seedance-2-omni-reference',
    id: 'seedance-2-omni-reference',
    category: 'video',
    description: 'SD 2.0 Omni Reference — generate videos with visual consistency using reference images, videos, and ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'seedance-2-omni-reference',
    endpoint: 'seedance-2-omni-reference',
    cost: 1.5,
    inputs: [],
  },
  {
    name: 'veo3-image-to-video',
    nodeType: 'veo3-image-to-video',
    id: 'veo3-image-to-video',
    category: 'video',
    description: 'VEO3 I2V animates static images into expressive video sequences, adding lifelike movement while pres...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'veo3-image-to-video',
    endpoint: 'veo3-image-to-video',
    cost: 2.5,
    inputs: [],
  },
  {
    name: 'veo3-fast-image-to-video',
    nodeType: 'veo3-fast-image-to-video',
    id: 'veo3-fast-image-to-video',
    category: 'video',
    description: 'Quickly transform static images into short, motion-rich video clips with fast rendering and impressi...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'veo3-fast-image-to-video',
    endpoint: 'veo3-fast-image-to-video',
    cost: 0.6,
    inputs: [],
  },
  {
    name: 'veo3.1-image-to-video',
    nodeType: 'veo3.1-image-to-video',
    id: 'veo3.1-image-to-video',
    category: 'video',
    description: 'Veo 3.1 is Google\'s advanced AI video generation model that allows users to create high-quality, 8-...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'veo3.1-image-to-video',
    endpoint: 'veo3.1-image-to-video',
    cost: 2.5,
    inputs: [],
  },
  {
    name: 'veo3.1-fast-image-to-video',
    nodeType: 'veo3.1-fast-image-to-video',
    id: 'veo3.1-fast-image-to-video',
    category: 'video',
    description: 'Veo 3.1 Fast is an optimized version of Google’s Veo 3.1 AI that transforms static images into dynam...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'veo3.1-fast-image-to-video',
    endpoint: 'veo3.1-fast-image-to-video',
    cost: 0.6,
    inputs: [],
  },
  {
    name: 'wan2.1-image-to-video',
    nodeType: 'wan2.1-image-to-video',
    id: 'wan2.1-image-to-video',
    category: 'video',
    description: 'Animate static images into expressive video sequences with WAN 2.1. Upload any image and guide its t...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.1-image-to-video',
    endpoint: 'wan2.1-image-to-video',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'wan2.2-image-to-video',
    nodeType: 'wan2.2-image-to-video',
    id: 'wan2.2-image-to-video',
    category: 'video',
    description: 'Wan 2.2’s I2V mode brings static visuals to life with vivid, expressive animations. It interprets mo...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.2-image-to-video',
    endpoint: 'wan2.2-image-to-video',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'wan2.5-image-to-video',
    nodeType: 'wan2.5-image-to-video',
    id: 'wan2.5-image-to-video',
    category: 'video',
    description: 'WAN 2.5 Image-to-Video takes your image as the starting frame and turns it into a dynamic video, pre...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.5-image-to-video',
    endpoint: 'wan2.5-image-to-video',
    cost: 0.65,
    inputs: [],
  },
  {
    name: 'wan2.6-image-to-video',
    nodeType: 'wan2.6-image-to-video',
    id: 'wan2.6-image-to-video',
    category: 'video',
    description: 'WAN 2.6 Image-to-Video converts a single still image into a smooth, cinematic video clip. It preserv...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.6-image-to-video',
    endpoint: 'wan2.6-image-to-video',
    cost: 0.65,
    inputs: [],
  },
  {
    name: 'wan2.7-image-to-video',
    nodeType: 'wan2.7-image-to-video',
    id: 'wan2.7-image-to-video',
    category: 'video',
    description: 'Alibaba WAN 2.7 converts images into videos with optional audio....',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan2.7-image-to-video',
    endpoint: 'wan2.7-image-to-video',
    cost: 0.1,
    inputs: [],
  },
  {
    name: 'wan3.0-image-to-video',
    nodeType: 'wan3.0-image-to-video',
    id: 'wan3.0-image-to-video',
    category: 'video',
    description: 'Wan 3.0 Image to Video is an upcoming AI video model. Confirmed API controls, output specifications,...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'wan3.0-image-to-video',
    endpoint: 'wan3.0-image-to-video',
    cost: 0.0,
    inputs: [],
  },
  {
    name: 'runway-image-to-video',
    nodeType: 'runway-image-to-video',
    id: 'runway-image-to-video',
    category: 'video',
    description: 'Animate any image by turning it into a video with motion effects or scene continuity. RunwayML’s I2V...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'runway-image-to-video',
    endpoint: 'runway-image-to-video',
    cost: 0.15,
    inputs: [],
  },
  {
    name: 'pixverse-v4.5-i2v',
    nodeType: 'pixverse-v4.5-i2v',
    id: 'pixverse-v4.5-i2v',
    category: 'video',
    description: 'Upload an image and PixVerse v4.5 will breathe life into it with smooth camera motion, realistic eff...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'pixverse-v4.5-i2v',
    endpoint: 'pixverse-v4.5-i2v',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'pixverse-v5-i2v',
    nodeType: 'pixverse-v5-i2v',
    id: 'pixverse-v5-i2v',
    category: 'video',
    description: 'PixVerse V5 delivers a major leap forward in AI-powered video creation — now featuring smoother moti...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'pixverse-v5-i2v',
    endpoint: 'pixverse-v5-i2v',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'pixverse-v5.5-i2v',
    nodeType: 'pixverse-v5.5-i2v',
    id: 'pixverse-v5.5-i2v',
    category: 'video',
    description: 'PixVerse v5.5 I2V transforms a single image into a dynamic cinematic video clip. It adds smooth came...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'pixverse-v5.5-i2v',
    endpoint: 'pixverse-v5.5-i2v',
    cost: 0.1,
    inputs: [],
  },
  {
    name: 'pixverse-v6-i2v',
    nodeType: 'pixverse-v6-i2v',
    id: 'pixverse-v6-i2v',
    category: 'video',
    description: 'Animate any image into a video using PixVerse V6. Supports resolutions up to 1080p, durations up to ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'pixverse-v6-i2v',
    endpoint: 'pixverse-v6-i2v',
    cost: 0.295,
    inputs: [],
  },
  {
    name: 'vidu-q2-pro-image-to-video',
    nodeType: 'vidu-q2-pro-image-to-video',
    id: 'vidu-q2-pro-image-to-video',
    category: 'video',
    description: 'Vidu Q2 Pro Image-to-Video animates a single starting image into a smooth, prompt-guided clip up to ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'vidu-q2-pro-image-to-video',
    endpoint: 'vidu-q2-pro-image-to-video',
    cost: 0.2,
    inputs: [],
  },
  {
    name: 'vidu-q2-turbo-image-to-video',
    nodeType: 'vidu-q2-turbo-image-to-video',
    id: 'vidu-q2-turbo-image-to-video',
    category: 'video',
    description: 'Vidu Q2 Turbo Image-to-Video animates a starting image into a fast, prompt-guided clip while preserv...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'vidu-q2-turbo-image-to-video',
    endpoint: 'vidu-q2-turbo-image-to-video',
    cost: 0.13,
    inputs: [],
  },
  {
    name: 'vidu-q3-pro-image-to-video',
    nodeType: 'vidu-q3-pro-image-to-video',
    id: 'vidu-q3-pro-image-to-video',
    category: 'video',
    description: 'Vidu Q3 Pro Image-to-Video animates a single starting image into a smooth, prompt-guided clip up to ...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'vidu-q3-pro-image-to-video',
    endpoint: 'vidu-q3-pro-image-to-video',
    cost: 0.75,
    inputs: [],
  },
  {
    name: 'vidu-q3-turbo-image-to-video',
    nodeType: 'vidu-q3-turbo-image-to-video',
    id: 'vidu-q3-turbo-image-to-video',
    category: 'video',
    description: 'Vidu Q3 Turbo Image-to-Video animates a starting image into a fast, prompt-guided clip while keeping...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'vidu-q3-turbo-image-to-video',
    endpoint: 'vidu-q3-turbo-image-to-video',
    cost: 0.3,
    inputs: [],
  },
  {
    name: 'minimax-hailuo-02-pro-i2v',
    nodeType: 'minimax-hailuo-02-pro-i2v',
    id: 'minimax-hailuo-02-pro-i2v',
    category: 'video',
    description: 'Advanced image-to-video with cinematic realism. Adds dynamic camera motion, realistic physics, and a...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'minimax-hailuo-02-pro-i2v',
    endpoint: 'minimax-hailuo-02-pro-i2v',
    cost: 0.6,
    inputs: [],
  },
  {
    name: 'minimax-hailuo-02-standard-i2v',
    nodeType: 'minimax-hailuo-02-standard-i2v',
    id: 'minimax-hailuo-02-standard-i2v',
    category: 'video',
    description: 'Transforms an image into video with light, natural motion. Great for social media, quick animations,...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'minimax-hailuo-02-standard-i2v',
    endpoint: 'minimax-hailuo-02-standard-i2v',
    cost: 0.15,
    inputs: [],
  },
  {
    name: 'minimax-hailuo-2.3-pro-i2v',
    nodeType: 'minimax-hailuo-2.3-pro-i2v',
    id: 'minimax-hailuo-2.3-pro-i2v',
    category: 'video',
    description: 'Hailuo 2.3 Pro I2V breathes life into still images with stunning motion synthesis and cinematic came...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'minimax-hailuo-2.3-pro-i2v',
    endpoint: 'minimax-hailuo-2.3-pro-i2v',
    cost: 0.63,
    inputs: [],
  },
  {
    name: 'minimax-hailuo-2.3-standard-i2v',
    nodeType: 'minimax-hailuo-2.3-standard-i2v',
    id: 'minimax-hailuo-2.3-standard-i2v',
    category: 'video',
    description: 'Hailuo 2.3 Standard I2V converts still images into visually immersive motion clips with stable dynam...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'minimax-hailuo-2.3-standard-i2v',
    endpoint: 'minimax-hailuo-2.3-standard-i2v',
    cost: 0.36,
    inputs: [],
  },
  {
    name: 'openai-sora-2-image-to-video',
    nodeType: 'openai-sora-2-image-to-video',
    id: 'openai-sora-2-image-to-video',
    category: 'video',
    description: 'Sora 2’s I2V lets you bring still images to life by animating them into short video clips with natur...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'openai-sora-2-image-to-video',
    endpoint: 'openai-sora-2-image-to-video',
    cost: 0.8,
    inputs: [],
  },
  {
    name: 'openai-sora-2-pro-image-to-video',
    nodeType: 'openai-sora-2-pro-image-to-video',
    id: 'openai-sora-2-pro-image-to-video',
    category: 'video',
    description: 'Sora 2 Pro I2V brings still images to life, transforming them into short videos with natural motion,...',
    outputType: 'video',
    provider: 'muapi',
    muapiModelId: 'openai-sora-2-pro-image-to-video',
    endpoint: 'openai-sora-2-pro-image-to-video',
    cost: 2.4,
    inputs: [],
  },
];

/**
 * Convert muapi catalog models to CineGen node definitions.
 */
export function buildMuapiModelNodeDefinitions() {
  const defs = {};
  for (const model of MUAPI_CATALOG) {
    const inputs = model.inputs
      .filter((f) => f.fieldType === "port" || f.fieldType === "select" || f.fieldType === "number" || f.fieldType === "toggle")
      .map((f) => ({
        id: f.id,
        type: f.portType,
        label: f.label,
      }));

    const defaultData = { __modelId: model.id };
    for (const field of model.inputs) {
      if (field.default !== undefined) {
        defaultData[field.id] = field.default;
      }
    }

    defs[model.nodeType] = {
      type: model.nodeType,
      label: model.name,
      category: model.category,
      inputs,
      outputs: [{ id: model.outputType, type: model.outputType, label: model.outputType }],
      defaultData,
      isModel: true,
    };
  }
  return defs;
}