import { FIELD_TEXT, POPCORN_ELEMENT_TYPES, BACKGROUND_COLOR, BACKGROUND } from '../popcorn';

export const INITIAL_VALUES = {
  type: POPCORN_ELEMENT_TYPES.TEXT_MASK,
  [FIELD_TEXT]: 'Video Mask',
  [BACKGROUND_COLOR]: '#000000',
  [BACKGROUND]: true,
};
