export const ACTION_TYPES = {
  SET_INITIAL: 'SET_INITIAL',
  SET_LOADING: 'SET_LOADING',
  ADD_ITEMS: 'ADD_ITEMS',
  SET_HAS_MORE: 'SET_HAS_MORE',
  SET_ACTIVE_ITEM: 'SET_ACTIVE_ITEM',
  TOGGLE_ACTIVE_ITEM: 'TOGGLE_ACTIVE_ITEM',
  UPDATE_ACTIVE_ITEMS: 'UPDATE_ACTIVE_ITEMS',
  SET_FILTER: 'SET_FILTER',
  UPDATE_FILTER: 'UPDATE_FILTER',
  SET_QUERY: 'SET_QUERY',
  UPDATE_ITEM: 'UPDATE_ITEM',
  ADD_ITEM: 'ADD_ITEM',
};
