export const ACTION_TYPES = {
  INIT: 'INIT',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_VOICE: 'SET_VOICE',
  SET_IS_PRO: 'SET_IS_PRO',
  SET_PITCH: 'SET_PITCH',
  SET_SPEAKING_RATE: 'SET_SPEAKING_RATE',
};
